// netlify/functions/importGalleryItems.js
// Also supports GET requests for listing and reading gallery files
const fs = require("fs/promises");
const path = require("path");

/* guards & path helpers (same as your other fns) */
const ALLOWED_ROOTS = ["src/data/Galleries", "src/pages/Other", "src/data/Other"];
const toPosix = (p = "") => String(p).replace(/\\/g, "/");
const hasTraversal = (p = "") => p.split(/[\\/]+/).some(seg => seg === "..");
function resolveDatasetAbsolute(datasetPath) {
  const rel = toPosix(String(datasetPath || "").replace(/^\//, ""));
  if (!rel || hasTraversal(rel) || !rel.endsWith(".mjs")) throw new Error("Invalid datasetPath");
  const ok = ALLOWED_ROOTS.some(root => rel.startsWith(toPosix(root) + "/"));
  if (!ok) throw new Error("Dataset must be under src/data/Galleries or src/pages/Other");
  return path.join(process.cwd(), rel);
}

// Recursively find all .mjs files in a directory
async function findMjsFiles(dir, basePath = "", files = []) {
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      const relativePath = basePath ? `${basePath}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        await findMjsFiles(fullPath, relativePath, files);
      } else if (entry.isFile() && entry.name.endsWith(".mjs")) {
        files.push("/" + relativePath);
      }
    }
  } catch (err) {
    // Ignore directories that don't exist
    if (err.code !== "ENOENT") console.warn("findMjsFiles error:", err.message);
  }
  return files;
}

/* helpers */
const isGhost = (d) => d && d.id === "i-k4studios";
const isReal  = (d) => d && !isGhost(d);

function normalizeItem(raw) {
  const notes = raw.notes ?? raw.collectorNotes;
  const keywords = Array.isArray(raw.keywords)
    ? raw.keywords
    : Array.isArray(raw.tags)
    ? raw.tags
    : undefined;

  const out = {};
  if (raw.id != null) out.id = raw.id;
  if (raw.title != null) out.title = raw.title;
  if (raw.description != null) out.description = raw.description;
  if (raw.alt != null) out.alt = raw.alt;
  if (raw.src != null || raw.url != null) out.src = raw.src || raw.url;
  if (raw.srcXL != null) out.srcXL = raw.srcXL;
  if (raw.srcL != null) out.srcL = raw.srcL;
  if (raw.srcM != null) out.srcM = raw.srcM;
  if (raw.srcS != null) out.srcS = raw.srcS;
  if (raw.srcOriginal != null) out.srcOriginal = raw.srcOriginal;
  if (raw.buyLink != null) out.buyLink = raw.buyLink;
  if (keywords != null) out.keywords = keywords;
  if (raw.story != null) out.story = raw.story;
  if (notes != null) out.notes = notes;
  if (typeof raw.rating === "number") out.rating = raw.rating;
  if (Array.isArray(raw.galleries)) out.galleries = raw.galleries;
  if (raw.visibility != null) out.visibility = raw.visibility;
  if (typeof raw.sortOrder === "number") out.sortOrder = raw.sortOrder;
  if (raw.themes && typeof raw.themes === "object") out.themes = raw.themes;
  if (raw.contentSource != null) out.contentSource = raw.contentSource;
  // NOTE: availableSeries is NOT stored in .mjs files - it's stored only in seriesRegistry.json
  if (raw.noSketch === true) out.noSketch = true;
  // Preserve first_seen date for Photo Shoots tracking
  if (raw.first_seen != null) out.first_seen = raw.first_seen;
  // Engrained-specific fields
  if (raw.editionSize != null) out.editionSize = raw.editionSize;
  if (raw.imageSize != null) out.imageSize = raw.imageSize;
  if (raw.price != null) out.price = raw.price;
  if (raw.linkedImageId != null) out.linkedImageId = raw.linkedImageId;
  if (raw.linkedGalleryPath != null) out.linkedGalleryPath = raw.linkedGalleryPath;
  if (raw.autoGenerated != null) out.autoGenerated = raw.autoGenerated;
  if (raw.autoTitle != null) out.autoTitle = raw.autoTitle;
  return out;
}

function buildMjsJson(galleryData, exportName = "galleryData") {
  const json = JSON.stringify(galleryData.map(normalizeItem), null, 2);
  return `// Auto-generated by GalleryImporter – review & commit
export const ${exportName} = ${json};
`;
}

/* parse helper ONLY used as a fallback if client didn't send items */
function extractArrayFromMjs(code) {
  const m = code.match(/export\s+const\s+galleryData\s*=\s*(\[[\s\S]*\]);?/);
  if (!m) return null;

  // Provide a tiny String.raw shim so template literals don't explode.
  // eslint-disable-next-line no-new-func
  const fn = new Function(`
    const String = { raw: (...args) => (Array.isArray(args[0]) ? args[0][0] : String(args[0])) };
    const x = ${m[1]};
    return x;
  `);
  try { return fn(); } catch { return null; }
}

exports.handler = async (event) => {
  const headers = {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Cache-Control": "no-store"
  };

  // Handle CORS preflight
  if (event.httpMethod === "OPTIONS") {
    return { statusCode: 200, headers, body: "" };
  }

  // GET: List all gallery files or read a specific one
  if (event.httpMethod === "GET") {
    const action = event.queryStringParameters?.action;
    const galleryPath = event.queryStringParameters?.path;

    // List all gallery .mjs files
    if (action === "list") {
      try {
        let allFiles = [];
        for (const root of ALLOWED_ROOTS) {
          const rootPath = path.join(process.cwd(), root);
          const files = await findMjsFiles(rootPath, root);
          allFiles.push(...files);
        }
        return {
          statusCode: 200,
          headers,
          body: JSON.stringify({ files: allFiles.sort() })
        };
      } catch (err) {
        return {
          statusCode: 500,
          headers,
          body: JSON.stringify({ error: err.message })
        };
      }
    }

    // Read a specific gallery file
    if (galleryPath) {
      try {
        const absPath = resolveDatasetAbsolute(galleryPath);
        const code = await fs.readFile(absPath, "utf8");
        const galleryData = extractArrayFromMjs(code);
        if (!galleryData) {
          return {
            statusCode: 400,
            headers,
            body: JSON.stringify({ error: "Could not parse galleryData" })
          };
        }
        return {
          statusCode: 200,
          headers,
          body: JSON.stringify({ 
            path: galleryPath, 
            galleryData: galleryData.map(normalizeItem) 
          })
        };
      } catch (err) {
        return {
          statusCode: err.code === "ENOENT" ? 404 : 500,
          headers,
          body: JSON.stringify({ error: err.message })
        };
      }
    }

    return {
      statusCode: 400,
      headers,
      body: JSON.stringify({ error: "Missing action or path parameter" })
    };
  }

  // POST: Import items between galleries
  if (event.httpMethod !== "POST") {
    return { statusCode: 405, headers, body: JSON.stringify({ error: "Method Not Allowed" }) };
  }

  try {
    const { toDatasetPath, fromDatasetPath, selectedIds, selectedItems } = JSON.parse(event.body || "{}");
    if (!toDatasetPath || !fromDatasetPath) {
      return { statusCode: 400, body: "Missing toDatasetPath or fromDatasetPath" };
    }

    // resolve both files
    let toAbs, fromAbs;
    try { toAbs = resolveDatasetAbsolute(toDatasetPath); fromAbs = resolveDatasetAbsolute(fromDatasetPath); }
    catch (e) { return { statusCode: 400, body: e.message }; }

    try { await fs.access(toAbs); }   catch { return { statusCode: 404, body: `Target not found: ${toDatasetPath}` }; }
    try { await fs.access(fromAbs); } catch { return { statusCode: 404, body: `Source not found: ${fromDatasetPath}` }; }

    // Read target
    const toCode = await fs.readFile(toAbs, "utf8");
    const toArr  = extractArrayFromMjs(toCode);
    if (!Array.isArray(toArr)) return { statusCode: 400, body: "Failed to parse target galleryData" };
    
    // ========== PRESERVE DATA FROM EXISTING TARGET FILE ==========
    // Build maps of existing themes, noSketch by id before we modify anything
    // NOTE: availableSeries is stored in seriesRegistry.json, NOT in .mjs files
    const existingThemesById = new Map();
    const existingNoSketchById = new Map();
    for (const item of toArr) {
      if (item && item.id) {
        if (item.themes && typeof item.themes === "object") {
          existingThemesById.set(item.id, item.themes);
        }
        if (item.noSketch === true) {
          existingNoSketchById.set(item.id, true);
        }
      }
    }
    // ================================================================
    
    const toGhosts = toArr.filter(isGhost);
    let toVis    = toArr.filter(isReal);
    
    // ========== SMART MERGE DATA FOR EXISTING ITEMS ==========
    // Combine existing themes/noSketch with any incoming data
    // NOTE: availableSeries is stored in seriesRegistry.json, NOT in .mjs files
    toVis = toVis.map((item) => {
      if (!item || !item.id) return item;
      
      // --- THEMES ---
      const existingThemes = existingThemesById.get(item.id);
      const incomingThemes = item.themes && typeof item.themes === "object" ? item.themes : null;
      
      let mergedThemes = null;
      if (existingThemes && Object.keys(existingThemes).length > 0) {
        if (!incomingThemes || Object.keys(incomingThemes).length === 0) {
          mergedThemes = existingThemes;
        } else {
          mergedThemes = { ...existingThemes, ...incomingThemes };
          for (const key of Object.keys(mergedThemes)) {
            if (mergedThemes[key] == null) delete mergedThemes[key];
          }
        }
      } else if (incomingThemes) {
        mergedThemes = incomingThemes;
      }
      
      // --- NO SKETCH ---
      const existingNoSketch = existingNoSketchById.get(item.id);
      const mergedNoSketch = item.noSketch === true ? true : (existingNoSketch === true ? true : undefined);
      
      // Build result with preserved/merged data
      const result = { ...item };
      if (mergedThemes && Object.keys(mergedThemes).length > 0) {
        result.themes = mergedThemes;
      }
      if (mergedNoSketch) {
        result.noSketch = true;
      }
      
      return result;
    });
    // ==============================================================

    // Get source items either from client (preferred) or by parsing the file
    let sourceVis = Array.isArray(selectedItems) && selectedItems.length
      ? selectedItems.filter(isReal)
      : null;

    if (!sourceVis) {
      const fromCode = await fs.readFile(fromAbs, "utf8");
      const fromArr  = extractArrayFromMjs(fromCode);
      if (!Array.isArray(fromArr)) return { statusCode: 400, body: "Failed to parse source galleryData" };
      const all = fromArr.filter(isReal);
      const want = Array.isArray(selectedIds) && selectedIds.length ? new Set(selectedIds) : null;
      sourceVis = want ? all.filter(x => want.has(x.id)) : all;
    }

    // Append, skipping id collisions; resequence sortOrder
    const existingIds = new Set(toVis.map(x => x.id));
    const picked = [];
    const skippedIds = [];
    let next = toVis.length;

    for (const it of sourceVis) {
      if (!it?.id) continue;
      if (existingIds.has(it.id)) { skippedIds.push(it.id); continue; }
      picked.push({ ...it, sortOrder: next++ });
    }

    const finalArr = toGhosts.concat(toVis, picked);
    const outText  = buildMjsJson(finalArr, "galleryData");
    await fs.writeFile(toAbs, outText, "utf8");

    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        ok: true,
        to: toDatasetPath,
        from: fromDatasetPath,
        imported: picked.length,
        skippedIds,
        total: finalArr.length,
      }),
    };
  } catch (err) {
    console.error(err);
    return { statusCode: 500, body: err?.message || "Server error" };
  }
};
