// netlify/functions/updateThemes.js

const fs = require("fs");
const path = require("path");

/* ===== path guards ===== */
const ALLOWED_ROOTS = ["src/data/themes"];
const toPosix = (p = "") => String(p).replace(/\\/g, "/");
const hasTraversal = (p = "") => p.split(/[\\/]+/).some(seg => seg === "..");

function resolveThemePathAbsolute(themePath) {
  const rel = toPosix(String(themePath || "").replace(/^\//, "")); // strip leading "/"
  if (!rel || hasTraversal(rel) || !rel.endsWith(".mjs")) {
    throw new Error("Invalid theme file path");
  }
  const ok = ALLOWED_ROOTS.some(root => rel.startsWith(toPosix(root) + "/"));
  if (!ok) throw new Error("Theme file must be under src/data/themes");
  return path.join(process.cwd(), rel);
}

exports.handler = async (event, context) => {
  try {
    if (event.httpMethod !== "POST") {
      return {
        statusCode: 405,
        body: "Method Not Allowed",
      };
    }

    const { themeFilePath, themesArray } = JSON.parse(event.body || "{}");

    if (!themeFilePath || !Array.isArray(themesArray)) {
      return {
        statusCode: 400,
        body: "Invalid payload",
      };
    }

    // Validate and resolve path
    let resolvedPath;
    try {
      resolvedPath = resolveThemePathAbsolute(themeFilePath);
    } catch (e) {
      return { statusCode: 400, body: e.message };
    }

    // Build the final file text with documentation header
    const header = `// Auto-generated by ThemeBuilder — review & commit

/**
 * THEMES MASTER FILE (Registry/Index)
 * ------------------------------------
 * This file is the THEME REGISTRY. It stores metadata for each theme.
 * Image membership is stored in the gallery .mjs files themselves.
 *
 * Each theme tracks:
 *  - name: Display name for the theme
 *  - slug: URL-safe identifier (used in URLs and as key in image.themes)
 *  - description: SEO description for the theme
 *  - dataset: Path to the gallery .mjs file this theme draws from
 *  - visible: Whether theme appears in dropdowns/buttons (true/false)
 *  - createdAt / updatedAt: Timestamps
 *
 * HOW THEME MEMBERSHIP WORKS:
 * Each image in its gallery .mjs file stores its theme membership:
 *   themes: { "black-hats": 0, "cowboys-and-horses": 5 }
 *   (key = theme slug, value = display order within that theme)
 *
 * TO HIDE A THEME: Set visible: false
 * TO DELETE A THEME: Remove entry here AND clean themes property from gallery images
 */

`;
    const fileText = header + `export const themes = ${JSON.stringify(themesArray, null, 2)};\n`;

    // Write file to disk
    fs.writeFileSync(resolvedPath, fileText, "utf8");

    return {
      statusCode: 200,
      body: JSON.stringify({
        success: true,
        written: resolvedPath,
      }),
    };
  } catch (err) {
    console.error("Error updating themes.mjs:", err);
    return {
      statusCode: 500,
      body: "Internal Server Error: " + err.message,
    };
  }
};
