// netlify/functions/updateGalleryOrder.js
const fs = require("fs/promises");
const path = require("path");

/* ===== path guards & helpers (new) ===== */
const ALLOWED_ROOTS = ["src/data/Galleries", "src/pages/Other", "src/data/Other"]; // support all trees
const toPosix = (p = "") => String(p).replace(/\\/g, "/");
const hasTraversal = (p = "") => p.split(/[\\/]+/).some(seg => seg === "..");

function resolveDatasetAbsolute(datasetPath) {
  const rel = toPosix(String(datasetPath || "").replace(/^\//, "")); // strip leading "/"
  if (!rel || hasTraversal(rel) || !rel.endsWith(".mjs")) {
    throw new Error("Invalid datasetPath");
  }
  const ok = ALLOWED_ROOTS.some(root => rel.startsWith(toPosix(root) + "/"));
  if (!ok) throw new Error("Dataset must be under src/data/Galleries, src/pages/Other, or src/data/Other");
  return path.join(process.cwd(), rel);
}

/* ===== your existing helpers ===== */
function isGhost(d) { return d && d.id === "i-k4studios"; }
function isReal(d) { return d && !isGhost(d); }

function normalizeSmartPunctuation(value) {
  return typeof value === "string"
    ? value
        .replace(/[\u2018\u2019]/g, "'")
        .replace(/[\u201C\u201D]/g, '"')
        .replace(/[\u2013\u2014]/g, "-")
        .replace(/\u2026/g, "...")
    : value;
}

function normalizeItem(raw) {
  const notes = normalizeSmartPunctuation(raw.notes ?? raw.collectorNotes);
  const keywords = Array.isArray(raw.keywords)
    ? raw.keywords
    : Array.isArray(raw.tags)
    ? raw.tags
    : undefined;

  const out = {};
  if (raw.id != null) out.id = normalizeSmartPunctuation(raw.id);
  if (raw.title != null) out.title = normalizeSmartPunctuation(raw.title);
  if (raw.description != null) out.description = normalizeSmartPunctuation(raw.description);
  if (raw.alt != null) out.alt = normalizeSmartPunctuation(raw.alt);
  if (raw.src != null || raw.url != null) out.src = normalizeSmartPunctuation(raw.src || raw.url);
  if (raw.srcXL != null) out.srcXL = normalizeSmartPunctuation(raw.srcXL);
  if (raw.srcL != null) out.srcL = normalizeSmartPunctuation(raw.srcL);
  if (raw.srcM != null) out.srcM = normalizeSmartPunctuation(raw.srcM);
  if (raw.srcS != null) out.srcS = normalizeSmartPunctuation(raw.srcS);
  if (raw.srcOriginal != null) out.srcOriginal = normalizeSmartPunctuation(raw.srcOriginal);
  if (raw.buyLink != null) out.buyLink = normalizeSmartPunctuation(raw.buyLink);
  if (keywords != null) out.keywords = keywords.map(normalizeSmartPunctuation);
  if (raw.story != null) out.story = normalizeSmartPunctuation(raw.story);
  if (notes != null) out.notes = notes;
  if (typeof raw.rating === "number") out.rating = raw.rating;
  if (Array.isArray(raw.galleries)) out.galleries = raw.galleries.map(normalizeSmartPunctuation);
  if (raw.visibility != null) out.visibility = normalizeSmartPunctuation(raw.visibility);
  if (typeof raw.sortOrder === "number") out.sortOrder = raw.sortOrder;
  if (raw.themes && typeof raw.themes === "object") out.themes = raw.themes;
  if (raw.contentSource != null) out.contentSource = normalizeSmartPunctuation(raw.contentSource);
  // NOTE: availableSeries is NOT stored in .mjs files - it's stored only in seriesRegistry.json
  if (raw.noSketch === true) out.noSketch = true;
  // Preserve first_seen date for Photo Shoots tracking
  if (raw.first_seen != null) out.first_seen = normalizeSmartPunctuation(raw.first_seen);
  // Preserve Engrained-specific fields (stored in .mjs, not seriesRegistry)
  if (raw.editionSize != null) out.editionSize = raw.editionSize;
  if (raw.imageSize != null) out.imageSize = normalizeSmartPunctuation(raw.imageSize);
  if (raw.price != null) out.price = raw.price;
  if (raw.linkedImageId != null) out.linkedImageId = normalizeSmartPunctuation(raw.linkedImageId);
  if (raw.linkedGalleryPath != null) out.linkedGalleryPath = normalizeSmartPunctuation(raw.linkedGalleryPath);
  if (raw.autoGenerated != null) out.autoGenerated = raw.autoGenerated;
  if (raw.autoTitle != null) out.autoTitle = normalizeSmartPunctuation(raw.autoTitle);
  return out;
}

function buildMjsJson(galleryData, exportName = "galleryData") {
  const json = JSON.stringify(galleryData.map(normalizeItem), null, 2);
  return `// Auto-generated by GalleryOrderer – review & commit
export const ${exportName} = ${json};
`;
}

/* Parse helper that handles both JSON format and JS object literal format with String.raw */
function extractArrayFromMjs(code) {
  const m = code.match(/export\s+const\s+galleryData\s*=\s*(\[[\s\S]*\]);?/);
  if (!m) return null;

  // First try JSON.parse (faster, works for JSON-formatted files)
  try {
    return JSON.parse(m[1]);
  } catch {
    // Fall back to Function eval with String.raw shim for JS object literal format
    try {
      // eslint-disable-next-line no-new-func
      const fn = new Function(`
        const String = { raw: (...args) => (Array.isArray(args[0]) ? args[0][0] : String(args[0])) };
        const x = ${m[1]};
        return x;
      `);
      return fn();
    } catch { return null; }
  }
}

async function readGalleryArray(absPath) {
  const code = await fs.readFile(absPath, "utf8");
  const arr = extractArrayFromMjs(code);
  return Array.isArray(arr) ? arr : [];
}

function mergePreservedFields(working, existingArr) {
  const existingThemesById = new Map();
  const existingNoSketchById = new Map();

  for (const item of existingArr) {
    if (!item || !item.id) continue;
    if (item.themes && typeof item.themes === "object") {
      existingThemesById.set(item.id, item.themes);
    }
    if (item.noSketch === true) {
      existingNoSketchById.set(item.id, true);
    }
  }

  return working.map((item) => {
    if (!item || !item.id) return item;

    const existingThemes = existingThemesById.get(item.id);
    const incomingThemes = item.themes && typeof item.themes === "object" ? item.themes : null;

    let mergedThemes = null;
    if (existingThemes && Object.keys(existingThemes).length > 0) {
      if (!incomingThemes || Object.keys(incomingThemes).length === 0) {
        mergedThemes = existingThemes;
      } else {
        mergedThemes = { ...existingThemes, ...incomingThemes };
        for (const key of Object.keys(mergedThemes)) {
          if (mergedThemes[key] == null) delete mergedThemes[key];
        }
      }
    } else if (incomingThemes) {
      mergedThemes = incomingThemes;
    }

    const existingNoSketch = existingNoSketchById.get(item.id);
    const mergedNoSketch = item.noSketch === true ? true : (existingNoSketch === true ? true : undefined);

    const result = { ...item };
    if (mergedThemes && Object.keys(mergedThemes).length > 0) {
      result.themes = mergedThemes;
    }
    if (mergedNoSketch) {
      result.noSketch = true;
    }

    return result;
  });
}

function finalizeGalleryArray(working, orderIds) {
  const ghosts = working.filter(isGhost);
  let visibles = working.filter(isReal);

  if (Array.isArray(orderIds) && orderIds.length) {
    const byId = new Map(visibles.map((it) => [it.id, it]));
    const used = new Set();
    const ordered = [];
    for (const id of orderIds) {
      const it = byId.get(id);
      if (it && !used.has(id)) {
        ordered.push(it);
        used.add(id);
      }
    }
    for (const it of visibles) {
      if (!used.has(it.id)) ordered.push(it);
    }
    visibles = ordered;
  }

  visibles.forEach((it, i) => {
    it.sortOrder = i;
  });

  return ghosts.concat(visibles);
}

async function writeGalleryArray(absPath, working, orderIds) {
  const existingArr = await readGalleryArray(absPath);
  const merged = mergePreservedFields(working, existingArr);
  const finalArr = finalizeGalleryArray(merged, orderIds);
  const outText = buildMjsJson(finalArr, "galleryData");
  await fs.writeFile(absPath, outText, "utf8");
  return finalArr;
}

/* ===== handler ===== */
exports.handler = async (event) => {
  try {
    if (event.httpMethod !== "POST") {
      return { statusCode: 405, body: "Method Not Allowed" };
    }

    const body = JSON.parse(event.body || "{}");
    let { datasetPath, orderIds, fullArray, sourceArray } = body;

    if (body.action === "transfer") {
      const mode = body.mode === "copy" ? "copy" : "move";
      const sourceDatasetPath = body.sourceDatasetPath;
      const targetDatasetPath = body.targetDatasetPath;
      const itemIds = Array.isArray(body.itemIds) ? Array.from(new Set(body.itemIds.filter(Boolean))) : [];

      if (!sourceDatasetPath || !targetDatasetPath || itemIds.length === 0) {
        return { statusCode: 400, body: "Missing sourceDatasetPath, targetDatasetPath, or itemIds" };
      }

      let sourceAbsPath;
      let targetAbsPath;
      try {
        sourceAbsPath = resolveDatasetAbsolute(sourceDatasetPath);
        targetAbsPath = resolveDatasetAbsolute(targetDatasetPath);
      } catch (e) {
        return { statusCode: 400, body: e.message };
      }

      const [sourceArr, targetArr] = await Promise.all([
        readGalleryArray(sourceAbsPath),
        readGalleryArray(targetAbsPath),
      ]);

      const sourceById = new Map(sourceArr.filter(isReal).map((item) => [item.id, item]));
      const transferItems = itemIds.map((id) => sourceById.get(id)).filter(Boolean);

      if (transferItems.length === 0) {
        return { statusCode: 404, body: "Requested itemIds were not found in the source gallery" };
      }

      const targetIdSet = new Set(targetArr.filter(isReal).map((item) => item.id));
      const itemsAlreadyInTarget = transferItems.filter((item) => targetIdSet.has(item.id));
      const itemsToAdd = transferItems.filter((item) => !targetIdSet.has(item.id));
      const transferIdSet = new Set(transferItems.map((item) => item.id));

      let updatedTarget = targetArr.slice();
      if (itemsToAdd.length > 0) {
        updatedTarget = targetArr.concat(itemsToAdd.map((item, index) => ({
          ...item,
          sortOrder: targetArr.filter(isReal).length + index,
        })));
      }

      const updatedSource = mode === "move"
        ? sourceArr.filter((item) => !transferIdSet.has(item.id))
        : sourceArr.slice();

      const [targetFinal, sourceFinal] = await Promise.all([
        itemsToAdd.length > 0 ? writeGalleryArray(targetAbsPath, updatedTarget) : Promise.resolve(targetArr),
        mode === "move" ? writeGalleryArray(sourceAbsPath, updatedSource) : Promise.resolve(sourceArr),
      ]);

      return {
        statusCode: 200,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ok: true,
          mode,
          transferred: transferItems.length,
          addedToTarget: itemsToAdd.length,
          alreadyInTarget: itemsAlreadyInTarget.length,
          sourceItems: sourceFinal.length,
          targetItems: targetFinal.length,
        }),
      };
    }

    if (!datasetPath || typeof datasetPath !== "string") {
      return { statusCode: 400, body: "Missing datasetPath" };
    }

    // NEW: safe resolve that accepts Galleries + Other
    let absPath;
    try {
      absPath = resolveDatasetAbsolute(datasetPath);
    } catch (e) {
      return { statusCode: 400, body: e.message };
    }

    try {
      await fs.access(absPath);
    } catch {
      return { statusCode: 404, body: `Dataset not found: ${datasetPath}` };
    }

    // Need a complete array to rebuild the file
    let working = Array.isArray(fullArray) ? fullArray.slice() : null;
    if (!working) {
      if (!Array.isArray(sourceArray)) {
        return { statusCode: 400, body: "Missing fullArray or sourceArray" };
      }
      working = sourceArray.slice();
    }

    const finalArr = await writeGalleryArray(absPath, working, orderIds);

    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ok: true, written: datasetPath, items: finalArr.length }),
    };
  } catch (err) {
    console.error(err);
    return { statusCode: 500, body: err?.message || "Server error" };
  }
};
