// netlify/functions/updateGalleryOrder.js
const fs = require("fs/promises");
const path = require("path");

/* ===== path guards & helpers (new) ===== */
const ALLOWED_ROOTS = ["src/data/Galleries", "src/pages/Other", "src/data/Other"]; // support all trees
const toPosix = (p = "") => String(p).replace(/\\/g, "/");
const hasTraversal = (p = "") => p.split(/[\\/]+/).some(seg => seg === "..");

function resolveDatasetAbsolute(datasetPath) {
  const rel = toPosix(String(datasetPath || "").replace(/^\//, "")); // strip leading "/"
  if (!rel || hasTraversal(rel) || !rel.endsWith(".mjs")) {
    throw new Error("Invalid datasetPath");
  }
  const ok = ALLOWED_ROOTS.some(root => rel.startsWith(toPosix(root) + "/"));
  if (!ok) throw new Error("Dataset must be under src/data/Galleries, src/pages/Other, or src/data/Other");
  return path.join(process.cwd(), rel);
}

/* ===== your existing helpers ===== */
function isGhost(d) { return d && d.id === "i-k4studios"; }
function isReal(d) { return d && !isGhost(d); }

function normalizeItem(raw) {
  const notes = raw.notes ?? raw.collectorNotes;
  const keywords = Array.isArray(raw.keywords)
    ? raw.keywords
    : Array.isArray(raw.tags)
    ? raw.tags
    : undefined;

  const out = {};
  if (raw.id != null) out.id = raw.id;
  if (raw.title != null) out.title = raw.title;
  if (raw.description != null) out.description = raw.description;
  if (raw.alt != null) out.alt = raw.alt;
  if (raw.src != null || raw.url != null) out.src = raw.src || raw.url;
  if (raw.srcXL != null) out.srcXL = raw.srcXL;
  if (raw.srcL != null) out.srcL = raw.srcL;
  if (raw.srcM != null) out.srcM = raw.srcM;
  if (raw.srcS != null) out.srcS = raw.srcS;
  if (raw.srcOriginal != null) out.srcOriginal = raw.srcOriginal;
  if (raw.buyLink != null) out.buyLink = raw.buyLink;
  if (keywords != null) out.keywords = keywords;
  if (raw.story != null) out.story = raw.story;
  if (notes != null) out.notes = notes;
  if (typeof raw.rating === "number") out.rating = raw.rating;
  if (Array.isArray(raw.galleries)) out.galleries = raw.galleries;
  if (raw.visibility != null) out.visibility = raw.visibility;
  if (typeof raw.sortOrder === "number") out.sortOrder = raw.sortOrder;
  if (raw.themes && typeof raw.themes === "object") out.themes = raw.themes;
  if (raw.contentSource != null) out.contentSource = raw.contentSource;
  // NOTE: availableSeries is NOT stored in .mjs files - it's stored only in seriesRegistry.json
  if (raw.noSketch === true) out.noSketch = true;
  // Preserve first_seen date for Photo Shoots tracking
  if (raw.first_seen != null) out.first_seen = raw.first_seen;
  // Preserve Engrained-specific fields (stored in .mjs, not seriesRegistry)
  if (raw.editionSize != null) out.editionSize = raw.editionSize;
  if (raw.imageSize != null) out.imageSize = raw.imageSize;
  if (raw.price != null) out.price = raw.price;
  if (raw.linkedImageId != null) out.linkedImageId = raw.linkedImageId;
  if (raw.linkedGalleryPath != null) out.linkedGalleryPath = raw.linkedGalleryPath;
  if (raw.autoGenerated != null) out.autoGenerated = raw.autoGenerated;
  if (raw.autoTitle != null) out.autoTitle = raw.autoTitle;
  return out;
}

function buildMjsJson(galleryData, exportName = "galleryData") {
  const json = JSON.stringify(galleryData.map(normalizeItem), null, 2);
  return `// Auto-generated by GalleryOrderer – review & commit
export const ${exportName} = ${json};
`;
}

/* Parse helper that handles both JSON format and JS object literal format with String.raw */
function extractArrayFromMjs(code) {
  const m = code.match(/export\s+const\s+galleryData\s*=\s*(\[[\s\S]*\]);?/);
  if (!m) return null;

  // First try JSON.parse (faster, works for JSON-formatted files)
  try {
    return JSON.parse(m[1]);
  } catch {
    // Fall back to Function eval with String.raw shim for JS object literal format
    try {
      // eslint-disable-next-line no-new-func
      const fn = new Function(`
        const String = { raw: (...args) => (Array.isArray(args[0]) ? args[0][0] : String(args[0])) };
        const x = ${m[1]};
        return x;
      `);
      return fn();
    } catch { return null; }
  }
}

/* ===== handler ===== */
exports.handler = async (event) => {
  try {
    if (event.httpMethod !== "POST") {
      return { statusCode: 405, body: "Method Not Allowed" };
    }

    const body = JSON.parse(event.body || "{}");
    let { datasetPath, orderIds, fullArray, sourceArray } = body;

    if (!datasetPath || typeof datasetPath !== "string") {
      return { statusCode: 400, body: "Missing datasetPath" };
    }

    // NEW: safe resolve that accepts Galleries + Other
    let absPath;
    try {
      absPath = resolveDatasetAbsolute(datasetPath);
    } catch (e) {
      return { statusCode: 400, body: e.message };
    }

    try {
      await fs.access(absPath);
    } catch {
      return { statusCode: 404, body: `Dataset not found: ${datasetPath}` };
    }

    // ========== PRESERVE THEMES AND NOSKETCH FROM EXISTING FILE ==========
    // Read the existing file to extract current data that might not be in client state
    // This prevents stale client data from wiping out themes, noSketch
    // NOTE: availableSeries is stored in seriesRegistry.json, NOT in .mjs files
    let existingThemesById = new Map();
    let existingNoSketchById = new Map();
    try {
      const existingCode = await fs.readFile(absPath, "utf8");
      // Extract the array using helper that handles both JSON and JS object literal formats
      const existingArr = extractArrayFromMjs(existingCode);
      if (Array.isArray(existingArr)) {
        for (const item of existingArr) {
          if (item && item.id) {
            if (item.themes && typeof item.themes === "object") {
              existingThemesById.set(item.id, item.themes);
            }
            if (item.noSketch === true) {
              existingNoSketchById.set(item.id, true);
            }
          }
        }
        console.log(`Preserved data from existing file: ${existingNoSketchById.size} noSketch, ${existingThemesById.size} themes`);
      } else {
        console.warn("Could not parse existing gallery for data preservation");
      }
    } catch (readErr) {
      console.warn("Could not read existing file for data preservation:", readErr.message);
    }
    // =================================================================================

    // Need a complete array to rebuild the file
    let working = Array.isArray(fullArray) ? fullArray.slice() : null;
    if (!working) {
      if (!Array.isArray(sourceArray)) {
        return { statusCode: 400, body: "Missing fullArray or sourceArray" };
      }
      working = sourceArray.slice();
    }

    // ========== MERGE PRESERVED DATA INTO WORKING DATA ==========
    // SMART MERGE: Preserve themes, noSketch from existing file
    // NOTE: availableSeries is stored in seriesRegistry.json, NOT in .mjs files
    working = working.map((item) => {
      if (!item || !item.id) return item;
      
      // --- THEMES ---
      const existingThemes = existingThemesById.get(item.id);
      const incomingThemes = item.themes && typeof item.themes === "object" ? item.themes : null;
      
      let mergedThemes = null;
      if (existingThemes && Object.keys(existingThemes).length > 0) {
        if (!incomingThemes || Object.keys(incomingThemes).length === 0) {
          mergedThemes = existingThemes;
        } else {
          mergedThemes = { ...existingThemes, ...incomingThemes };
          for (const key of Object.keys(mergedThemes)) {
            if (mergedThemes[key] == null) delete mergedThemes[key];
          }
        }
      } else if (incomingThemes) {
        mergedThemes = incomingThemes;
      }
      
      // --- NO SKETCH ---
      const existingNoSketch = existingNoSketchById.get(item.id);
      const mergedNoSketch = item.noSketch === true ? true : (existingNoSketch === true ? true : undefined);
      
      // Build result with preserved/merged data
      const result = { ...item };
      if (mergedThemes && Object.keys(mergedThemes).length > 0) {
        result.themes = mergedThemes;
      }
      if (mergedNoSketch) {
        result.noSketch = true;
      }
      
      return result;
    });
    // ==============================================================

    const ghosts = working.filter(isGhost);
    let visibles = working.filter(isReal);

    if (Array.isArray(orderIds) && orderIds.length) {
      const byId = new Map(visibles.map((it) => [it.id, it]));
      const used = new Set();
      const ordered = [];
      for (const id of orderIds) {
        const it = byId.get(id);
        if (it && !used.has(id)) {
          ordered.push(it);
          used.add(id);
        }
      }
      for (const it of visibles) if (!used.has(it.id)) ordered.push(it);
      visibles = ordered;
    }

    // resequence sortOrder (0..n-1)
    visibles.forEach((it, i) => { it.sortOrder = i; });

    const finalArr = ghosts.concat(visibles);
    const outText = buildMjsJson(finalArr, "galleryData");
    await fs.writeFile(absPath, outText, "utf8");

    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ok: true, written: datasetPath, items: finalArr.length }),
    };
  } catch (err) {
    console.error(err);
    return { statusCode: 500, body: err?.message || "Server error" };
  }
};
