[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200



[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Civil-War-Portraits/Color/i-:id/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Civil-War-Portraits/Color/i-:id/index.html"
status = 200

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Civil-War-Portraits/Black-White/i-:id/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Civil-War-Portraits/Black-White/i-:id/index.html"
status = 200

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/i-:id/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/i-:id/index.html"
status = 200

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White/i-:id/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White/i-:id/index.html"
status = 200

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Roaring-20s-Portraits/Color/i-:id/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Roaring-20s-Portraits/Color/i-:id/index.html"
status = 200

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Roaring-20s-Portraits/Black-White/i-:id/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Roaring-20s-Portraits/Black-White/i-:id/index.html"
status = 200

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/Color/i-:id/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/Color/i-:id/index.html"
status = 200

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/Black-White/i-:id/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/Black-White/i-:id/index.html"
status = 200

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Transportation/Trains-Color/i-:id/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Transportation/Trains-Color/i-:id/index.html"
status = 200

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Transportation/Trains-Black-White/i-:id/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Transportation/Trains-Black-White/i-:id/index.html"
status = 200

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Transportation/Cars/i-:id/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Transportation/Cars/i-:id/index.html"
status = 200

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Transportation/Boats/i-:id/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Transportation/Boats/i-:id/index.html"
status = 200

[[redirects]]
from = "/Other/K4-Select-Series/Engrained/Engrained-Series/i-:id/*"
to = "/Other/K4-Select-Series/Engrained/Engrained-Series/i-:id/index.html"
status = 200

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Location/West"
to = "/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Location/West/Gallery"
status = 301
force = true

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Location/International"
to = "/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Location/International/Gallery"
status = 301
force = true

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Location/Northeast"
to = "/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Location/Northeast/Gallery"
status = 301
force = true

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Location/South"
to = "/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Location/South/Gallery"
status = 301
force = true

[[redirects]]
from = "/Other/K4-Select-Series/Series-1"
to = "https://wayne-heim.smugmug.com/Other/K4-Select-Series/Series-1"
status = 301
force = true

[[redirects]]
from = "/Other/K4-Select-Series/Series-2"
to = "https://wayne-heim.smugmug.com/Other/K4-Select-Series/Series-2"
status = 301
force = true

[[redirects]]
from = "/Other/K4-Select-Series/Series-3"
to = "/Other/K4-Select-Series/Engrained"
status = 301
force = true

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[edge_functions]]
  function = "block-countries"
  path = "/*"

[[redirects]]
from = "/*/A"
to = "https://wayne-heim.smugmug.com/:splat/A"
status = 301
force = true
[[redirects]]
from = "/Galleries/Fine-Art-Photography/Portraits/Color/i-nxz6Zxg/A"
to = "https://wayne-heim.smugmug.com/Galleries/Fine-Art-Photography/Portraits/Color/i-nxz6Zxg/A"
status = 301
force = true

[[redirects]]
from = "/black-and-white-western-photos"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White"
status = 301
force = true

[[redirects]]
from = "/black-and-white-western-photos/"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White"
status = 301
force = true

[[redirects]]
from = "/historical-reenactment-photography"
to = "/Galleries/Fine-Art-Photography/Miscellaneous/Reenactments"
status = 301
force = true

[[redirects]]
from = "/historical-reenactment-photography/"
to = "/Galleries/Fine-Art-Photography/Miscellaneous/Reenactments"
status = 301
force = true

[[redirects]]
from = "/Black-and-White-Western-Photos"
to = "https://wayne-heim.smugmug.com/Black-and-White-Western-Photos"
status = 301
force = true

[[redirects]]
from = "/Black-and-White-Western-Photos/"
to = "https://wayne-heim.smugmug.com/Black-and-White-Western-Photos"
status = 301
force = true

[[redirects]]
from = "/k4-studios-site-map"
to = "/sitemap.xml"
status = 301
force = true

[[redirects]]
from = "/k4-studios-site-map/"
to = "/sitemap.xml"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White/i-D2fQjDQ/A"
to = "https://wayne-heim.smugmug.com/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White/i-D2fQjDQ/A"
status = 301
force = true
[[redirects]]
from = "/Galleries/:splat/i-:id/A"
to = "https://wayne-heim.smugmug.com/Galleries/:splat/i-:id/A"
status = 301
force = true
[[redirects]]
from = "/Galleries/zPainterly-Western-Cowboy-Portraits/Color/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/:splat"
status = 301
force = true
[[redirects]]
from = "/Galleries/Fine-Art-Photography/Landscapes/By-Theme/Black-White/Black-White*"
to = "/Galleries/Fine-Art-Photography/Landscapes/By-Theme/Black-White/:splat"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White Backup/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White/:splat"
status = 301
force = true
[[redirects]]
from = "/Galleries/Fine-Art-Photography/Landscapes/By-Theme/Water/Water/*"
to = "/Galleries/Fine-Art-Photography/Landscapes/By-Theme/Water/:splat"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Art-of-War-WWII"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/War"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Roaring-20s-Portraits/Black-White.mjs/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Roaring-20s-Portraits/Black-White/:splat"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color Backup/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/:splat"
status = 301
force = true
[[redirects]]
from = "/m/opt/*"
to = "/Glossary"
status = 301
force = true

[[redirects]]
from = "/m/opt"
to = "/Glossary"
status = 301
force = true

[[redirects]]
from = "/m/opt/"
to = "/Glossary"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/Portraits/Color copy/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/Portraits/Color/:splat"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/Portraits/Color%20copy/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/Portraits/Color/:splat"
status = 301
force = true
[[redirects]]
from = "/hack/*"
to = "/Glossary"
status = 301
force = true
[[redirects]]
from = "/Galleries/zPainterly-Western-Cowboy-Portraits/BlackWhite/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White/:splat"
status = 301
force = true
[[redirects]]
from = "/api/v2/*"
to = "/Glossary"
status = 301
force = true
[[redirects]]
from = "/api/*"
to = "/Glossary"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color-back2/Color fixed/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/:splat"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color-back2/Color%20fixed/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/:splat"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Civil-War-Portraits/Color.mjs/i-:id"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Civil-War-Portraits/Color/i-:id"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color-back2/Color 1src/i-:id"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/i-:id"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color-back2/Color%201src/i-:id"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/i-:id"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color-back2/Color%201src/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/:splat"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Miscellaneous/Portraits copy/i-:id"
to = "/Galleries/Painterly-Fine-Art-Photography/Miscellaneous/Portraits/i-:id"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Miscellaneous/Portraits%20copy/i-:id"
to = "/Galleries/Painterly-Fine-Art-Photography/Miscellaneous/Portraits/i-:id"
status = 301
force = true
[[redirects]]
from = "/Other/Photo-Shoots/*"
to = "https://wayne-heim.smugmug.com/Other/Photo-Shoots/:splat"
status = 301
force = true

[[redirects]]
from = "/Slideshows/*"
to = "https://wayne-heim.smugmug.com/Slideshows/:splat"
status = 301
force = true

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Native-American"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/NA-Color"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Theme/Sunsets/Sunsets/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Theme/Sunsets/:splat"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color-back2/Color fixed/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/:splat"
status = 301
force = true
[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color-back2/Color 1src/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/:splat"
status = 301
force = true
[[redirects]]
from = "/keyword/*"
to = "/Glossary"
status = 301
force = true

[[redirects]]
from = "/keyword"
to = "/Glossary"
status = 301
force = true

[[redirects]]
from = "/keyword/"
to = "/Glossary"
status = 301
force = true
[[redirects]]
from = "/Other/Photo-Shoots-and-Themes/*"
to = "https://wayne-heim.smugmug.com/Other/Photo-Shoots/:splat"
status = 301
force = true


[[redirects]]
from = "/bio"
to = "/Other/Bio"
status = 301
force = true


[[redirects]]
from = "/news-awards"
to = "/News-Awards"
status = 301
force = true

[[redirects]]
from = "/news-awards/"
to = "/News-Awards"
status = 301
force = true

[[redirects]]
from = "/search"
to = "/Glossary"
status = 301
force = true

[[redirects]]
from = "/search/"
to = "/Glossary"
status = 301
force = true

[[redirects]]
from = "/blog-thoughts-and-ideas"
to = "/Blog"
status = 301
force = true

[[redirects]]
from = "/blog-thoughts-and-ideas/"
to = "/Blog"
status = 301
force = true

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color copy/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/:splat"
status = 301
force = true

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color%20copy/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/:splat"
status = 301
force = true

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White copy/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White/:splat"
status = 301
force = true

[[redirects]]
from = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White%20copy/*"
to = "/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White/:splat"
status = 301
force = true

[build]
  command = "npm run build && node scripts/purge-cloudflare.js"
