export const entranceData = {
  title: "Painterly Cowboy Fine Art Photography – Western Prints <span style=\"white-space:nowrap\">by Wayne Heim</span>",
  subtitle: "Cowboy Portraits, Western Fine Art & Story-Driven Frontier Imagery",

  keywords: [
    "Western Cowboy Portraits",
    "painterly cowboy photography",
    "Western fine art photography",
    "cowboy art prints",
    "One-Image Movie",
    "wild west painterly photography",
    "frontier photography",
    "Americana photography",
    "western grit",
    "cowboy fine art prints",
    "western portrait art",
    "authentic frontier art prints",
    "Wayne Heim cowboy photography",
    "Facing History photography"
  ],

  description:
    "Explore painterly cowboy fine art photography that blends authentic Western grit with cinematic, story-driven artistry. Each portrait by Wayne Heim is crafted in the field, capturing real cowboys, ranch hands, and seasoned reenactors in the dust, sun, and wind of the American West. These Western fine art prints offer collectors a powerful fusion of realism, painterly atmosphere, and narrative depth—perfect for anyone seeking cowboy wall art, Western photography, or frontier storytelling.",
  
  details:
    `Every image in this gallery is created on location—never staged in a studio, never generated by AI, and never built with Hollywood shortcuts. Wayne Heim's painterly fine-art methods merge illustrative toning, classical composition, and atmospheric Western light to produce works that feel like scenes from a living frontier tale. Many images include Collector Notes, offering behind-the-scenes insight into composition, narrative cues, artistic lineage, and the One-Image Movie principles that guide Wayne's storytelling-first approach. These portraits do more than portray cowboys—they invite viewers into the mythic, weathered, and deeply human West.<br><br>These works are part of Wayne Heim's broader exploration of <a href="/Western-Fine-Art-Photography" style="color:#85644b; text-decoration:underline; transition:color 0.2s;" onmouseover="this.style.color='#a74219'" onmouseout="this.style.color='#85644b'">Western Fine Art Photography</a>, focusing on character, story, and the human West.`,
  
  image: {
    id: "i-44jcjTQ",
    src: "https://photos.smugmug.com/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color/i-44jcjTQ/3/MgTD8rSCgsDJVpFJp8MMrqrC5fFZGT7qHBHjvjbGR/XL/cowboy%20art%20_O1H0384-Edit-2-Edit-2-Edit-2-XL.jpg",
    alt: "Painterly cowboy fine art portrait – The Old Hand by Wayne Heim",
    caption: "\"The Old Hand\" – Painterly cowboy fine art photography",
  },

  breadcrumb: 
  `<a href="/Galleries/Painterly-Fine-Art-Photography/Facing-History" style="color: inherit; text-decoration: none; cursor: pointer; pointer-events: auto; position: relative; z-index: 9999; transition: color 0.2s ease;" onmouseover="this.style.color='red'" onmouseout="this.style.color='inherit'">Facing History</a> | <a href="/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits" style="color: inherit; text-decoration: none; cursor: pointer; pointer-events: auto; position: relative; z-index: 9999; transition: color 0.2s ease;" onmouseover="this.style.color='#4aa8ff'" onmouseout="this.style.color='inherit'">Cowboy Portraits</a> | Color`,
};
