import React, { useEffect, useMemo, useState } from "react";
import PanZoomStageEditor from "./PanZoomStageEditor.jsx";

export default function VideoBakerEditor() {
  /* ---------------------------------------------------------
     1️⃣ Discover all show files in /src/data/Other/Stories
  --------------------------------------------------------- */
  const modules = useMemo(() => {
    return import.meta.glob("/src/data/Other/Stories/*.mjs", {
      eager: false,
    });
  }, []);

  const options = useMemo(() => {
    return Object.keys(modules)
      .sort((a, b) => a.localeCompare(b))
      .map((path) => {
        const name = path.split("/").pop().replace(".mjs", "");
        const label = name
          .replace(/-/g, " ")
          .replace(/\b\w/g, (m) => m.toUpperCase());
        return { path, label };
      });
  }, [modules]);

  /* ---------------------------------------------------------
     2️⃣ Core states
  --------------------------------------------------------- */
  const [selectedPath, setSelectedPath] = useState("");
  const [storyMeta, setStoryMeta] = useState(null);
  const [slides, setSlides] = useState([]);
  const [editingSlide, setEditingSlide] = useState(null);
  const [status, setStatus] = useState("");

  /* ---------------------------------------------------------
     3️⃣ Load the chosen show file dynamically
  --------------------------------------------------------- */
  useEffect(() => {
    if (!selectedPath) return;
    let cancelled = false;

    async function loadShow() {
      setStatus("Loading…");
      try {
        const mod = await modules[selectedPath]();
        // Flexible export handling
        const meta =
          mod.storyMeta || mod.default || mod.showMeta || mod.story || null;

        if (!meta) {
          console.warn("⚠️ No recognizable export in", selectedPath, mod);
          setStatus("⚠️ No data found in file");
          return;
        }

        const slidesArr = Array.isArray(meta.slides)
          ? meta.slides
          : Array.isArray(meta.story)
          ? meta.story
          : [];

        if (cancelled) return;

        setStoryMeta(meta);
        setSlides(slidesArr);
        setStatus(`Loaded ${slidesArr.length} slides`);
        console.log("✅ Loaded show:", selectedPath, meta);
      } catch (err) {
        console.error("❌ Failed to load show:", err);
        if (!cancelled) setStatus("Failed to load file");
      }
    }

    loadShow();
    return () => {
      cancelled = true;
    };
  }, [selectedPath]);

  /* ---------------------------------------------------------
     4️⃣ Save helper
  --------------------------------------------------------- */
  function saveAsMjs() {
    if (!storyMeta) return;
    const updated = { ...storyMeta, slides };
    const blob = new Blob(
      [
        "// Auto-generated by VideoBaker\nexport const storyMeta = ",
        JSON.stringify(updated, null, 2),
        ";\n",
      ],
      { type: "text/plain" }
    );
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const filename =
      selectedPath.split("/").pop().replace(/\.mjs$/, "-baked.mjs");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    setStatus(`Saved → ${filename}`);
  }

  /* ---------------------------------------------------------
     5️⃣ Render
  --------------------------------------------------------- */
  return (
    <div
      className="p-6 max-w-6xl mx-auto text-sm"
      style={{ fontFamily: "'Glegoo', serif" }}
    >
      <h2 className="text-2xl font-semibold mb-3">K4 Video Baker</h2>

      <div className="flex flex-wrap items-center gap-3 mb-4">
        <select
          className="border rounded-md px-2 py-1 min-w-[22rem]"
          value={selectedPath}
          onChange={(e) => setSelectedPath(e.target.value)}
        >
          <option value="">Select a show file…</option>
          {options.map((o) => (
            <option key={o.path} value={o.path}>
              {o.label}
            </option>
          ))}
        </select>

        <button
          onClick={saveAsMjs}
          className="px-3 py-1 rounded-md border bg-white hover:bg-gray-50"
        >
          Save .mjs
        </button>

        {status && <span className="ml-auto text-xs opacity-70">{status}</span>}
      </div>

      {!selectedPath && (
        <p className="opacity-70">Select a show file to begin editing.</p>
      )}

      {slides.length > 0 && (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill,minmax(220px,1fr))",
            gap: "1rem",
          }}
        >
          {slides.map((s, i) => {
            const img =
              s.srcXL || s.srcL || s.srcM || s.src || s.url || s.imageUrl || "";
            return (
              <div
                key={s.id || i}
                className="border rounded-lg overflow-hidden bg-white shadow-sm"
              >
                {img ? (
                  <img src={img} alt="" className="w-full h-40 object-cover" />
                ) : (
                  <div className="grid place-items-center h-40 bg-gray-100 text-xs text-gray-500">
                    No image
                  </div>
                )}
                <div className="p-2">
                  <div className="font-medium text-sm truncate">
                    {s.title || s.id || "Untitled"}
                  </div>
                  <button
                    onClick={() => setEditingSlide(s)}
                    className="px-3 py-1 mt-2 text-xs border rounded-md bg-blue-50 hover:bg-blue-100"
                  >
                    Edit Pan/Zoom
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {editingSlide && (
        <PanZoomStageEditor
          slide={editingSlide}
          onSave={(data) => {
            setSlides((prev) =>
              prev.map((s) =>
                s.id === editingSlide.id
                  ? { ...s, panZoom: { ...s.panZoom, ...data } }
                  : s
              )
            );
            setEditingSlide(null);
          }}
          onCancel={() => setEditingSlide(null)}
        />
      )}
    </div>
  );
}
