// src/components/GalleryEditorPro.jsx
import { useEffect, useMemo, useRef, useState } from "react";
import PricingEditorModal from "./PricingEditorModal.jsx";

/* ---------- config: add more roots here if needed ---------- */
const DATA_ROOTS = [
  "/src/data/Galleries",
  "/src/pages/Other",
  "/src/data/Other",
];

/* ---------- helpers ---------- */
function escapeForTemplate(str = "") {
  let s = String(str).replace(/\r\n/g, "\n");
  s = s.replace(/`/g, "\\`");
  s = s.replace(/\$\{/g, "\\${");
  return s;
}

function buildMjs(galleryData, exportName = "galleryData") {
  const body = galleryData
    .map((it) => {
      const out = [];
      const pushStr = (k, v) => out.push(`    ${k}: String.raw\`${escapeForTemplate(v)}\`,`);
      const pushVal = (k, v) => out.push(`    ${k}: ${v},`);

      if (it.id != null) pushStr("id", it.id);
      if (it.title != null) pushStr("title", it.title);
      if (it.alt != null) pushStr("alt", it.alt);
      if (it.description != null) pushStr("description", it.description);
      if (it.story != null) pushStr("story", it.story);
      if (it.collectorNotes != null) pushStr("collectorNotes", it.collectorNotes);
      if (it.notes != null) pushStr("notes", it.notes);
      if (it.url != null) pushStr("url", it.url);
      if (it.src != null) pushStr("src", it.src);
      if (it.srcXL != null) pushStr("srcXL", it.srcXL);
      if (it.srcL != null) pushStr("srcL", it.srcL);
      if (it.srcM != null) pushStr("srcM", it.srcM);
      if (it.srcS != null) pushStr("srcS", it.srcS);
      if (it.srcOriginal != null) pushStr("srcOriginal", it.srcOriginal);
      if (it.section != null) pushStr("section", it.section);
      if (typeof it.rating === "number") pushVal("rating", it.rating);
      if (Array.isArray(it.tags)) out.push(`    tags: ${JSON.stringify(it.tags)},`);
      if (Array.isArray(it.keywords)) out.push(`    keywords: ${JSON.stringify(it.keywords)},`);
      if (Array.isArray(it.galleries)) out.push(`    galleries: ${JSON.stringify(it.galleries)},`);
      if (it.visibility != null) pushStr("visibility", it.visibility);
      if (typeof it.sortOrder === "number") pushVal("sortOrder", it.sortOrder);
      if (it.buyLink != null) pushStr("buyLink", it.buyLink);
      if (it.contentSource != null) pushStr("contentSource", it.contentSource);
      if (it.themes && typeof it.themes === "object") out.push(`    themes: ${JSON.stringify(it.themes)},`);
      return `  {\n${out.join("\n")}\n  }`;
    })
    .join(",\n");

  return `// Auto-generated by GalleryEditorPro – review & commit
export const ${exportName} = [
${body}
];
`;
}

function downloadText(text, filename) {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function pickImage(d = {}) {
  return (
    d.url || d.srcXL || d.srcL || d.srcM || d.srcS || d.src || d.imageUrl || d.cover || d.hero?.src || d.preview?.src ||
    d.images?.[0]?.url || d.images?.[0]?.src || ""
  );
}
function isRealItem(d) { return d && d.id !== "i-k4studios"; }

/* --- Quick Refresh helpers (simple) --- */
const RESUME_KEY = "k4-editor:resume";
function writeResumeState({ selectedPath, idx, filter, backupMade, realBackupMade, turboMode }) {
  try {
    localStorage.setItem(
      RESUME_KEY,
      JSON.stringify({ selectedPath, idx, filter, backupMade, realBackupMade, turboMode, ts: Date.now() })
    );
  } catch {}
}
function readResumeState() {
  try {
    const raw = localStorage.getItem(RESUME_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch { return null; }
}

/* Clear the per-dataset draft so Editor Pro won’t restore stale order */
function clearDraftForCurrent(keyFn) {
  try { localStorage.removeItem(keyFn("draft")); } catch {}
}

/* ---------- path & label helpers ---------- */
function normalizePath(p = "") { return p.replace(/\\/g, "/"); }
function stripRoot(p) {
  const n = normalizePath(p);
  for (const root of DATA_ROOTS) {
    const r = normalizePath(root) + "/";
    if (n.startsWith(r)) return n.slice(r.length);
  }
  return n.startsWith("/") ? n.slice(1) : n;
}
function prettyLabelFromPath(fullPath) {
  const rel = stripRoot(fullPath).replace(/\.mjs$/i, "");
  const segs = rel.split("/").map((s) =>
    s.replace(/-/g, " ").replace(/\b\w/g, (m) => m.toUpperCase())
  );
  const rootHint =
    DATA_ROOTS.find((r) => normalizePath(fullPath).startsWith(normalizePath(r) + "/")) || "";
  const rootName = rootHint.split("/").pop();
  return `[${rootName}] ${segs.join(" / ")}`;
}

/* ---------- UI helpers ---------- */
const btnBase = "px-3 py-1 rounded-md border inline-flex items-center transition-colors duration-150";
const btnHover = "hover:opacity-90";
const btnGray = "bg-gray-100 border-gray-300 text-gray-800";
const btnTan = "bg-amber-100 border-amber-300 text-amber-900";
const btnOrange = "bg-orange-100 border-orange-300 text-orange-900";
const btnBlue = "bg-blue-300 border-blue-700 text-black";

/* ---------- Series Definitions ---------- */
// Note: Engrained has its own system, not managed here
const SERIES_DEFINITIONS = {
  sketch: { label: "Sketch", limit: null, description: "Open edition, 5×7 only" },
  foundation: { label: "Foundation", limit: null, description: "Open edition, larger formats" },
  chronicle: { label: "Chronicle", limit: 250, description: "Limited edition of 250" },
  legend: { label: "Legend", limit: 12, description: "Limited edition of 12" },
};

/* ---------- Series Resolution Logic ---------- */
function getEffectiveSeries(image) {
  const series = image?.availableSeries ? [...image.availableSeries] : [];
  // Sketch is ALWAYS included unless explicitly suppressed
  if (!image?.noSketch && !series.includes("sketch")) {
    series.unshift("sketch");
  }
  return series;
}

/* ---------- Edition Counter (local-only updates + explicit save) ---------- */
function EditionCounter({ seriesKey, limit, value, serverValue, disabled, onChange, onSave, hasPendingChange }) {
  const [adjustMode, setAdjustMode] = useState(false);
  const displayValue = value ?? 0; // 0 = none sold yet
  
  function increment() {
    if (displayValue >= limit) return;
    onChange(displayValue + 1);
  }

  function handleAdjust(newVal) {
    const clamped = Math.max(0, Math.min(limit, newVal));
    onChange(clamped);
  }
  
  return (
    <div className="flex items-center gap-1 text-sm">
      {adjustMode ? (
        <>
          <input
            type="number"
            min="0"
            max={limit}
            value={displayValue}
            onChange={(e) => handleAdjust(parseInt(e.target.value, 10) || 0)}
            onBlur={() => setAdjustMode(false)}
            onKeyDown={(e) => { if (e.key === "Enter" || e.key === "Escape") setAdjustMode(false); }}
            disabled={disabled}
            autoFocus
            className="w-14 px-2 py-1 border-2 border-amber-400 rounded text-center text-sm bg-amber-50"
          />
        </>
      ) : (
        <>
          <span className={`w-10 text-center font-medium ${hasPendingChange ? "text-amber-600" : ""}`}>
            {displayValue}
          </span>
          <button
            onClick={increment}
            disabled={disabled || displayValue >= limit}
            className="px-1.5 py-0.5 border rounded text-xs hover:bg-gray-100 disabled:opacity-40 disabled:cursor-not-allowed"
            title="Increment (local only)"
          >▲</button>
        </>
      )}
      <span className="text-gray-500">of {limit} Sold</span>
      {serverValue > 0 && <span className="text-xs text-red-600 ml-1">🔒</span>}
      {!adjustMode && (
        <button
          onClick={() => setAdjustMode(true)}
          disabled={disabled}
          className="text-xs text-amber-600 hover:text-amber-800 ml-1"
          title="Adjust sold count"
        >✎</button>
      )}
      {/* Save button - only shows when there's a pending change */}
      {hasPendingChange && (
        <button
          onClick={onSave}
          disabled={disabled}
          className="px-2 py-0.5 bg-green-600 text-white rounded text-xs hover:bg-green-700 disabled:opacity-40 ml-1"
          title="Save edition count to server"
        >💾</button>
      )}
    </div>
  );
}

/* ---------- Series & Status Panel ---------- */
function SeriesStatusPanel({ current, backupMade, onUpdate, onSave, onOpenPricing }) {
  const [editionStates, setEditionStates] = useState({});
  const [pendingEditions, setPendingEditions] = useState({}); // Local pending changes
  const [loading, setLoading] = useState(false);

  // Fetch edition states from separate database when current image changes
  useEffect(() => {
    if (!current?.id) return;
    fetchEditionState(current.id);
    setPendingEditions({}); // Clear pending when switching images
  }, [current?.id]);

  async function fetchEditionState(imageId) {
    try {
      // Add cache-buster to prevent stale data
      const cacheBuster = Date.now();
      const res = await fetch(`/.netlify/functions/editionState?imageId=${imageId}&_t=${cacheBuster}`, {
        cache: "no-store",
        headers: { "Cache-Control": "no-cache" }
      });
      if (res.ok) {
        const data = await res.json();
        const states = data.states || {};
        setEditionStates(states);
      }
    } catch (err) {
      console.error("[SeriesStatusPanel] Error fetching edition state:", err);
    }
  }

  // Update pending edition locally (no server call)
  function updatePendingEdition(seriesKey, newCount) {
    setPendingEditions(prev => ({ ...prev, [seriesKey]: newCount }));
  }

  // Save a specific series edition to server
  async function saveEdition(seriesKey) {
    if (!current?.id) return;
    const newCount = pendingEditions[seriesKey];
    if (newCount === undefined) return;
    
    setLoading(true);
    try {
      // Ensure edition exists first
      const existing = editionStates[seriesKey];
      if (!existing) {
        await fetch("/.netlify/functions/editionState", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            imageId: current.id,
            series: seriesKey,
            action: "create"
          })
        });
      }
      
      const res = await fetch("/.netlify/functions/editionState", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          imageId: current.id,
          series: seriesKey,
          action: "setSold",
          data: { sold: newCount }
        })
      });
      if (res.ok) {
        const result = await res.json();
        // Update local state immediately with the confirmed value
        if (result.state) {
          setEditionStates(prev => ({
            ...prev,
            [seriesKey]: result.state
          }));
        }
        // Clear this pending change
        setPendingEditions(prev => {
          const copy = { ...prev };
          delete copy[seriesKey];
          return copy;
        });
      }
    } catch (err) {
      console.error("[SeriesStatusPanel] Error saving edition:", err);
    }
    setLoading(false);
  }

  // Create/release a series edition
  async function releaseSeries(seriesKey, limit) {
    if (!current?.id) return;
    setLoading(true);
    try {
      const res = await fetch("/.netlify/functions/editionState", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          imageId: current.id,
          series: seriesKey,
          action: "create"
        })
      });
      if (res.ok) {
        await fetchEditionState(current.id);
      }
    } catch (err) {
      console.error("[SeriesStatusPanel] Error releasing series:", err);
    }
    setLoading(false);
  }

  const effectiveSeries = getEffectiveSeries(current);
  const currentStatus = current?.status || "active";
  const isRetired = currentStatus === "retired";
  
  // Calculate lock info from server state
  // Value represents number sold (not next edition)
  // Exclude engrained - it has its own system
  let totalActuallySold = 0;
  for (const [seriesKey, info] of Object.entries(editionStates)) {
    if (seriesKey === "engrained") continue; // Engrained managed separately
    totalActuallySold += info.sold || 0;
  }
  const isLocked = totalActuallySold > 0;
  const canRemove = !isLocked && currentStatus !== "retired";
  const canRetire = !isRetired;

  // Check if a specific series has sales (locked) - based on SERVER state
  // Value represents number sold (not next edition)
  // sold > 0 = at least 1 sold = locked
  function isSeriesLocked(seriesKey) {
    const soldCount = editionStates[seriesKey]?.sold || 0;
    return soldCount > 0;
  }

  // Toggle series membership
  function toggleSeries(seriesKey) {
    if (!backupMade || isRetired) return;
    if (isSeriesLocked(seriesKey)) return;

    if (seriesKey === "sketch") {
      onUpdate("noSketch", !current.noSketch);
    } else {
      const currentSeries = current.availableSeries || [];
      let newSeries;
      if (currentSeries.includes(seriesKey)) {
        newSeries = currentSeries.filter(s => s !== seriesKey);
      } else {
        newSeries = [...currentSeries, seriesKey];
        // Auto-release edition state when adding a limited series
        const def = SERIES_DEFINITIONS[seriesKey];
        if (def?.limit && !editionStates[seriesKey]) {
          releaseSeries(seriesKey, def.limit);
        }
      }
      onUpdate("availableSeries", newSeries.length > 0 ? newSeries : undefined);
    }
  }

  // Change status
  function changeStatus(newStatus) {
    if (!backupMade) return;
    if (newStatus === "removed" && isLocked) return;
    if (isRetired) return;
    
    if (newStatus === "retired") {
      const ok = confirm(
        "⚠️ RETIREMENT IS PERMANENT\n\n" +
        "Once retired, this image:\n" +
        "• Cannot re-enter any series\n" +
        "• Cannot have new editions released\n" +
        "• Cannot be changed back to active\n\n" +
        "Are you sure you want to retire this image?"
      );
      if (!ok) return;
    }
    
    if (newStatus === "removed") {
      const ok = confirm(
        "⚠️ REMOVAL CONFIRMATION\n\n" +
        "This will remove the image from the public archive.\n\n" +
        "I confirm no editions have ever been sold.\n\n" +
        "Proceed with removal?"
      );
      if (!ok) return;
    }
    
    onUpdate("status", newStatus);
  }

  if (!current) return null;

  return (
    <div className="mt-4 p-4 border-2 border-amber-200 rounded-lg bg-amber-50">
      <h4 className="text-sm font-bold text-amber-800 mb-3 flex items-center gap-2">
        📊 Series & Status
        {isLocked && (
          <span className="text-xs bg-red-100 text-red-700 px-2 py-0.5 rounded">
            🔒 {totalActuallySold} sold — some options locked
          </span>
        )}
        {isRetired && (
          <span className="text-xs bg-gray-200 text-gray-700 px-2 py-0.5 rounded">
            ⏸️ Retired — editing disabled
          </span>
        )}
        <button
          onClick={onOpenPricing}
          className="ml-auto text-xs bg-slate-100 hover:bg-slate-200 text-slate-600 px-2 py-0.5 rounded border border-slate-300"
          title="Edit series pricing and descriptions"
        >
          💰 Edit Pricing
        </button>
      </h4>

      {/* Series Checkboxes */}
      <div className="mb-4">
        <label className="block text-xs opacity-70 mb-2">Series Participation</label>
        <div className="flex flex-col gap-2">
          {Object.entries(SERIES_DEFINITIONS).map(([key, def]) => {
            const isActive = effectiveSeries.includes(key);
            const locked = isSeriesLocked(key);
            const disabled = !backupMade || isRetired || (locked && isActive);
            const soldCount = editionStates[key]?.sold || 0;
            const hasLimit = def.limit !== null;
            
            return (
              <div key={key} className="flex items-center gap-3">
                {/* Checkbox */}
                <label
                  className={`flex items-center gap-2 px-3 py-1.5 rounded border cursor-pointer transition-all min-w-[140px] ${
                    isActive
                      ? locked
                        ? "bg-red-50 border-red-300 text-red-800"
                        : "bg-green-50 border-green-300 text-green-800"
                      : "bg-white border-gray-300 text-gray-600"
                  } ${disabled ? "opacity-60 cursor-not-allowed" : "hover:border-amber-400"}`}
                  title={locked ? `${soldCount} sold — cannot remove` : def.description}
                >
                  <input
                    type="checkbox"
                    checked={isActive}
                    disabled={disabled}
                    onChange={() => toggleSeries(key)}
                    className="sr-only"
                  />
                  <span className="text-sm font-medium">{def.label}</span>
                  {isActive && locked && <span className="text-xs">🔒</span>}
                </label>
                
                {/* Edition Counter (only for limited series when active) */}
                {hasLimit && isActive && (
                  <EditionCounter
                    seriesKey={key}
                    limit={def.limit}
                    value={pendingEditions[key] !== undefined ? pendingEditions[key] : (soldCount ?? 0)}
                    serverValue={soldCount ?? 0}
                    disabled={!backupMade || isRetired || loading}
                    onChange={(newVal) => updatePendingEdition(key, newVal)}
                    onSave={() => saveEdition(key)}
                    hasPendingChange={pendingEditions[key] !== undefined && pendingEditions[key] !== (soldCount ?? 0)}
                  />
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Status Dropdown */}
      <div>
        <label className="block text-xs opacity-70 mb-2">Archive Status</label>
        <div className="flex items-center gap-3">
          <select
            value={currentStatus}
            onChange={(e) => changeStatus(e.target.value)}
            disabled={!backupMade || isRetired}
            className={`px-3 py-1.5 rounded border text-sm ${
              currentStatus === "active" ? "bg-green-50 border-green-300" :
              currentStatus === "retired" ? "bg-gray-100 border-gray-300" :
              "bg-red-50 border-red-300"
            } ${isRetired ? "cursor-not-allowed opacity-60" : ""}`}
          >
            <option value="active">✅ Active — part of living archive</option>
            <option value="retired" disabled={!canRetire}>⏸️ Retired — visible but closed to sales</option>
            <option value="removed" disabled={!canRemove}>🗑️ Removed — erased from archive</option>
          </select>
          
          {loading && <span className="text-xs text-gray-500">Saving...</span>}
        </div>
        
        {!canRemove && currentStatus === "active" && (
          <p className="text-xs text-red-600 mt-1">
            ⚠️ This image has sales and cannot be removed.
          </p>
        )}
      </div>
    </div>
  );
}

/* ---------- Star Rating (1–5) ---------- */
function StarRating({ value = 0, onChange }) {
  const v = Math.max(0, Math.min(5, Math.round(Number(value) || 0)));
  const set = (n) => onChange && onChange(n);
  const stars = [1,2,3,4,5];
  return (
    <div className="flex items-center gap-1" role="radiogroup" aria-label="Rating">
      {stars.map((n) => {
        const active = n <= v;
        return (
          <button
            key={n}
            type="button"
            role="radio"
            aria-checked={active}
            onClick={() => set(n)}
            onKeyDown={(e) => {
              if (e.key === "ArrowRight" || e.key === "ArrowUp") set(Math.min(5, v + 1));
              if (e.key === "ArrowLeft" || e.key === "ArrowDown") set(Math.max(1, v - 1));
            }}
            className={`text-xl leading-none ${active ? "text-amber-500" : "text-gray-300"} focus:outline-none focus:ring-2 focus:ring-amber-400 rounded`}
            title={`${n} star${n>1?"s":""}`}
          >
            {active ? "★" : "☆"}
          </button>
        );
      })}
      <span className="ml-2 text-xs opacity-60">{v ? `${v}/5` : "Unrated"}</span>
    </div>
  );
}

/* ---------- component ---------- */
export default function GalleryEditorPro() {
  const modules = useMemo(() => {
    const maps = [
      import.meta.glob("/src/data/Galleries/**/*.mjs", { eager: false, import: "galleryData" }),
      import.meta.glob("/src/pages/Other/**/*.mjs",     { eager: false, import: "galleryData" }),
      import.meta.glob("/src/data/Other/**/*.mjs",      { eager: false, import: "galleryData" }),
    ];
    return Object.assign({}, ...maps);
  }, []);

  const options = useMemo(() => {
    const rootIdx = (p) => {
      const n = normalizePath(p);
      return DATA_ROOTS.findIndex((r) => n.startsWith(normalizePath(r) + "/"));
    };
    return Object.keys(modules)
      .sort((a, b) => {
        const ra = rootIdx(a), rb = rootIdx(b);
        if (ra !== rb) return ra - rb; // group by root order
        return stripRoot(a).localeCompare(stripRoot(b));
      })
      .map((path) => ({ path, label: prettyLabelFromPath(path) }));
  }, [modules]);

  // Try to restore state from resume storage (survives HMR)
  const resumeState = useMemo(() => {
    if (typeof window === "undefined") return null;
    return readResumeState();
  }, []);

  const [selectedPath, setSelectedPath] = useState(() => {
    // Initialize with sessionStorage if available (client-side only)
    if (typeof window === "undefined") return "";
    return resumeState?.selectedPath || sessionStorage.getItem("lastDatasetPath") || "";
  });
  const [data, setData] = useState([]);
  const [backupData, setBackupData] = useState(null);
  const [idx, setIdx] = useState(() => resumeState?.idx ?? 0);
  const [filter, setFilter] = useState(() => resumeState?.filter ?? "");
  const [dirty, setDirty] = useState(false);
  const [backupMade, setBackupMade] = useState(() => resumeState?.backupMade ?? false);
  const [lastAction, setLastAction] = useState(null);

  const [showRefreshGuard, setShowRefreshGuard] = useState(false);
  const [resumeApplied, setResumeApplied] = useState(false);

  // Turbo Mode state
  const [turboMode, setTurboMode] = useState(() => resumeState?.turboMode ?? false);
  const [turboText, setTurboText] = useState("");
  const [turboApplied, setTurboApplied] = useState(false);
  const [realBackupMade, setRealBackupMade] = useState(() => resumeState?.realBackupMade ?? false);
  const [lastTurboIdx, setLastTurboIdx] = useState(-1); // Track last idx for turbo text updates
  const turboTextareaRef = useRef(null); // Ref for turbo mode textarea

  // Pricing Modal state
  const [pricingModalOpen, setPricingModalOpen] = useState(false);

  useEffect(() => {
    if (!lastAction) return;
    const t = setTimeout(() => setLastAction(null), 6000);
    return () => clearTimeout(t);
  }, [lastAction]);

  const keyLS = (suffix) => `k4-editor:${selectedPath}:${suffix}`;

  // local draft writer (used by programmatic changes)
  function writeDraft(arr) {
    try { localStorage.setItem(keyLS("draft"), JSON.stringify(arr)); } catch {}
  }

  useEffect(() => {
    if (resumeApplied || !options.length) return;
    const resume = readResumeState();
    if (resume && options.some((o) => o.path === resume.selectedPath)) {
      setSelectedPath(resume.selectedPath);
    }
    setResumeApplied(true);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [options.length, resumeApplied]);

  // Initialize with first option if no sessionStorage value
  useEffect(() => {
    if (!options.length || selectedPath) return;
    setSelectedPath(options[0]?.path || "");
  }, [options, selectedPath]);

  // Load dataset when changed
  useEffect(() => {
    let cancelled = false;
    async function load() {
      if (!selectedPath) return;
      
      // Read resume state BEFORE clearing it
      const resume = readResumeState();
      const isResumingSamePath = resume && resume.selectedPath === selectedPath && (Date.now() - resume.ts) < 30000;
      
      // Now clear stale draft (but not resume key yet - we'll clear it after using)
      try {
        localStorage.removeItem(keyLS("draft"));
      } catch {}
      
      const mod = await modules[selectedPath]();
      // Support both shapes: import option may return the value or module object
      const allArr = Array.isArray(mod)
        ? mod
        : Array.isArray(mod?.galleryData)
        ? mod.galleryData
        : Array.isArray(mod?.default)
        ? mod.default
        : [];
      const arr = allArr.filter(isRealItem);
      if (cancelled) return;

      setData(arr);
      setBackupData(allArr);
      
      if (isResumingSamePath) {
        // Restore state from resume - don't reset everything
        setIdx(Math.min(resume.idx ?? 0, arr.length - 1));
        setFilter(resume.filter ?? "");
        setBackupMade(resume.backupMade ?? false);
        setRealBackupMade(resume.realBackupMade ?? false);
        setTurboMode(resume.turboMode ?? false);
        setDirty(false);
        setLastAction("Restored after save");
        setShowRefreshGuard(false);
        // Clear resume state after successfully restoring
        try { localStorage.removeItem(RESUME_KEY); } catch {}
      } else {
        // Fresh load - reset everything
        setIdx(0);
        setFilter("");
        setBackupMade(false);
        setRealBackupMade(false);
        setDirty(false);
        setLastAction(null);
        setShowRefreshGuard(false);
        setTurboMode(false);
        // Clear any stale resume state
        try { localStorage.removeItem(RESUME_KEY); } catch {}
      }
    }
    load();
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedPath]);

  // Autosave draft
  useEffect(() => {
    if (!selectedPath || !data) return;
    try { localStorage.setItem(keyLS("draft"), JSON.stringify(data)); } catch {}
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data]);

  // Persist selected dataset to sessionStorage for cross-app continuity
  useEffect(() => {
    if (selectedPath && typeof window !== "undefined") {
      sessionStorage.setItem("lastDatasetPath", selectedPath);
    }
  }, [selectedPath]);

  const filtered = useMemo(() => {
    const base = data;
    if (!filter.trim()) return base;
    const q = filter.toLowerCase();
    return base.filter((d) =>
      [d.id, d.title, d.alt, d.description, d.story, d.collectorNotes ?? d.notes, (d.tags || d.keywords || []).join(", ")]
        .filter(Boolean)
        .some((v) => String(v).toLowerCase().includes(q))
    );
  }, [data, filter]);

  useEffect(() => {
    if (!filtered.length) return;
    const curId = filtered[idx]?.id;
    if (!curId) { setIdx(0); return; }
    const newPos = filtered.findIndex((d) => d.id === curId);
    if (newPos === -1) setIdx(0);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filter]);

  const current = filtered[idx] || null;

  function ensureBackup() {
    if (!backupData) return;
    const ts = new Date().toISOString().replace(/[:.]/g, "-");
    // Extract gallery name from path (e.g., "Color" from ".../Western-Cowboy-Portraits/Color.mjs")
    const pathParts = selectedPath.split("/").filter(Boolean);
    const fileName = pathParts.pop()?.replace(".mjs", "") || "gallery";
    const parentFolder = pathParts.pop() || "";
    const galleryLabel = parentFolder ? `${parentFolder}-${fileName}`.substring(0, 40) : fileName.substring(0, 40);
    downloadText(buildMjs(backupData, "galleryData"), `BACKUP-${galleryLabel}-${ts}.mjs`);
    setBackupMade(true);
    setRealBackupMade(true);
    setLastAction(`Backup created — ${new Date().toLocaleTimeString()}`);
  }
  function skipBackupConfirm() {
    const ok = confirm(
      "Skip creating a safety backup for this session?\n\n" +
      "This will unlock editing temporarily. You will be prompted again next time you load this dataset.\n\n" +
      "Click OK to proceed without a backup."
    );
    if (!ok) return;
    setBackupMade(true);
    setLastAction("Backup skipped for now — editing unlocked");
  }

  function updateField(field, value) {
    if (!backupMade || !current) return;
    // Text content fields that indicate human authorship when edited
    const textContentFields = ["title", "alt", "description", "story", "collectorNotes", "notes", "keywords"];
    const isTextContent = textContentFields.includes(field);
    
    setData((arr) => {
      const i = arr.findIndex((d) => d.id === current.id);
      if (i === -1) return arr;
      const copy = [...arr];
      if (field === "keywords") {
        const tags = String(value).split(",").map((s) => s.trim()).filter(Boolean);
        copy[i] = { ...copy[i], tags, keywords: tags };
      } else if (field === "collectorNotes" || field === "notes") {
        copy[i] = { ...copy[i], collectorNotes: value };
      } else if (field === "rating") {
        const n = Number(value);
        const clamped = Number.isFinite(n) ? Math.min(5, Math.max(1, Math.round(n))) : copy[i].rating;
        copy[i] = { ...copy[i], rating: clamped };
      } else {
        copy[i] = { ...copy[i], [field]: value };
      }
      // Mark as human-authored if editing text content fields (not in turbo mode)
      if (isTextContent && !turboMode) {
        copy[i] = { ...copy[i], contentSource: "human" };
      }
      return copy;
    });
    setDirty(true);
  }

  function revertCurrentToBackup() {
    if (!backupData || !current) return;
    const orig = backupData.find((d) => d.id === current.id);
    if (!orig) return;
    setData((arr) => {
      const i = arr.findIndex((d) => d.id === current.id);
      if (i === -1) return arr;
      const copy = [...arr];
      const {
        id, title, alt, description, story, collectorNotes, notes, tags, keywords,
        url, src, srcXL, srcL, srcM, srcS, srcOriginal, section, rating, galleries, visibility, sortOrder, buyLink, contentSource
      } = orig;
      copy[i] = {
        id, title, alt, description, story,
        collectorNotes: collectorNotes ?? notes,
        tags, keywords, url, src, srcXL, srcL, srcM, srcS, srcOriginal, section, rating, galleries, visibility, sortOrder, buyLink, contentSource
      };
      return copy;
    });
    setDirty(true);
    setLastAction(`Reverted CURRENT (${current.id}) — ${new Date().toLocaleTimeString()}`);
  }

  function revertAllToBackup() {
    if (!backupData) return;
    if (!confirm("Revert ALL images to the backed-up data?")) return;
    setData(
      backupData.filter(isRealItem).map((orig) => {
        const {
          id, title, alt, description, story, collectorNotes, notes, tags, keywords,
          url, src, srcXL, srcL, srcM, srcS, srcOriginal, section, rating, galleries, visibility, sortOrder, buyLink, contentSource
        } = orig;
        return {
          id, title, alt, description, story,
          collectorNotes: collectorNotes ?? notes,
          tags, keywords, url, src, srcXL, srcL, srcM, srcS, srcOriginal, section, rating, galleries, visibility, sortOrder, buyLink, contentSource
        };
      })
    );
    setDirty(true);
    setLastAction(`Reverted ALL — ${new Date().toLocaleTimeString()}`);
  }

  // ---- TURBO MODE functions ----
  function buildTurboText(item) {
    if (!item) return "";
    const keywords = Array.isArray(item.tags)
      ? item.tags.join(", ")
      : Array.isArray(item.keywords)
      ? item.keywords.join(", ")
      : "";
    const collectorNotes = item.collectorNotes ?? item.notes ?? "";
    
    return `<<TITLE>>
${item.title || ""}

<<STORY>>
${item.story || ""}

<<DESCRIPTION>>
${item.description || ""}

<<ALT>>
${item.alt || ""}

<<KEYWORDS>>
${keywords}

<<COLLECTOR_NOTES>>
${collectorNotes}`;
  }

  function parseTurboText(text) {
    const result = {};
    const sections = {
      TITLE: "title",
      STORY: "story",
      DESCRIPTION: "description",
      ALT: "alt",
      KEYWORDS: "keywords",
      COLLECTOR_NOTES: "collectorNotes"
    };
    
    // Accept formats: <<TAG>>, <TAG>, "1. <TAG>", "1.<TAG>" (with optional numbering)
    // Lookahead also handles numbered next sections like "2. <STORY>"
    const regex = /(?:\d+\.\s*)?<?<(\w+)>>?\s*([\s\S]*?)(?=(?:\d+\.\s*)?<?<\w+>>?|$)/g;
    let match;
    while ((match = regex.exec(text)) !== null) {
      const tag = match[1].toUpperCase();
      // Strip trailing numbered list markers like "\n\n2." or "\n3."
      let content = match[2].trim().replace(/\n+\d+\.?\s*$/, "").trim();
      if (sections[tag]) {
        result[sections[tag]] = content;
      }
    }
    return result;
  }

  function enterTurboMode() {
    if (!current) return;
    
    // If real backup hasn't been made yet, trigger one now
    if (!realBackupMade) {
      if (!backupData) {
        alert("No data to backup yet. Please wait for the gallery to load.");
        return;
      }
      // Trigger the backup
      const ts = new Date().toISOString().replace(/[:.]/g, "-");
      const pathParts = selectedPath.split("/").filter(Boolean);
      const fileName = pathParts.pop()?.replace(".mjs", "") || "gallery";
      const parentFolder = pathParts.pop() || "";
      const galleryLabel = parentFolder ? `${parentFolder}-${fileName}`.substring(0, 40) : fileName.substring(0, 40);
      downloadText(buildMjs(backupData, "galleryData"), `BACKUP-${galleryLabel}-${ts}.mjs`);
      setBackupMade(true);
      setRealBackupMade(true);
      setLastAction(`Backup created for Turbo Mode — ${new Date().toLocaleTimeString()}`);
    }
    
    setTurboText(buildTurboText(current));
    setTurboApplied(false);
    setTurboMode(true);
  }

  function exitTurboMode() {
    setTurboMode(false);
    setTurboText("");
    setTurboApplied(false);
  }

  async function populateFromTurbo() {
    if (!current || !backupMade) return;
    const parsed = parseTurboText(turboText);
    
    // Build the updated item with contentSource: ai
    const updatedItem = { ...current, contentSource: "ai" };
    if (parsed.title !== undefined) updatedItem.title = parsed.title;
    if (parsed.story !== undefined) updatedItem.story = parsed.story;
    if (parsed.description !== undefined) updatedItem.description = parsed.description;
    if (parsed.alt !== undefined) updatedItem.alt = parsed.alt;
    if (parsed.collectorNotes !== undefined) updatedItem.collectorNotes = parsed.collectorNotes;
    if (parsed.keywords !== undefined) {
      const tags = parsed.keywords.split(",").map((s) => s.trim()).filter(Boolean);
      updatedItem.tags = tags;
      updatedItem.keywords = tags;
    }
    
    // Capture the current id before async operations
    const currentId = current.id;
    
    // Update local state
    setData((arr) => {
      const i = arr.findIndex((d) => d.id === currentId);
      if (i === -1) return arr;
      const copy = [...arr];
      copy[i] = updatedItem;
      return copy;
    });
    
    // Save to database
    try {
      const payload = {
        datasetPath: selectedPath.replace(/^\//, ""),
        id: updatedItem.id,
        patch: {
          title: updatedItem.title ?? "",
          alt: updatedItem.alt ?? "",
          description: updatedItem.description ?? "",
          story: updatedItem.story ?? "",
          notes: updatedItem.collectorNotes ?? updatedItem.notes ?? "",
          keywords: Array.isArray(updatedItem.tags)
            ? updatedItem.tags
            : Array.isArray(updatedItem.keywords)
            ? updatedItem.keywords
            : String(updatedItem.tags || updatedItem.keywords || "")
                .split(",")
                .map((s) => s.trim())
                .filter(Boolean),
          rating: typeof updatedItem.rating === "number" ? updatedItem.rating : undefined,
          contentSource: "ai",
        },
      };

      // Save resume state before API call (in case HMR triggers)
      writeResumeState({ selectedPath, idx, filter, backupMade, realBackupMade, turboMode: true });

      const res = await fetch("/.netlify/functions/updateGalleryItem", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error(await res.text());
      
      setDirty(false);
      setTurboApplied(true);
      setLastAction(`Saved ${currentId} — ${new Date().toLocaleTimeString()}`);
    } catch (err) {
      setDirty(true);
      setTurboApplied(true);
      setLastAction(`Populated but save failed: ${err.message}`);
      alert("Populate succeeded but save failed.\n\n" + err.message);
    }
  }

  function turboMove(delta) {
    // Check if there are unsaved changes in turbo mode
    if (current) {
      const originalText = buildTurboText(current);
      if (turboText !== originalText && !turboApplied) {
        const shouldSave = confirm(
          "You have unpopulated changes in the text block.\n\n" +
          "Click OK to save changes before moving.\n" +
          "Click Cancel to go back and review."
        );
        if (!shouldSave) return; // User cancelled, go back to review
        // Save changes before moving
        populateFromTurbo();
      }
    }
    
    move(delta);
    setTurboApplied(false);
    // Will update turboText via effect
  }

  // Update turbo text when navigating to a different image in turbo mode
  useEffect(() => {
    if (turboMode && current && idx !== lastTurboIdx) {
      setTurboText(buildTurboText(current));
      setTurboApplied(false);
      setLastTurboIdx(idx);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [turboMode, idx]);

  function move(delta) {
    const len = filtered.length;
    if (!len) return;
    let n = idx + delta;
    if (n < 0) n = 0;
    if (n > len - 1) n = len - 1;
    setIdx(n);
  }

  function saveAllAsMjs() {
    if (!selectedPath) return;
    const filename = selectedPath.split("/").pop() || "gallery.mjs";
    const merged = Array.isArray(backupData)
      ? backupData.map((item) => {
          if (!item || !item.id) return item;
          const edited = data.find((d) => d.id === item.id);
          return edited ? edited : item;
        })
      : data;
    const text = buildMjs(merged, "galleryData");
    downloadText(text, filename);
    setDirty(false);
    setLastAction(`Saved ALL → ${filename} — ${new Date().toLocaleTimeString()}`);
  }

  async function saveCurrentOnly() {
    if (!backupMade || !selectedPath || !backupData || !current) return;
    const payload = {
      datasetPath: selectedPath.replace(/^\//, ""),
      id: current.id,
      patch: {
        title: current.title ?? "",
        alt: current.alt ?? "",
        description: current.description ?? "",
        story: current.story ?? "",
        notes: current.collectorNotes ?? current.notes ?? "",
        keywords: Array.isArray(current.tags)
          ? current.tags
          : Array.isArray(current.keywords)
          ? current.keywords
          : String(current.tags || current.keywords || "")
              .split(",")
              .map((s) => s.trim())
              .filter(Boolean),
        rating: typeof current.rating === "number" ? current.rating : undefined,
        contentSource: current.contentSource ?? undefined,
        srcXL: current.srcXL ?? "",
        srcL: current.srcL ?? "",
        srcM: current.srcM ?? "",
        srcS: current.srcS ?? "",
        srcOriginal: current.srcOriginal ?? "",
        // Series & Status fields (use null to remove, undefined gets stripped by JSON)
        availableSeries: Array.isArray(current.availableSeries) && current.availableSeries.length > 0 ? current.availableSeries : null,
        noSketch: current.noSketch === true ? true : null,
        status: current.status && current.status !== "active" ? current.status : null,
        // NOTE: Edition sold counts are NEVER stored in .mjs files
        // They are stored in editionState.json via the editionState Netlify function
      },
    };

    // Save resume state before API call (in case HMR triggers)
    writeResumeState({ selectedPath, idx, filter, backupMade, realBackupMade, turboMode });

    try {
      const res = await fetch("/.netlify/functions/updateGalleryItem", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error(await res.text());
      setLastAction(`Patched CURRENT (${current.id}) in-place — ${new Date().toLocaleTimeString()}`);
      setDirty(false);
    } catch (err) {
      alert("Save failed. Falling back to file download.\n\n" + err.message);
      const filename = selectedPath.split("/").pop() || "gallery.mjs";
      const edited = data.find((d) => d.id === current.id) || current;
      const merged = backupData.map((item) => (item && item.id === edited.id ? edited : item));
      const text = buildMjs(merged, "galleryData");
      downloadText(text, filename);
      setLastAction(`Saved CURRENT via download → ${filename} — ${new Date().toLocaleTimeString()}`);
    }
  }

  // ---- NEW: Show/Hide toggle ----
  async function toggleVisibility() {
    if (!backupMade || !selectedPath || !current) return;
    const next = current.visibility === "hidden" ? "" : "hidden";

    // optimistic UI: data
    setData((arr) => {
      const i = arr.findIndex((d) => d.id === current.id);
      if (i === -1) return arr;
      const copy = [...arr];
      if (next) copy[i] = { ...copy[i], visibility: next };
      else {
        const { visibility, ...rest } = copy[i];
        copy[i] = rest;
      }
      writeDraft(copy);
      return copy;
    });
    // optimistic UI: full array (backupData)
    setBackupData((full) =>
      Array.isArray(full)
        ? full.map((item) => {
            if (!item || item.id !== current.id) return item;
            if (next) return { ...item, visibility: next };
            const { visibility, ...rest } = item;
            return rest;
          })
        : full
    );

    // persist
    try {
      const res = await fetch("/.netlify/functions/updateGalleryItem", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          datasetPath: selectedPath.replace(/^\//, ""),
          id: current.id,
          patch: { visibility: next, rating: typeof current.rating === "number" ? current.rating : undefined },
        }),
      });
      if (!res.ok) throw new Error(await res.text());
      setLastAction(`Visibility → ${next || "show"} — ${new Date().toLocaleTimeString()}`);
    } catch (err) {
      alert("Visibility update failed.\n\n" + (err?.message || err));
    }
  }

  // ---- NEW: Delete current image FROM THIS gallery ----
  async function deleteCurrentFromGallery() {
    if (!backupMade || !selectedPath || !backupData || !current) return;

    const ok = confirm(
      "WARNING: You are about to remove image data for this image from this database.\n\n" +
      "Continue?\n\nYes = Remove from THIS gallery file only (non-destructive elsewhere).\nNo  = Cancel.\n\n" +
      "Note: this data may also exist in other galleries."
    );
    if (!ok) return;

    try {
      // Build full array: keep ghosts, drop current
      const ghosts = backupData.filter((d) => d && d.id === "i-k4studios");
      const nextUI  = data.filter((d) => d.id !== current.id);
      const finalFull = ghosts.concat(nextUI);

      // persist via order function (it resequences sortOrder)
      const res = await fetch("/.netlify/functions/updateGalleryOrder", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          datasetPath: selectedPath.replace(/^\//, ""),
          fullArray: finalFull,
        }),
      });
      if (!res.ok) throw new Error(await res.text());

      // reflect in UI
      setBackupData(finalFull);
      setData(nextUI);
      writeDraft(nextUI);
      setIdx((i) => Math.max(0, Math.min(i, nextUI.length - 1)));
      setDirty(false);
      setLastAction(`Deleted ${current.id} from this gallery — ${new Date().toLocaleTimeString()}`);
    } catch (err) {
      alert("Delete failed.\n\n" + (err?.message || err));
    }
  }

  // ---- Refresh after external action (reorder/import) ----
  function refreshAfterExternal() {
    writeResumeState({ selectedPath, idx, filter, backupMade });
    clearDraftForCurrent(keyLS);       // prevent stale draft restoring old order
    window.location.reload();
  }

  const datasetParam = encodeURIComponent(selectedPath || "");
  const total = filtered.length;
  const pos = total ? idx + 1 : 0;

  // one flag for button locking
  const itemLocked = !backupMade || !current;

  return (
    <div className="relative p-6 max-w-6xl mx-auto text-sm">
      {/* MAIN UI (gets dimmed/disabled when guard is active) */}
      <div className={showRefreshGuard ? "pointer-events-none select-none opacity-40" : ""} aria-hidden={showRefreshGuard ? "true" : undefined}>
        <h1 className="text-2xl font-semibold mb-3">Gallery Editor Pro</h1>

        {/* Row 1: dataset select + status */}
        <div className="flex flex-wrap items-center gap-3 mb-2">
          <select
            className="border rounded-md px-2 py-1 min-w-[22rem]"
            value={selectedPath}
            onChange={(e) => setSelectedPath(e.target.value)}
          >
            {options.map((o) => (
              <option key={o.path} value={o.path}>{o.label}</option>
            ))}
          </select>

          {backupMade ? (
            <span className="text-green-700">✅ Editing unlocked</span>
          ) : (
            <span className="text-yellow-700">🔒 Editing locked</span>
          )}
        </div>

        {/* Row 2: action row */}
        <div className="flex flex-wrap items-center gap-2 mb-3">
          {!backupMade ? (
            <>
              <button onClick={ensureBackup} className={`${btnBase} ${btnGray} ${btnHover}`} title="Download a safety backup of the current dataset">
                1) Make Data Backup
              </button>
              <button
                onClick={skipBackupConfirm}
                className={`${btnBase} border-red-300 text-red-700 bg-white ${btnHover}`}
                title="Temporarily unlock editing without a backup (not recommended)"
              >
                Skip For Now (temporary)
              </button>
            </>
          ) : null}


          <a
            href={`/admin/GalleryReorderer?dataset=${datasetParam}`}
            target="_blank"
            rel="noopener noreferrer"
            onClick={() => { clearDraftForCurrent(keyLS); setShowRefreshGuard(true); }}
            className={`${btnBase} ${btnHover}`}
            style={{ background: '#e4dae9ff', borderColor: '#836fa5ff', color: '#31233bff' }}
            onMouseEnter={(e) => (e.currentTarget.style.background = '#b4acd4ff')}
            onMouseLeave={(e) => (e.currentTarget.style.background = '#e4dae9ff')}
          >
            Open Reorder
          </a>

          <a
            href={`/admin/GalleryDataSwapper?dataset=${datasetParam}`}
            target="_blank"
            rel="noopener noreferrer"
            className={`${btnBase} ${btnHover}`}
            style={{ background: '#d4e4faff', borderColor: '#6fa5a5ff', color: '#233b31ff' }}
            onMouseEnter={(e) => (e.currentTarget.style.background = '#acd4b4ff')}
            onMouseLeave={(e) => (e.currentTarget.style.background = '#d4e4faff')}
          >
            Open Data Swapper
          </a>

          <a
            href={`/admin/GalleryImporter?to=${datasetParam}`}
            target="_blank"
            rel="noopener noreferrer"
            onClick={() => { clearDraftForCurrent(keyLS); setShowRefreshGuard(true); }}
            className={`${btnBase} ${btnHover}`}
            style={{ background: '#ebc3e2ff', borderColor: '#7693beff', color: '#2b1a29ff' }}
            onMouseEnter={(e) => (e.currentTarget.style.background = '#b996b6ff')}
            onMouseLeave={(e) => (e.currentTarget.style.background = '#ebc3e2ff')}
          >
            Import Images…
          </a>

          <button
            onClick={enterTurboMode}
            disabled={!backupMade}
            className={`${btnBase} ${btnHover} ${!backupMade ? "opacity-50 cursor-not-allowed" : ""}`}
            style={{ background: '#fef3c7', borderColor: '#f59e0b', color: '#92400e' }}
            onMouseEnter={(e) => backupMade && (e.currentTarget.style.background = '#fde68a')}
            onMouseLeave={(e) => (e.currentTarget.style.background = '#fef3c7')}
            title={realBackupMade ? "Enter Turbo Mode for fast AI-assisted data entry" : "Click to create backup and enter Turbo Mode"}
          >
            ⚡ Turbo Mode
          </button>
        </div>

        {/* Row 3: search + nav */}
        <div className="flex flex-wrap items-center gap-2 mb-3">
          <input
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            placeholder="Search id/title/text/keywords…"
            className="w-72 border  rounded-md px-2 py-1"
          />
          <button onClick={() => move(-1)} className={`${btnBase} bg-green-100 ${btnHover}`}>Prev</button>
          <button onClick={() => move(1)} className={`${btnBase} bg-green-300 ${btnHover}`}>Next</button>
          <span className="opacity-70">{pos}/{total} (of {data.length})</span>
        </div>

        {/* editor + actions */}
        <div className="mb-3 flex flex-wrap items-center gap-2">
          {dirty && <span className="text-red-600 font-medium">Unsaved changes</span>}

          {/* Show/Hide */}
          <button
            onClick={toggleVisibility}
            disabled={itemLocked}
            className={`${btnBase} bg-yellow-50 border-yellow-300 text-yellow-800 ${itemLocked ? "opacity-50 cursor-not-allowed" : ""} ${btnHover}`}
            title={current?.visibility === "hidden" ? "Show this image on the site" : "Hide this image from the site"}
          >
            {current?.visibility === "hidden" ? "Show On Site" : "Hide From Site"}
          </button>

          {/* Delete from this gallery */}
          <button
            onClick={deleteCurrentFromGallery}
            disabled={itemLocked}
            className={`${btnBase} bg-red-50 border-red-300 text-red-700 ${itemLocked ? "opacity-50 cursor-not-allowed" : ""} ${btnHover}`}
            title="Remove this image entry from this gallery file (non-destructive elsewhere)"
          >
            Delete Image
          </button>

          {/* Save THIS image (server patch) */}
          <button
            onClick={saveCurrentOnly}
            disabled={itemLocked}
            className={`${btnBase} ${btnBlue} ${itemLocked ? "opacity-50 cursor-not-allowed" : ""} ${btnHover}`}
            title={itemLocked ? "Unlock editing with a backup first" : "Save just this image to the dataset on the server"}
          >
            Save This Image (.mjs)
          </button>

          {/* These remain available */}
          <button onClick={saveAllAsMjs} className={`${btnBase} bg-white ${btnHover}`}>
            Save All (.mjs)
          </button>
          <button onClick={revertCurrentToBackup} className={`${btnBase} bg-white ${btnHover}`}>
            Revert This Image
          </button>
          <button onClick={revertAllToBackup} className={`${btnBase} bg-white ${btnHover}`}>
            Revert All
          </button>

          {lastAction && (
            <span className="ml-auto text-xs bg-green-50 border border-green-200 text-green-800 px-2 py-1 rounded-md">
              {lastAction}
            </span>
          )}
        </div>

        {/* editing locked notice */}
        {!backupMade && (
          <div className="mb-3 p-3 border rounded-md bg-yellow-50">
            Editing is locked until you click <strong>“Make Data Backup”</strong> or <strong>“Skip For Now”</strong> (not recommended). You’ll be asked again next time.
          </div>
        )}

        {/* main form */}
        {current ? (
          <div className={`grid grid-cols-1 md:grid-cols-2 gap-4 ${!backupMade ? "pointer-events-none opacity-60" : ""}`}>
            {/* Left */}
            <div className="space-y-3">
              <div className="mb-1 text-xs uppercase tracking-wide opacity-70">
                Chapter {idx + 1} of {data.length}
              </div>
              {(() => {
                const imgUrl = pickImage(current);
                const hidden = current?.visibility === "hidden";
                const contentSource = current?.contentSource || "human"; // Default to human if not set
                return imgUrl ? (
                  <div className="relative">
                    <img src={imgUrl} alt="" className={`w-full rounded-lg shadow ${hidden ? "opacity-60" : ""}`} />
                    {hidden && (
                      <span className="absolute top-2 left-2 text-xs px-2 py-1 rounded bg-yellow-100 border border-yellow-300 text-yellow-900">
                        Hidden
                      </span>
                    )}
                    {/* Content source indicator - always show */}
                    <span 
                      className={`absolute top-2 right-2 text-xs px-2 py-1 rounded ${
                        contentSource === "ai" 
                          ? "bg-purple-100 border border-purple-300 text-purple-900" 
                          : "bg-blue-100 border border-blue-300 text-blue-900"
                      }`}
                      title={contentSource === "ai" ? "Content written by AI/Turbo Mode" : "Content written by human (or not yet processed)"}
                    >
                      {contentSource === "ai" ? "🤖 AI" : "✍️ Human"}
                    </span>
                  </div>
                ) : (
                  <div className="w-full h-64 grid place-items-center border rounded-lg">No image url</div>
                );
              })()}

              <div>
                <label className="block text-xs opacity-70 mb-1">ID (read-only)</label>
                <input value={current.id || ""} readOnly className="w-full border rounded-md px-2 py-1 bg-gray-50 text-gray-700 cursor-not-allowed" />
              </div>

              <div>
                <label className="block text-xs opacity-70 mb-1">Title</label>
                <input value={current.title || ""} onChange={(e) => updateField("title", e.target.value)} className="w-full border rounded-md px-2 py-1" />
              </div>

              <div>
                <label className="block text-xs opacity-70 mb-1">Alt Text</label>
                <input value={current.alt || ""} onChange={(e) => updateField("alt", e.target.value)} className="w-full border rounded-md px-2 py-1" />
              </div>

              <div>
                <label className="block text-xs opacity-70 mb-1">Rating (1–5)</label>
                <StarRating
                  value={typeof current.rating === "number" ? current.rating : 0}
                  onChange={(n) => updateField("rating", n)}
                />
              </div>

              <div>
                <label className="block text-xs opacity-70 mb-1">Keywords (comma separated)</label>
                <textarea
                  value={
                    Array.isArray(current.tags)
                      ? current.tags.join(", ")
                      : Array.isArray(current.keywords)
                      ? current.keywords.join(", ")
                      : ""
                  }
                  onChange={(e) => updateField("keywords", e.target.value)}
                  className="w-full min-h-[88px] border rounded-md px-2 py-1 resize-y"
                />
              </div>

              <div>
                <label className="block text-xs opacity-70 mb-1">Src</label>
                <input value={current.src || ""} onChange={(e) => updateField("src", e.target.value)} className="w-full border rounded-md px-2 py-1" />
              </div>

              <div>
                <label className="block text-xs opacity-70 mb-1">Src XL</label>
                <input value={current.srcXL || ""} onChange={(e) => updateField("srcXL", e.target.value)} className="w-full border rounded-md px-2 py-1" />
              </div>

              <div>
                <label className="block text-xs opacity-70 mb-1">Src L</label>
                <input value={current.srcL || ""} onChange={(e) => updateField("srcL", e.target.value)} className="w-full border rounded-md px-2 py-1" />
              </div>

              <div>
                <label className="block text-xs opacity-70 mb-1">Src M</label>
                <input value={current.srcM || ""} onChange={(e) => updateField("srcM", e.target.value)} className="w-full border rounded-md px-2 py-1" />
              </div>

              <div>
                <label className="block text-xs opacity-70 mb-1">Src S</label>
                <input value={current.srcS || ""} onChange={(e) => updateField("srcS", e.target.value)} className="w-full border rounded-md px-2 py-1" />
              </div>

              <div>
                <label className="block text-xs opacity-70 mb-1">Src Original</label>
                <input value={current.srcOriginal || ""} onChange={(e) => updateField("srcOriginal", e.target.value)} className="w-full border rounded-md px-2 py-1" />
              </div>
            </div>

            {/* Right */}
            <div className="space-y-3">
              <div>
                <label className="block text-xs opacity-70 mb-1">The Story — For people’s imagination</label>
                <textarea value={current.story || ""} onChange={(e) => updateField("story", e.target.value)} className="w-full h-32 border rounded-md px-2 py-1" />
              </div>

              <div>
                <label className="block text-xs opacity-70 mb-1">Description — Google/SEO Optimized Copy</label>
                <textarea value={current.description || ""} onChange={(e) => updateField("description", e.target.value)} className="w-full h-32 border rounded-md px-2 py-1" />
              </div>

              <div>
                <label className="block text-xs opacity-70 mb-1">Collector Notes — Artistic critique for collector confidence</label>
                <textarea value={current.collectorNotes ?? current.notes ?? ""} onChange={(e) => updateField("collectorNotes", e.target.value)} className="w-full h-28 border rounded-md px-2 py-1" />
              </div>

              {/* Series & Status Panel */}
              <SeriesStatusPanel
                current={current}
                backupMade={backupMade}
                onUpdate={(field, value) => updateField(field, value)}
                onSave={saveCurrentOnly}
                onOpenPricing={() => setPricingModalOpen(true)}
              />
            </div>
          </div>
        ) : (
          <div className="p-10 text-center opacity-70">No items match your filter.</div>
        )}
      </div>

      {/* TURBO MODE full-screen overlay */}
      {turboMode && (
        <div className="fixed inset-0 z-40 bg-gray-900 overflow-auto">
          <div className="min-h-screen p-6">
            {/* Header bar */}
            <div className="flex flex-wrap items-center gap-3 mb-4">
              <h2 className="text-xl font-bold text-amber-400">⚡ Turbo Mode</h2>
              <span className="text-gray-300 text-sm">
                {pos}/{total} — {current?.id || "No item"}
              </span>
              
              <div className="flex-1" />
              
              <button
                onClick={exitTurboMode}
                className={`${btnBase} bg-red-600 border-red-700 text-white ${btnHover}`}
              >
                ✕ Exit Turbo Mode
              </button>
            </div>

            {/* Success message */}
            {turboApplied && (
              <div className="mb-4 p-3 bg-green-800 border border-green-600 rounded-lg flex items-center gap-3">
                <span className="text-green-200 text-lg">✓</span>
                <span className="text-green-100 font-medium">
                  Saved {current?.id} — Ready for next image
                </span>
              </div>
            )}

            {current ? (
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {/* Left: Image */}
                <div className="space-y-3">
                  {(() => {
                    const imgUrl = pickImage(current);
                    const contentSource = current?.contentSource || "human";
                    return imgUrl ? (
                      <div className="relative">
                        <img 
                          src={imgUrl} 
                          alt="" 
                          className="w-full max-h-[80vh] object-contain rounded-lg shadow-lg bg-black" 
                        />
                        <div className="absolute bottom-2 left-2 text-xs px-2 py-1 rounded bg-black/70 text-white">
                          {current.id}
                        </div>
                        {/* Content source indicator in turbo mode */}
                        <span 
                          className={`absolute top-2 right-2 text-xs px-2 py-1 rounded ${
                            contentSource === "ai" 
                              ? "bg-purple-500 border border-purple-400 text-white" 
                              : "bg-blue-500 border border-blue-400 text-white"
                          }`}
                        >
                          {contentSource === "ai" ? "🤖 AI" : "✍️ Human"}
                        </span>
                      </div>
                    ) : (
                      <div className="w-full h-64 grid place-items-center border border-gray-600 rounded-lg text-gray-400">
                        No image url
                      </div>
                    );
                  })()}
                  
                  <div className="text-xs text-gray-400 text-center">
                    Print Screen this view, feed to AI, paste the result back, then click Populate
                  </div>
                  
                  {/* Rating stars */}
                  <div className="mt-3 flex items-center justify-center gap-2 p-2 bg-gray-800 rounded-lg">
                    <span className="text-gray-400 text-sm">Rating:</span>
                    <StarRating
                      value={typeof current.rating === "number" ? current.rating : 0}
                      onChange={(n) => updateField("rating", n)}
                    />
                  </div>
                  
                  {/* Nav buttons below image */}
                  <div className="mt-3 flex items-center justify-center gap-3">
                    <button
                      onClick={() => turboMove(-1)}
                      disabled={idx === 0}
                      className={`${btnBase} px-6 py-2 ${idx === 0 ? 'bg-gray-600 border-gray-700 text-gray-400 cursor-not-allowed' : `bg-green-600 border-green-700 text-white ${btnHover}`}`}
                    >
                      ◀ Prev
                    </button>
                    <button
                      onClick={() => turboMove(1)}
                      disabled={idx >= filtered.length - 1}
                      className={`${btnBase} px-6 py-2 ${idx >= filtered.length - 1 ? 'bg-gray-600 border-gray-700 text-gray-400 cursor-not-allowed' : `bg-green-500 border-green-600 text-white ${btnHover}`}`}
                    >
                      Next ▶
                    </button>
                  </div>
                </div>

                {/* Right: Text block + actions */}
                <div className="flex flex-col h-full">
                  <div className="flex items-center gap-2 mb-2">
                    <label className="text-sm text-gray-300 font-medium">Data Block</label>
                  </div>
                  
                  <textarea
                    ref={turboTextareaRef}
                    value={turboText}
                    onChange={(e) => { setTurboText(e.target.value); setTurboApplied(false); }}
                    className="flex-1 w-full min-h-[70vh] border border-gray-600 rounded-lg px-3 py-2 bg-gray-800 text-gray-100 font-mono text-sm resize-none focus:outline-none focus:ring-2 focus:ring-amber-400"
                    placeholder="Paste AI-generated content here in the <<TAG>> format..."
                    spellCheck={false}
                  />
                  
                  <div className="mt-3 flex flex-wrap items-center gap-2">
                    <button
                      onClick={() => setTurboText(buildTurboText(current))}
                      className={`${btnBase} bg-gray-700 border-gray-600 text-gray-200 ${btnHover}`}
                      title="Reset text to current saved data"
                    >
                      Reset Text
                    </button>
                    <button
                      onClick={() => { setTurboText(""); turboTextareaRef.current?.focus(); }}
                      className={`${btnBase} bg-gray-600 border-gray-500 text-gray-200 ${btnHover}`}
                      title="Clear all text for easy pasting"
                    >
                      Clear Text
                    </button>
                    
                    <div className="flex-1" />
                    
                    <button
                      onClick={populateFromTurbo}
                      className={`${btnBase} bg-amber-500 border-amber-600 text-black font-semibold ${btnHover}`}
                      title="Parse the text block, populate all fields, and save to database"
                    >
                      📥 Populate & Save
                    </button>
                    
                    {lastAction && (
                      <span className="text-xs bg-green-900 border border-green-700 text-green-200 px-2 py-1 rounded-md">
                        {lastAction}
                      </span>
                    )}
                  </div>
                  
                  {/* Nav buttons below text block */}
                  <div className="mt-3 flex items-center justify-center gap-3">
                    <button
                      onClick={() => turboMove(-1)}
                      disabled={idx === 0}
                      className={`${btnBase} px-6 py-2 ${idx === 0 ? 'bg-gray-600 border-gray-700 text-gray-400 cursor-not-allowed' : `bg-green-600 border-green-700 text-white ${btnHover}`}`}
                    >
                      ◀ Prev
                    </button>
                    <button
                      onClick={() => turboMove(1)}
                      disabled={idx >= filtered.length - 1}
                      className={`${btnBase} px-6 py-2 ${idx >= filtered.length - 1 ? 'bg-gray-600 border-gray-700 text-gray-400 cursor-not-allowed' : `bg-green-500 border-green-600 text-white ${btnHover}`}`}
                    >
                      Next ▶
                    </button>
                  </div>
                </div>
              </div>
            ) : (
              <div className="p-10 text-center text-gray-400">No items in this gallery.</div>
            )}
          </div>
        </div>
      )}

      {/* FULL-SCREEN GUARD shown after opening Reorderer/Importer */}
      {showRefreshGuard && (
        <div className="fixed inset-0 z-50 grid place-items-center bg-black/55 backdrop-blur-[2px]">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-6 text-center">
            <h2 className="text-xl font-semibold mb-2">External change in progress</h2>
            <p className="text-sm text-gray-700 mb-5">
              You opened the Gallery Reorderer or Importer in a new tab. To keep the data safe,
              refresh this editor to load the latest changes before continuing to edit.
            </p>
            <button
              onClick={refreshAfterExternal}
              className="inline-flex items-center justify-center px-4 py-2 rounded-md border bg-black text-white hover:opacity-90"
            >
              Refresh to sync
            </button>
            <div className="mt-3 text-xs text-gray-500">
              This preserves your current gallery, selection, and unlocked state.
            </div>
          </div>
        </div>
      )}

      {/* Pricing Editor Modal */}
      <PricingEditorModal
        isOpen={pricingModalOpen}
        onClose={() => setPricingModalOpen(false)}
      />
    </div>
  );
}
