// src/components/GalleryOrderer.jsx
import { useEffect, useMemo, useRef, useState } from "react";

/* ========= roots (add more here if needed) ========= */
export const DATA_ROOTS = [
  "/src/data/Galleries",
  "/src/pages/Other",
  "/src/data/Other",
];

/* ========= helpers ========= */
function downloadText(text, filename) {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function pickImage(d = {}) {
  return (
    d.url || d.srcXL || d.srcL || d.srcM || d.srcS || d.src || d.imageUrl || d.cover || d.hero?.src || d.preview?.src ||
    d.images?.[0]?.url || d.images?.[0]?.src || ""
  );
}

function isGhost(d) { return d && d.id === "i-k4studios"; }
function isRealItem(d) { return d && !isGhost(d); }
function isHidden(d) {
  if (!d) return true;
  const visibility = String(d.visibility ?? "").trim().toLowerCase();
  return visibility !== "show" && visibility !== "normal";
}

function normalizeSmartPunctuation(value) {
  return typeof value === "string"
    ? value
        .replace(/[\u2018\u2019]/g, "'")
        .replace(/[\u201C\u201D]/g, '"')
        .replace(/[\u2013\u2014]/g, "-")
        .replace(/\u2026/g, "...")
    : value;
}

/** Normalize item -> your JSON-style schema (quoted keys/values) */
function normalizeItem(raw) {
  const notes = normalizeSmartPunctuation(raw.notes ?? raw.collectorNotes);
  const keywords = Array.isArray(raw.keywords)
    ? raw.keywords
    : Array.isArray(raw.tags)
    ? raw.tags
    : undefined;

  const out = {};
  if (raw.id != null) out.id = normalizeSmartPunctuation(raw.id);
  if (raw.title != null) out.title = normalizeSmartPunctuation(raw.title);
  if (raw.description != null) out.description = normalizeSmartPunctuation(raw.description);
  if (raw.alt != null) out.alt = normalizeSmartPunctuation(raw.alt);
  if (raw.src != null || raw.url != null) out.src = normalizeSmartPunctuation(raw.src || raw.url);
  if (raw.srcXL != null) out.srcXL = normalizeSmartPunctuation(raw.srcXL);
  if (raw.srcL != null) out.srcL = normalizeSmartPunctuation(raw.srcL);
  if (raw.srcM != null) out.srcM = normalizeSmartPunctuation(raw.srcM);
  if (raw.srcS != null) out.srcS = normalizeSmartPunctuation(raw.srcS);
  if (raw.srcOriginal != null) out.srcOriginal = normalizeSmartPunctuation(raw.srcOriginal);
  if (raw.buyLink != null) out.buyLink = normalizeSmartPunctuation(raw.buyLink);
  if (keywords != null) out.keywords = keywords.map(normalizeSmartPunctuation);
  if (raw.story != null) out.story = normalizeSmartPunctuation(raw.story);
  if (notes != null) out.notes = notes;
  if (typeof raw.rating === "number") out.rating = raw.rating;
  if (Array.isArray(raw.galleries)) out.galleries = raw.galleries.map(normalizeSmartPunctuation);
  if (raw.visibility != null) out.visibility = normalizeSmartPunctuation(raw.visibility);
  if (typeof raw.sortOrder === "number") out.sortOrder = raw.sortOrder;
  if (raw.themes && typeof raw.themes === "object") out.themes = raw.themes;
  if (raw.contentSource != null) out.contentSource = normalizeSmartPunctuation(raw.contentSource);
  // NOTE: availableSeries is NOT stored in .mjs files - it's stored only in seriesRegistry.json
  if (raw.noSketch === true) out.noSketch = true;
  // Preserve first_seen date for Photo Shoots tracking
  if (raw.first_seen != null) out.first_seen = normalizeSmartPunctuation(raw.first_seen);
  return out;
}

function buildMjsJson(galleryData, exportName = "galleryData") {
  const json = JSON.stringify(galleryData.map(normalizeItem), null, 2);
  return `// Auto-generated by GalleryOrderer – review & commit
export const ${exportName} = ${json};
`;
}

/** Simple array reordering */
function arrayMove(arr, from, to) {
  if (from === to) return arr;
  const copy = arr.slice();
  const item = copy.splice(from, 1)[0];
  copy.splice(to, 0, item);
  return copy;
}

/* --- path helpers --- */
function normalizePath(p = "") { return p.replace(/\\/g, "/"); }

function stripRoot(p) {
  const n = normalizePath(p);
  for (const root of DATA_ROOTS) {
    const r = normalizePath(root) + "/";
    if (n.startsWith(r)) return n.slice(r.length);
  }
  return n.startsWith("/") ? n.slice(1) : n;
}

function prettyLabelFromPath(fullPath) {
  const rel = stripRoot(fullPath).replace(/\.mjs$/i, "");
  const segs = rel.split("/").map((s) =>
    s
      .replace(/-/g, " ")
      .replace(/\b\w/g, (m) => m.toUpperCase())
  );
  const rootHint =
    DATA_ROOTS.find((r) => normalizePath(fullPath).startsWith(normalizePath(r) + "/")) || "";
  const rootName = rootHint.split("/").pop(); // "Galleries" or "Other"
  return `[${rootName}] ${segs.join(" / ")}`;
}

async function loadGalleryDataFresh(selectedPath, fallbackLoader, label = "GalleryOrderer") {
  const cacheBust = `_t=${Date.now()}`;
  const freshPath = `${selectedPath}${selectedPath.includes("?") ? "&" : "?"}${cacheBust}`;

  try {
    const mod = await import(/* @vite-ignore */ freshPath);
    if (Array.isArray(mod)) return mod;
    if (Array.isArray(mod?.galleryData)) return mod.galleryData;
    if (Array.isArray(mod?.default)) return mod.default;
  } catch (error) {
    console.warn(`[${label}] Fresh import failed for ${selectedPath}; falling back to module map.`, error);
  }

  if (typeof fallbackLoader !== "function") return [];

  const mod = await fallbackLoader();
  if (Array.isArray(mod)) return mod;
  if (Array.isArray(mod?.galleryData)) return mod.galleryData;
  if (Array.isArray(mod?.default)) return mod.default;
  return [];
}

/** Read ?dataset=... from URL (supports hash routers, too) */
function getDatasetFromUrl() {
  try {
    const search =
      window.location.search ||
      (window.location.hash.includes("?")
        ? window.location.hash.split("?")[1]
        : "");
    const params = new URLSearchParams(search);
    const raw = params.get("dataset");
    if (!raw) return "";
    const path = raw.startsWith("/") ? raw : `/${raw}`;
    const prefixed = path.startsWith("/src/") ? path : `/src/${path}`;
    return normalizePath(prefixed);
  } catch {
    return "";
  }
}

const SKIP_BACKUP_PROMPT_KEY = "k4-gallery-orderer:skipBackupPrompt";

function readSkipBackupPromptPreference() {
  try {
    return sessionStorage.getItem(SKIP_BACKUP_PROMPT_KEY) === "1";
  } catch {
    return false;
  }
}

function writeSkipBackupPromptPreference(value) {
  try {
    if (value) {
      sessionStorage.setItem(SKIP_BACKUP_PROMPT_KEY, "1");
    } else {
      sessionStorage.removeItem(SKIP_BACKUP_PROMPT_KEY);
    }
  } catch {}
}

/* ========= Component (Grid-only, server save) ========= */
export default function GalleryOrderer({ datasetPath = "" }) {
  // discover datasets in BOTH roots
  const modules = useMemo(() => {
    const maps = [
      import.meta.glob("/src/data/Galleries/**/*.mjs", { eager: false, import: "galleryData" }),
      import.meta.glob("/src/pages/Other/**/*.mjs",     { eager: false, import: "galleryData" }),
      import.meta.glob("/src/data/Other/**/*.mjs",      { eager: false, import: "galleryData" }),
    ];
    return Object.assign({}, ...maps);
  }, []);

  const options = useMemo(() => {
    const rootIdx = (p) => {
      const n = normalizePath(p);
      return DATA_ROOTS.findIndex((r) => n.startsWith(normalizePath(r) + "/"));
    };
    return Object.keys(modules)
      .sort((a, b) => {
        const ra = rootIdx(a), rb = rootIdx(b);
        if (ra !== rb) return ra - rb; // group by root order
        return stripRoot(a).localeCompare(stripRoot(b));
      })
      .map((path) => ({ path, label: prettyLabelFromPath(path) }));
  }, [modules]);

  const [selectedPath, setSelectedPath] = useState("");
  // Multi-select state
  const [selectedIds, setSelectedIds] = useState([]);
  const [backupData, setBackupData] = useState(null);   // full array as loaded (incl ghost)
  const [items, setItems] = useState([]);               // working order (ghost excluded)
  const [backupMade, setBackupMade] = useState(false);
  const [dirty, setDirty] = useState(false);
  const [lastAction, setLastAction] = useState(null);
  const [deletedIds, setDeletedIds] = useState([]);     // track deleted image IDs for series cleanup

  // UI state
  const [thumb, setThumb] = useState(180);
  const [showTitles, setShowTitles] = useState(false);
  const [filter, setFilter] = useState("");

  // undo stack for last move
  const lastMoveRef = useRef(null); // {from,to,snapshot}

  // context menu state
  const [contextMenu, setContextMenu] = useState({ visible: false, x: 0, y: 0, itemId: null, action: null, targetPath: '' });
  const [pendingTransfer, setPendingTransfer] = useState(null);
  const [showBackupPrompt, setShowBackupPrompt] = useState(false);
  const [backupOptions, setBackupOptions] = useState({ source: true, target: true });
  const [skipBackupPrompt, setSkipBackupPrompt] = useState(() => {
    if (typeof window === "undefined") return false;
    return readSkipBackupPromptPreference();
  });

  // --- Read ?dataset=... from URL (consistent with DataSwapper)
  const [urlDataset, setUrlDataset] = useState("");
  useEffect(() => {
    try {
      const search =
        window.location.search ||
        (window.location.hash.includes("?")
          ? window.location.hash.split("?")[1]
          : "");
      const params = new URLSearchParams(search);
      const raw = params.get("dataset");
      if (!raw) return;
      const prefixed = raw.startsWith("/src/") ? raw : `/src/${raw}`;
      setUrlDataset(normalizePath(prefixed));
    } catch {}
  }, []);

  // Choose dataset: prefer prop → URL → sessionStorage → first option
  useEffect(() => {
    if (!options.length) return;

    const fromProp = datasetPath
      ? (datasetPath.startsWith("/") ? datasetPath : `/${datasetPath}`)
      : "";
    const fromUrl = urlDataset || "";
    const fromSession = sessionStorage.getItem("lastDatasetPath") || "";

    const candidate = [fromProp, fromUrl, fromSession, options[0]?.path]
      .find((p) => p && options.some((o) => o.path === normalizePath(p)));

    if (candidate && candidate !== selectedPath) {
      setSelectedPath(normalizePath(candidate));
    }
  }, [options, datasetPath, urlDataset]);

  // Persist selected dataset to sessionStorage for cross-app continuity
  useEffect(() => {
    if (selectedPath) {
      sessionStorage.setItem("lastDatasetPath", selectedPath);
    }
  }, [selectedPath]);

  useEffect(() => {
    writeSkipBackupPromptPreference(skipBackupPrompt);
  }, [skipBackupPrompt]);

  // load dataset
  useEffect(() => {
    let cancelled = false;
    async function load() {
      if (!selectedPath) return;
      const arr = await loadGalleryDataFresh(selectedPath, modules[selectedPath], "GalleryOrderer");
      if (cancelled) return;

      setBackupData(arr);
      const vis = arr.filter(isRealItem);
      setItems(vis);
      setBackupMade(false);
      setDirty(false);
      setFilter("");
      setShowTitles(false);
      setDeletedIds([]); // Clear deleted IDs when switching galleries
      lastMoveRef.current = null;
      setLastAction(null);
    }
    load();
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedPath]);

  // close context menu on outside click
  useEffect(() => {
    function handleClickOutside() {
      if (showBackupPrompt) return;
      if (contextMenu.visible) {
        closeContextMenu();
      }
    }
    document.addEventListener('click', handleClickOutside);
    return () => document.removeEventListener('click', handleClickOutside);
  }, [contextMenu.visible, showBackupPrompt]);

  function note(msg) {
    setLastAction(`${msg} — ${new Date().toLocaleTimeString()}`);
    window.setTimeout(() => setLastAction(null), 6000);
  }

  function ensureBackup() {
    if (!backupData) return;
    const ts = new Date().toISOString().replace(/[:.]/g, "-");
    const galleryName = selectedPath ? prettyLabelFromPath(selectedPath).replace(/[^a-zA-Z0-9-_]/g, "-") : "unknown";
    downloadText(JSON.stringify(backupData, null, 2), `ORDER-BACKUP-${galleryName}-${ts}.json`);
    downloadText(buildMjsJson(backupData, "galleryData"), `ORDER-BACKUP-${galleryName}-${ts}.mjs`);
    setBackupMade(true);
    note("Backup created, ordering unlocked");
  }

  // filter
  const filtered = useMemo(() => {
    const base = items;
    const q = filter.trim().toLowerCase();
    if (!q) return base;
    return base.filter((d) =>
      [d.id, d.title, d.alt, d.description, d.story]
        .filter(Boolean)
        .some((v) => String(v).toLowerCase().includes(q))
    );
  }, [items, filter]);

  // indices map (id -> index in items)
  const idxById = useMemo(() => {
    const m = new Map();
    items.forEach((it, i) => m.set(it.id, i));
    return m;
  }, [items]);

  // drag handlers
  const dragFromIndex = useRef(null);

  function onDragStart(e, id) {
    if (!backupMade) { e.preventDefault(); return; }
    const idx = idxById.get(id);
    dragFromIndex.current = idx;
    e.dataTransfer.effectAllowed = "move";
    e.dataTransfer.setData("text/plain", id);
  }
  function onDragOver(e) { if (dragFromIndex.current == null) return; e.preventDefault(); }
  function onDrop(e, overId) {
    e.preventDefault();
    const from = dragFromIndex.current;
    const to = idxById.get(overId);
    dragFromIndex.current = null;
    if (from == null || to == null || from === to) return;
    lastMoveRef.current = { from, to, snapshot: items.slice() };
    setItems((arr) => arrayMove(arr, from, to));
    setDirty(true);
    note(`Moved #${from + 1} → #${to + 1}`);
  }

  // Multi-select click handler
  function handleSelect(e, id) {
    if (e.button !== 0) return; // only left click
    if (e.ctrlKey || e.metaKey) {
      // Toggle selection
      setSelectedIds(sel => sel.includes(id) ? sel.filter(x => x !== id) : [...sel, id]);
    } else if (e.shiftKey && selectedIds.length > 0) {
      // Range select
      const lastSelected = selectedIds[selectedIds.length - 1];
      const idxA = items.findIndex(x => x.id === lastSelected);
      const idxB = items.findIndex(x => x.id === id);
      if (idxA === -1 || idxB === -1) {
        setSelectedIds([id]);
        return;
      }
      const [start, end] = [idxA, idxB].sort((a, b) => a - b);
      const rangeIds = items.slice(start, end + 1).map(x => x.id);
      setSelectedIds(Array.from(new Set([...selectedIds, ...rangeIds])));
    } else {
      // Single select
      setSelectedIds([id]);
    }
  }

  // Deselect on dataset change or reload
  useEffect(() => { setSelectedIds([]); }, [selectedPath, items]);

  function resetOrder() {
    if (!backupData) return;
    setItems(backupData.filter(isRealItem));
    setDirty(false);
    lastMoveRef.current = null;
    note("Order reset to loaded");
  }
  function undoLastMove() {
    const u = lastMoveRef.current;
    if (!u) return;
    setItems(u.snapshot);
    setDirty(true);
    lastMoveRef.current = null;
    note("Undid last move");
  }

  // toggle visibility for a given item id
  function toggleVisibility(id, wantHidden) {
    setItems(arr =>
      arr.map(it =>
        it.id === id
          ? (wantHidden ? { ...it, visibility: "hidden" } : { ...it, visibility: "show" })
          : it
      )
    );
    setDirty(true);
  }

  // Build final array (ghost first, then reordered items), resequence sortOrder
  function buildFinalArray() {
    if (!backupData) return [];

    const ghosts = backupData.filter(isGhost);

    // Deep clone and normalize everything so no object references carry over
    const cloned = items.map((it) => ({
      id: it.id,
      title: it.title ?? "",
      alt: it.alt ?? "",
      description: it.description ?? "",
      story: it.story ?? "",
      notes: it.notes ?? it.collectorNotes ?? "",
      keywords: Array.isArray(it.keywords)
        ? [...it.keywords]
        : Array.isArray(it.tags)
        ? [...it.tags]
        : [],
      src: it.src ?? it.url ?? "",
      srcXL: it.srcXL ?? "",
      srcL: it.srcL ?? "",
      srcM: it.srcM ?? "",
      srcS: it.srcS ?? "",
      srcOriginal: it.srcOriginal ?? "",
      visibility: it.visibility ?? "",
      rating: typeof it.rating === "number" ? it.rating : undefined,
      galleries: Array.isArray(it.galleries) ? [...it.galleries] : undefined,
      buyLink: it.buyLink ?? "",
    }));

    // Separate visible/hidden and resequence sortOrder
    const shown = cloned.filter((x) => !isHidden(x));
    const hidden = cloned.filter((x) => isHidden(x));

    const ordered = shown.concat(hidden).map((it, i) => ({
      ...it,
      sortOrder: i,
    }));

    return ghosts.concat(ordered);
  }

  // Sync visibility changes with Archive gallery - ATOMIC operation
  // Hidden images get a copy in Archive (visibility: "show")
  // Shown images get hidden in Archive ONLY if they were archived from THIS gallery
  // Single API call + single file write to prevent HMR from killing us mid-operation
  async function syncArchive(fullArray, galleryPath) {
    const hiddenImages = fullArray.filter(it => it.visibility === "hidden");
    
    try {
      console.log(`[Archive] syncFromGallery: ${galleryPath}, ${hiddenImages.length} hidden images`);
      const res = await fetch("/.netlify/functions/updateArchive", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "syncFromGallery",
          imageId: "sync", // Required by validation
          sourceGalleryPath: galleryPath,
          hiddenImages: hiddenImages
        })
      });
      const result = await res.json();
      console.log(`[Archive] Sync complete: hid=${result.hiddenCount}, added=${result.addedCount}, updated=${result.updatedCount}`);
    } catch (err) {
      console.warn(`[Archive] Failed to sync:`, err.message);
    }
  }

  // Save to server (Netlify function) – send FULL ARRAY so visibility persists
  async function saveOrderHere({ reload = true } = {}) {
    if (!backupMade) { alert("Please create a backup first."); return; }
    if (!selectedPath) return;

    const datasetPathClean = selectedPath.replace(/^\//, ""); // strip leading slash
    const fullArray = JSON.parse(JSON.stringify(buildFinalArray()));

    try {
      // Clean up series registry for any deleted items
      if (deletedIds.length > 0) {
        for (const imageId of deletedIds) {
          try {
            await fetch("/.netlify/functions/seriesRegistry", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                action: "removeOccurrence",
                imageId,
                galleryPath: datasetPathClean
              })
            });
            console.log(`[GalleryOrderer] Removed ${imageId} from series registry`);
          } catch (err) {
            console.warn(`[GalleryOrderer] Failed to remove ${imageId} from series registry:`, err.message);
          }
        }
        setDeletedIds([]); // Clear after processing
      }

      const res = await fetch("/.netlify/functions/updateGalleryOrder", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          datasetPath: datasetPathClean, // e.g. src/data/.../Color.mjs OR src/pages/Other/...
          fullArray,                     // includes order + visibility + everything normalized on server
        }),
      });
      if (!res.ok) throw new Error(await res.text());
      
      // Sync visibility changes with Archive gallery
      // Hidden images get copied to Archive, shown images get removed
      note("Syncing with Archive...");
      await syncArchive(fullArray, datasetPathClean);
      
      note("Saved order/visibility in-place");
      setDirty(false);
      // Refresh page AFTER syncArchive completes (not before!)
      if (reload) window.location.reload();
      return true;
    } catch (err) {
      alert("Server save failed. Falling back to download.\n\n" + err.message);
      const filename = datasetPathClean.split("/").pop() || "gallery.mjs";
      const text = buildMjsJson(fullArray, "galleryData");
      downloadText(text, filename);
      note(`Downloaded → ${filename}`);
      setDirty(false);
      return false;
    }
  }

  useEffect(() => {
    // On mount, always restore unlocked state (no backup prompt, ordering enabled)
    setBackupMade(true);
  }, []);

  // Optional manual download
  function saveAsDownload() {
    if (!selectedPath) return;
    const datasetPathClean = selectedPath.replace(/^\//, "");
    const filename = datasetPathClean.split("/").pop() || "gallery.mjs";
    const text = buildMjsJson(buildFinalArray(), "galleryData");
    downloadText(text, filename);
    note(`Downloaded → ${filename}`);
    setDirty(false);
  }

  // context menu handler
  function handleContextMenu(e, itemId) {
    e.preventDefault();
    setContextMenu({ visible: true, x: e.clientX, y: e.clientY, itemId, action: null, targetPath: '' });
  }

  function closeContextMenu() {
    setContextMenu({ visible: false, x: 0, y: 0, itemId: null, action: null, targetPath: '' });
  }

  function removeItems(idsToRemove) {
    if (!Array.isArray(idsToRemove) || idsToRemove.length === 0) return;

    const uniqueIds = Array.from(new Set(idsToRemove));
    const idSet = new Set(uniqueIds);

    setDeletedIds((prev) => Array.from(new Set([...prev, ...uniqueIds])));
    setItems((currentItems) => currentItems.filter((it) => !idSet.has(it.id)));
    setBackupData((currentData) => currentData?.filter((it) => !idSet.has(it.id)) ?? currentData);
    setSelectedIds((currentSelected) => currentSelected.filter((id) => !idSet.has(id)));
    setDirty(true);
  }

  function confirmAndRemove(idsToRemove) {
    const count = idsToRemove.length;
    const message = count === 1
      ? 'Are you sure you want to delete this image? This action cannot be undone.'
      : `Are you sure you want to delete these ${count} images? This action cannot be undone.`;

    if (!window.confirm(message)) return;

    removeItems(idsToRemove);
    note(count === 1 ? 'Deleted image' : `Deleted ${count} selected images`);
    closeContextMenu();
  }

  function getActionItemIds(itemId) {
    if (!itemId) return [];
    return selectedIds.includes(itemId) ? selectedIds : [itemId];
  }

  function startTransfer(actionType) {
    if (!contextMenu.targetPath) return;

    const transferRequest = {
      itemId: contextMenu.itemId,
      action: actionType,
      targetPath: contextMenu.targetPath,
    };
    setPendingTransfer(transferRequest);

    if (skipBackupPrompt) {
      performAction({
        transferRequestOverride: transferRequest,
        actionOverride: actionType,
        backupSelections: { source: false, target: false },
        skipBackups: true,
      });
      closeContextMenu();
      return;
    }

    setBackupOptions({ source: true, target: true });
    setShowBackupPrompt(true);
    closeContextMenu();
  }

  // perform move or copy
  async function performAction(options = {}) {
    const { actionOverride, backupSelections, skipBackups = false, transferRequestOverride } = options;
    const transferRequest = transferRequestOverride || pendingTransfer || contextMenu;
    const { itemId, action: contextAction, targetPath } = transferRequest;
    const action = actionOverride || contextAction;
    if (!itemId || !action || !targetPath) return;

    // Warn if unsaved changes before moving
    if (action === 'move' && dirty) {
      const proceed = window.confirm('You have unsaved changes. Do you want to save before moving? Click OK to save, Cancel to discard changes and continue.');
      if (proceed) {
        // Keep this page alive until the transfer completes. Reloading during
        // this save can abort the follow-up request that removes the source.
        const saved = await saveOrderHere({ reload: false });
        if (!saved) return;
      } else {
        setDirty(false);
      }
    }

    const actionItemIds = getActionItemIds(itemId);
    const actionItems = actionItemIds
      .map((id) => items.find((it) => it.id === id))
      .filter(Boolean);
    if (actionItems.length === 0) return;

    // Load target data for backup download / duplicate preview
    const targetData = await loadGalleryDataFresh(targetPath, modules[targetPath], "GalleryOrderer:target");
    const targetIdSet = new Set(targetData.map((it) => it.id));
    const itemsAlreadyInTarget = actionItems.filter((it) => targetIdSet.has(it.id));
    const itemsToAdd = actionItems.filter((it) => !targetIdSet.has(it.id));

    if (itemsAlreadyInTarget.length > 0) {
      if (action === 'move') {
        const confirmDelete = window.confirm(
          itemsAlreadyInTarget.length === actionItems.length
            ? 'The selected image(s) are already in the target gallery. Do you want to delete them from the source gallery?'
            : `${itemsAlreadyInTarget.length} selected image(s) are already in the target gallery. They can be removed from the source while the remaining ${itemsToAdd.length} are added to the target. Continue?`
        );
        if (!confirmDelete) {
          closeContextMenu();
          return;
        }
      } else if (action === 'copy') {
        if (itemsToAdd.length === 0) {
          alert('All selected image(s) are already in the target gallery. Nothing to copy.');
          closeContextMenu();
          return;
        }
      }
    }

    // download backups if selected and not skipping for session
    const effectiveBackupOptions = backupSelections || backupOptions;

    if (!skipBackups) {
      if (effectiveBackupOptions.source) {
        const ts = new Date().toISOString().replace(/[:.]/g, "-");
        const sourceFilename = `BACKUP-${selectedPath.split('/').pop()}-${ts}`;
        downloadText(JSON.stringify(backupData, null, 2), `${sourceFilename}.json`);
        downloadText(buildMjsJson(backupData, "galleryData"), `${sourceFilename}.mjs`);
      }
      if (effectiveBackupOptions.target) {
        const ts = new Date().toISOString().replace(/[:.]/g, "-");
        const targetFilename = `BACKUP-${targetPath.split('/').pop()}-${ts}`;
        downloadText(JSON.stringify(targetData, null, 2), `${targetFilename}.json`);
        downloadText(buildMjsJson(targetData, "galleryData"), `${targetFilename}.mjs`);
      }
    }

    // prepare updated data
    const normalizedItems = itemsToAdd.map((item) => normalizeItem(item));
    const actionIdSet = new Set(actionItemIds);

    try {
      const res = await fetch("/.netlify/functions/updateGalleryOrder", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "transfer",
          mode: action,
          sourceDatasetPath: selectedPath.replace(/^\//, ""),
          targetDatasetPath: targetPath.replace(/^\//, ""),
          itemIds: actionItemIds,
        }),
      });
      if (!res.ok) throw new Error(await res.text());
      await res.json();
    } catch (err) {
      alert(`Failed to ${action} item(s): ${err.message}`);
      return;
    }

    setPendingTransfer(null);

    // update local state if current dataset affected
    if (action === 'move' && targetPath !== selectedPath) {
      setItems((currentItems) => currentItems.filter((it) => !actionIdSet.has(it.id)));
      setBackupData((currentData) => currentData?.filter((it) => !actionIdSet.has(it.id)) ?? currentData);
      setSelectedIds((currentSelected) => currentSelected.filter((id) => !actionIdSet.has(id)));
      // Both files were already persisted by the transfer endpoint.
      setDirty(false);
    }

    const movedCount = actionItems.length;
    const addedCount = normalizedItems.length;
    const duplicateCount = itemsAlreadyInTarget.length;
    if (action === 'move') {
      if (duplicateCount > 0 && addedCount === 0) {
        note(movedCount === 1 ? 'Deleted item from source (already in target)' : `Deleted ${movedCount} items from source (already in target)`);
      } else if (duplicateCount > 0) {
        note(`Moved ${addedCount} and removed ${duplicateCount} already in target`);
      } else {
        note(movedCount === 1 ? `Moved item to ${targetPath.split('/').pop()}` : `Moved ${movedCount} items to ${targetPath.split('/').pop()}`);
      }
    } else {
      note(addedCount === 1 ? `Copied item to ${targetPath.split('/').pop()}` : `Copied ${addedCount} items to ${targetPath.split('/').pop()}`);
    }
    window.location.reload();
    closeContextMenu();
  }

  const total = items.length;

  return (
    <div
      className="p-6 max-w-7xl mx-auto text-sm"
      style={{
        fontFamily: "'Glegoo', serif",
        background: "#f5f3ef", // 🟤 soft painterly beige background to match DataSwapper
        minHeight: "100vh",
        color: "#2a1f17",
      }}
    >
      {/* Header Bar */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          background: "#e4dae9",
          padding: "10px 20px",
          borderRadius: 8,
          marginBottom: 18,
          boxShadow: "0 2px 6px rgba(0,0,0,0.1)",
        }}
      >
        <div>
          <h1 style={{ fontSize: "1.6em", fontWeight: "700", margin: 0 }}>
            Gallery Orderer
          </h1>
          {selectedPath && (
            <div style={{
              fontSize: "0.9em",
              color: "#5a4a3a",
              marginTop: 4,
              fontWeight: 500,
              opacity: 0.8
            }}>
              {prettyLabelFromPath(selectedPath)}
            </div>
          )}
        </div>

        <button
          onClick={() => {
            const q = selectedPath
              ? `?dataset=${encodeURIComponent(selectedPath.replace(/^\/src\//, ""))}`
              : "";
            window.open(`/admin/GalleryDataSwapper${q}`, "_self"); // open in same tab
          }}
          style={{
            background: "#d4c4b5",
            border: "1px solid #b6a998",
            borderRadius: 6,
            padding: "6px 12px",
            fontWeight: "600",
            cursor: "pointer",
            transition: "background 0.2s ease",
          }}
          onMouseOver={(e) => (e.currentTarget.style.background = "#c3b29e")}
          onMouseOut={(e) => (e.currentTarget.style.background = "#d4c4b5")}
        >
          ⇄ Switch to Data View
        </button>
      </div>

      {/* dataset + backup gate */}
      <div className="flex flex-wrap items-center gap-2 mb-3">

        <select
          className="border rounded-md px-2 py-1 min-w-[22rem]"
          value={selectedPath}
          onChange={(e) => setSelectedPath(e.target.value)}
        >
          {options.map((o) => (
            <option key={o.path} value={o.path}>
              {o.label}
            </option>
          ))}
        </select>

        {!backupMade ? (
          <>
            <button onClick={ensureBackup} className="px-3 py-1 rounded-md border bg-white">
              1) Make Data Backup
            </button>
            <button onClick={() => { setBackupMade(true); }} className="px-3 py-1 rounded-md border bg-gray-50 ml-2">
              Skip Backup
            </button>
          </>
        ) : (
          <span className="text-green-700">✅ Backup created — ordering unlocked</span>
        )}

        <div className="ml-auto flex items-center gap-2">
          <input
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            placeholder="Search id/title/text…"
            className="w-72 border rounded-md px-2 py-1"
          />
          <label className="flex items-center gap-1 px-2 py-1 border rounded-md">
            <input
              type="checkbox"
              checked={showTitles}
              onChange={() => setShowTitles((v) => !v)}
            />
            Titles
          </label>
          <div className="flex items-center gap-2 border rounded-md px-2 py-1">
            <span className="opacity-70">Thumb</span>
            <input
              type="range"
              min={90}
              max={320}
              value={thumb}
              onChange={(e) => setThumb(Number(e.target.value))}
            />
          </div>
        </div>
      </div>

      {/* actions */}
      <div className="mb-3 flex flex-wrap items-center gap-2">
        {dirty && <span className="text-red-600 font-medium">Unsaved changes</span>}

        <button onClick={saveOrderHere} className="px-3 py-1 rounded-md border">
          Save Here (server)
        </button>
        <button onClick={saveAsDownload} className="px-3 py-1 rounded-md border">
          Download .mjs
        </button>
        <button onClick={resetOrder} className="px-3 py-1 rounded-md border">
          Reset To Loaded
        </button>
        <button onClick={undoLastMove} className="px-3 py-1 rounded-md border">
          Undo Last Move
        </button>

        {selectedIds.length > 0 && (
          <>
            <span className="px-2 py-1 text-xs rounded-md border bg-blue-50 text-blue-700">
              {selectedIds.length} selected
            </span>
            <button
              onClick={() => confirmAndRemove(selectedIds)}
              className="px-3 py-1 rounded-md border bg-red-50 hover:bg-red-100 text-red-700"
            >
              Delete Selected
            </button>
            <button
              onClick={() => setSelectedIds([])}
              className="px-3 py-1 rounded-md border"
            >
              Clear Selection
            </button>
          </>
        )}

        <span className="ml-auto opacity-70">{filtered.length}/{total}</span>

        {lastAction && (
          <span className="ml-2 text-xs bg-green-50 border border-green-200 text-green-800 px-2 py-1 rounded-md">
            {lastAction}
          </span>
        )}
      </div>

      {/* grid DnD */}
      <div
        className={`${!backupMade ? "pointer-events-none opacity-60" : ""}`}
        style={{
          display: "grid",
          gap: "0.75rem",
          gridTemplateColumns: `repeat(auto-fill, minmax(${thumb}px, 1fr))`,
        }}
      >
        {filtered.map((it) => {
          const img = pickImage(it);
          const i = items.findIndex((x) => x.id === it.id);
          const hidden = isHidden(it);
          const selected = selectedIds.includes(it.id);
          return (
            <div
              key={it.id}
              draggable
              onDragStart={(e) => onDragStart(e, it.id)}
              onDragOver={onDragOver}
              onDrop={(e) => onDrop(e, it.id)}
              onContextMenu={(e) => handleContextMenu(e, it.id)}
              onClick={(e) => handleSelect(e, it.id)}
              className={`relative border rounded-md bg-white overflow-hidden shadow-sm cursor-pointer ${selected ? "ring-2 ring-blue-500" : ""}`}
              title={`#${i + 1} – ${it.id}${hidden ? " (hidden)" : ""}`}
              style={hidden ? { opacity: 0.5, filter: "grayscale(0.35)" } : undefined}
            >
              {/* S/H tiny toggle */}
              <div className="absolute top-1 right-1 z-10 flex gap-1">
                <button
                  type="button"
                  className={`px-1.5 h-6 text-[11px] rounded ${hidden ? "bg-white border border-gray-300 text-gray-500" : "bg-green-600 text-white border border-green-700"}`}
                  title="Show"
                  onClick={(e) => { e.preventDefault(); e.stopPropagation(); toggleVisibility(it.id, false); }}
                >
                  S
                </button>
                <button
                  type="button"
                  className={`px-1.5 h-6 text-[11px] rounded ${hidden ? "bg-red-600 text-white border border-red-700" : "bg-white border border-gray-300 text-gray-500"}`}
                  title="Hide"
                  onClick={(e) => { e.preventDefault(); e.stopPropagation(); toggleVisibility(it.id, true); }}
                >
                  H
                </button>
              </div>

              {img ? (
                <img
                  src={img}
                  alt=""
                  className="block w-full"
                  style={{ height: thumb, objectFit: "cover" }}
                />
              ) : (
                <div className="w-full grid place-items-center" style={{ height: thumb }}>
                  No image
                </div>
              )}

              {/* footer */}
              <div className="flex items-center justify-between px-2 py-1 text-xs border-t bg-gray-50">
                <span className="font-medium">#{i + 1}</span>
                {showTitles ? (
                  <input
                    type="text"
                    className="ml-2 px-1 py-0.5 border rounded text-xs truncate bg-white"
                    value={it.title || ""}
                    title={it.title || it.id}
                    onChange={e => {
                      const newTitle = e.target.value;
                      setItems(items => items.map(item => item.id === it.id ? { ...item, title: newTitle } : item));
                      setBackupData(data => data.map(item => item.id === it.id ? { ...item, title: newTitle } : item));
                      setDirty(true);
                    }}
                  />
                ) : (
                  <span className="opacity-60 truncate ml-2">{it.id}</span>
                )}
                {hidden && (
                  <span className="ml-2 inline-flex items-center px-1.5 py-[1px] text-[10px] rounded bg-red-100 text-red-700 border border-red-200">
                    Hidden
                  </span>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* context menu */}
      {contextMenu.visible && (
        <div
          className="fixed z-50 bg-white border border-gray-300 rounded-md shadow-lg p-3"
          style={{ left: contextMenu.x, top: contextMenu.y }}
          onClick={(e) => e.stopPropagation()}
        >
          <div className="text-sm font-medium mb-2">Move/Copy to:</div>
          <select
            className="border rounded-md px-2 py-1 mb-2 w-full"
            value={contextMenu.targetPath}
            onChange={(e) => setContextMenu(prev => ({ ...prev, targetPath: e.target.value }))}
          >
            <option value="">Select target...</option>
            {options.filter(o => o.path !== selectedPath).map((o) => (
              <option key={o.path} value={o.path}>
                {o.label}
              </option>
            ))}
          </select>
          <div className="flex gap-2 mb-2">
            <button
              onClick={() => {
                // Move selected images to top
                setItems(items => {
                  const selSet = new Set(selectedIds);
                  const selected = items.filter(it => selSet.has(it.id));
                  const rest = items.filter(it => !selSet.has(it.id));
                  return [...selected, ...rest];
                });
                setDirty(true);
                note('Moved selected to top');
                closeContextMenu();
              }}
              className="px-3 py-1 rounded-md border bg-blue-50 hover:bg-blue-100"
              disabled={selectedIds.length === 0}
            >
              Move to Top
            </button>
            <button
              onClick={() => {
                // Move selected images to bottom
                setItems(items => {
                  const selSet = new Set(selectedIds);
                  const selected = items.filter(it => selSet.has(it.id));
                  const rest = items.filter(it => !selSet.has(it.id));
                  return [...rest, ...selected];
                });
                setDirty(true);
                note('Moved selected to bottom');
                closeContextMenu();
              }}
              className="px-3 py-1 rounded-md border bg-blue-50 hover:bg-blue-100"
              disabled={selectedIds.length === 0}
            >
              Move to Bottom
            </button>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => startTransfer('move')}
              className="px-3 py-1 rounded-md border bg-blue-50 hover:bg-blue-100"
              disabled={!contextMenu.targetPath}
            >
              Move
            </button>
            <button
              onClick={() => startTransfer('copy')}
              className="px-3 py-1 rounded-md border bg-green-50 hover:bg-green-100"
              disabled={!contextMenu.targetPath}
            >
              Copy
            </button>
            <button
              onClick={() => {
                const idsToRemove = selectedIds.includes(contextMenu.itemId)
                  ? selectedIds
                  : [contextMenu.itemId];
                confirmAndRemove(idsToRemove);
              }}
              className="px-3 py-1 rounded-md border bg-red-50 hover:bg-red-100 text-red-700"
            >
              {selectedIds.includes(contextMenu.itemId) && selectedIds.length > 1
                ? `Delete ${selectedIds.length} Selected`
                : 'Delete Image'}
            </button>
            <button
              onClick={closeContextMenu}
              className="px-3 py-1 rounded-md border"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* backup prompt */}
      {showBackupPrompt && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50"
          onClick={(e) => e.stopPropagation()}
        >
          <div
            className="bg-white p-6 rounded-md shadow-lg max-w-md w-full"
            onClick={(e) => e.stopPropagation()}
          >
            <h3 className="text-lg font-semibold mb-4">Backup Before Proceeding</h3>
            <p className="mb-4 text-sm">Before {pendingTransfer?.action === 'move' ? 'moving' : 'copying'} the item, download backups of the affected files?</p>
            <div className="space-y-2 mb-4">
              <label className="flex items-center">
                <input
                  type="checkbox"
                  checked={backupOptions.source}
                  onChange={(e) => setBackupOptions(prev => ({ ...prev, source: e.target.checked }))}
                  className="mr-2"
                />
                Backup source file ({selectedPath.split('/').pop()})
              </label>
              <label className="flex items-center">
                <input
                  type="checkbox"
                  checked={backupOptions.target}
                  onChange={(e) => setBackupOptions(prev => ({ ...prev, target: e.target.checked }))}
                  className="mr-2"
                />
                Backup target file ({pendingTransfer?.targetPath?.split('/').pop() || ''})
              </label>
              <label className="flex items-center">
                <input
                  type="checkbox"
                  checked={skipBackupPrompt}
                  onChange={(e) => setSkipBackupPrompt(e.target.checked)}
                  className="mr-2"
                />
                Don't show backup prompt again this session
              </label>
            </div>
            <div className="flex gap-2 justify-end">
              <button
                onClick={() => {
                  const backupSelections = { ...backupOptions };
                  const skipForThisAction = skipBackupPrompt;
                  const transferRequest = pendingTransfer;
                  setShowBackupPrompt(false);
                  performAction({
                    transferRequestOverride: transferRequest,
                    backupSelections,
                    skipBackups: skipForThisAction,
                  });
                }}
                className="px-4 py-2 rounded-md border bg-blue-50 hover:bg-blue-100"
              >
                Proceed
              </button>
              <button
                onClick={() => {
                  setShowBackupPrompt(false);
                  setPendingTransfer(null);
                  closeContextMenu();
                }}
                className="px-4 py-2 rounded-md border"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="mt-4 text-xs opacity-70">
        Drag to reorder. Use the S/H buttons to show/hide items. Click <strong>Save Here (server)</strong> to overwrite
        the dataset file via Netlify (order + visibility). If the server save fails, use <strong>Download .mjs</strong>
        as a fallback.
      </div>
    </div>
  );
}
