import { useEffect, useMemo, useState } from "react";

/* ========= roots (same concept as GalleryOrderer) ========= */
export const DATA_ROOTS = [
  "/src/data/Galleries",
  "/src/pages/Other",
  "/src/data/Other",
];

// Adjust this if you put themes somewhere else
const THEME_FILE_PATH = "/src/data/themes/themes.mjs";

/* ========= helpers ========= */
function downloadText(text, filename) {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function normalizePath(p = "") {
  return p.replace(/\\/g, "/");
}

function stripRoot(p) {
  const n = normalizePath(p);
  for (const root of DATA_ROOTS) {
    const r = normalizePath(root) + "/";
    if (n.startsWith(r)) return n.slice(r.length);
  }
  return n.startsWith("/") ? n.slice(1) : n;
}

function prettyLabelFromPath(fullPath) {
  const rel = stripRoot(fullPath).replace(/\.mjs$/i, "");
  const segs = rel.split("/").map((s) =>
    s
      .replace(/-/g, " ")
      .replace(/\b\w/g, (m) => m.toUpperCase())
  );
  const rootHint =
    DATA_ROOTS.find((r) => normalizePath(fullPath).startsWith(normalizePath(r) + "/")) || "";
  const rootName = rootHint.split("/").pop(); // "Galleries" or "Other"
  return `[${rootName}] ${segs.join(" / ")}`;
}

function isGhost(d) {
  return d && d.id === "i-k4studios";
}
function isRealItem(d) {
  return d && !isGhost(d);
}

function pickImage(d = {}) {
  return (
    d.url ||
    d.srcXL ||
    d.srcL ||
    d.srcM ||
    d.srcS ||
    d.src ||
    d.imageUrl ||
    d.cover ||
    d.hero?.src ||
    d.preview?.src ||
    d.images?.[0]?.url ||
    d.images?.[0]?.src ||
    ""
  );
}

// Normalize image item when writing back to gallery .mjs
function normalizeGalleryItem(raw) {
  const notes = raw.notes ?? raw.collectorNotes;
  const keywords = Array.isArray(raw.keywords)
    ? raw.keywords
    : Array.isArray(raw.tags)
    ? raw.tags
    : undefined;

  const out = {};
  if (raw.id != null) out.id = raw.id;
  if (raw.title != null) out.title = raw.title;
  if (raw.description != null) out.description = raw.description;
  if (raw.alt != null) out.alt = raw.alt;
  if (raw.src != null || raw.url != null) out.src = raw.src || raw.url;
  if (raw.srcXL != null) out.srcXL = raw.srcXL;
  if (raw.srcL != null) out.srcL = raw.srcL;
  if (raw.srcM != null) out.srcM = raw.srcM;
  if (raw.srcS != null) out.srcS = raw.srcS;
  if (raw.srcOriginal != null) out.srcOriginal = raw.srcOriginal;
  if (raw.buyLink != null) out.buyLink = raw.buyLink;
  if (keywords != null) out.keywords = keywords;
  if (raw.story != null) out.story = raw.story;
  if (notes != null) out.notes = notes;
  if (typeof raw.rating === "number") out.rating = raw.rating;
  if (Array.isArray(raw.galleries)) out.galleries = raw.galleries;
  if (raw.visibility != null) out.visibility = raw.visibility;
  if (typeof raw.sortOrder === "number") out.sortOrder = raw.sortOrder;
  if (raw.themes && typeof raw.themes === "object") out.themes = raw.themes;
  return out;
}

function buildMjsJsonFromGallery(galleryData, exportName = "galleryData") {
  const json = JSON.stringify(galleryData.map(normalizeGalleryItem), null, 2);
  return `// Auto-generated by ThemeBuilder – review & commit
export const ${exportName} = ${json};
`;
}

function buildThemesMjsJson(themesArray, exportName = "themes") {
  const json = JSON.stringify(themesArray, null, 2);
  const header = `// Auto-generated by ThemeBuilder — review & commit

/**
 * THEMES MASTER FILE (Registry/Index)
 * ------------------------------------
 * This file is the THEME REGISTRY. It stores metadata for each theme.
 * Image membership is stored in the gallery .mjs files themselves.
 *
 * Each theme tracks:
 *  - name: Display name for the theme
 *  - slug: URL-safe identifier (used in URLs and as key in image.themes)
 *  - description: SEO description for the theme
 *  - dataset: Path to the gallery .mjs file this theme draws from
 *  - visible: Whether theme appears in dropdowns/buttons (true/false)
 *  - createdAt / updatedAt: Timestamps
 *
 * HOW THEME MEMBERSHIP WORKS:
 * Each image in its gallery .mjs file stores its theme membership:
 *   themes: { "black-hats": 0, "cowboys-and-horses": 5 }
 *   (key = theme slug, value = display order within that theme)
 *
 * TO HIDE A THEME: Set visible: false
 * TO DELETE A THEME: Remove entry here AND clean themes property from gallery images
 */

`;
  return header + `export const ${exportName} = ${json};\n`;
}

/** Simple array reordering */
function arrayMove(arr, from, to) {
  if (from === to) return arr;
  const copy = arr.slice();
  const item = copy.splice(from, 1)[0];
  copy.splice(to, 0, item);
  return copy;
}

function slugifyName(name) {
  return String(name || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/* ========= ThemeBuilder Component ========= */

export default function ThemeBuilder() {
  // Step: "selectTheme" | "metadata" | "selectImages" | "reorder" | "done"
  const [step, setStep] = useState("selectTheme");

  // Load all gallery datasets (same pattern as GalleryOrderer)
  const datasetModules = useMemo(() => {
    const maps = [
      import.meta.glob("/src/data/Galleries/**/*.mjs", {
        eager: false,
        import: "galleryData",
      }),
      import.meta.glob("/src/pages/Other/**/*.mjs", {
        eager: false,
        import: "galleryData",
      }),
      import.meta.glob("/src/data/Other/**/*.mjs", {
        eager: false,
        import: "galleryData",
      }),
    ];
    return Object.assign({}, ...maps);
  }, []);

  const datasetOptions = useMemo(() => {
    const rootIdx = (p) => {
      const n = normalizePath(p);
      return DATA_ROOTS.findIndex((r) => n.startsWith(normalizePath(r) + "/"));
    };
    return Object.keys(datasetModules)
      .sort((a, b) => {
        const ra = rootIdx(a),
          rb = rootIdx(b);
        if (ra !== rb) return ra - rb;
        return stripRoot(a).localeCompare(stripRoot(b));
      })
      .map((path) => ({ path, label: prettyLabelFromPath(path) }));
  }, [datasetModules]);

  // Load themes.mjs
  const [themes, setThemes] = useState([]);
  const [themesLoaded, setThemesLoaded] = useState(false);

  useEffect(() => {
    const themeMods = import.meta.glob("/src/data/themes/**/*.mjs", {
      eager: false,
    });

    async function loadThemes() {
      console.log("ThemeBuilder: Available theme files:", Object.keys(themeMods));
      const filePath = Object.keys(themeMods).find(
        (p) => normalizePath(p) === normalizePath(THEME_FILE_PATH)
      );
      if (!filePath) {
        console.warn("ThemeBuilder: themes.mjs not found at", THEME_FILE_PATH);
        setThemes([]);
        setThemesLoaded(true);
        return;
      }
      console.log("ThemeBuilder: Loading from", filePath);
      const mod = await themeMods[filePath]();
      console.log("ThemeBuilder: Raw module:", mod);
      const arr =
        Array.isArray(mod?.themes) && mod.themes.length >= 0
          ? mod.themes
          : Array.isArray(mod?.default)
          ? mod.default
          : [];
      console.log("ThemeBuilder: Loaded themes:", arr.map(t => t.name || t.slug));
      setThemes(arr);
      setThemesLoaded(true);
    }

    loadThemes().catch((err) => {
      console.error("Failed to load themes.mjs", err);
      setThemes([]);
      setThemesLoaded(true);
    });
  }, []);

  // Working theme state
  const [selectedThemeSlug, setSelectedThemeSlug] = useState("");
  const [themeName, setThemeName] = useState("");
  const [themeSlug, setThemeSlug] = useState("");
  const [themeDescription, setThemeDescription] = useState("");
  const [themeDatasetPath, setThemeDatasetPath] = useState("");
  const [themeImagesCount, setThemeImagesCount] = useState(0);
  const [themeVisible, setThemeVisible] = useState(true);

  // Tracks the original slug for comparison when editing
  const [originalSlug, setOriginalSlug] = useState("");

  // Controls whether a rename banner should appear
  const [pendingRename, setPendingRename] = useState(false);

  // Gallery data for current theme dataset
  const [galleryFullData, setGalleryFullData] = useState([]); // includes ghosts
  const [galleryItems, setGalleryItems] = useState([]); // isRealItem only

  // Selection + reorder state
  const [selectedIds, setSelectedIds] = useState([]);
  const [reorderItems, setReorderItems] = useState([]); // only selected items, ordered
  const [filterText, setFilterText] = useState("");
  const [thumb, setThumb] = useState(180);
  const [showSelectedOnly, setShowSelectedOnly] = useState(false);

  // Backup state (for BOTH themes & dataset)
  const [backupMade, setBackupMade] = useState(false);
  const [skipBackupPrompt, setSkipBackupPrompt] = useState(false);
  const [lastAction, setLastAction] = useState(null);

  function note(msg) {
    setLastAction(`${msg} — ${new Date().toLocaleTimeString()}`);
    window.setTimeout(() => setLastAction(null), 6000);
  }

  /* ========= Step 1: select / create theme ========= */

  const themeOptions = useMemo(() => {
    const base = themes.slice().sort((a, b) =>
      String(a.name || "").localeCompare(String(b.name || ""))
    );
    return base;
  }, [themes]);

  function handleSelectExistingTheme(slug) {
    const t = themes.find((x) => x.slug === slug);
    if (!t) return;

    setSelectedThemeSlug(slug);
    setOriginalSlug(slug);     // <-- TRACK ORIGINAL
    setThemeName(t.name || "");
    setThemeSlug(t.slug || "");
    setThemeDescription(t.description || "");
    setThemeVisible(t.visible !== false); // default to true if not set
    
    // Normalize dataset path - ensure it has leading slash for internal use
    const datasetPath = t.dataset ? (t.dataset.startsWith("/") ? t.dataset : "/" + t.dataset) : "";
    setThemeDatasetPath(datasetPath);
    setStep("metadata");

    // If dataset present, load gallery + pre-select membership
    if (datasetPath) {
      loadGalleryDatasetForTheme(datasetPath, slug);
    } else {
      setGalleryFullData([]);
      setGalleryItems([]);
      setSelectedIds([]);
      setReorderItems([]);
      setThemeImagesCount(0);
    }
  }

  function handleCreateNewTheme() {
    setSelectedThemeSlug("");
    setThemeName("");
    setThemeSlug("");
    setThemeDescription("");
    setThemeVisible(true);
    setThemeDatasetPath("");
    setGalleryFullData([]);
    setGalleryItems([]);
    setSelectedIds([]);
    setReorderItems([]);
    setThemeImagesCount(0);
    setStep("metadata");
  }

  /* ========= Gallery loading & membership derivation ========= */

  async function loadGalleryDatasetForTheme(datasetPath, slugForMembership) {
    // Normalize path to match import.meta.glob keys (they start with /src/...)
    let normPath = normalizePath(datasetPath);
    if (!normPath.startsWith("/")) {
      normPath = "/" + normPath;
    }
    
    const loader = datasetModules[normPath];
    if (!loader) {
      console.warn("ThemeBuilder: dataset not found:", normPath, "Available:", Object.keys(datasetModules).slice(0, 5));
      setGalleryFullData([]);
      setGalleryItems([]);
      setSelectedIds([]);
      setReorderItems([]);
      setThemeImagesCount(0);
      return;
    }
    const mod = await loader();
    const arr = Array.isArray(mod)
      ? mod
      : Array.isArray(mod?.galleryData)
      ? mod.galleryData
      : Array.isArray(mod?.default)
      ? mod.default
      : [];

    const full = arr || [];
    const visible = full.filter(isRealItem);

    setGalleryFullData(full);
    setGalleryItems(visible);

    // Derive membership from existing themes in the images
    if (slugForMembership) {
      const members = visible.filter(
        (img) => img.themes && img.themes[slugForMembership] != null
      );

      // Sort by stored per-image theme index
      members.sort(
        (a, b) =>
          (a.themes[slugForMembership] ?? 0) -
          (b.themes[slugForMembership] ?? 0)
      );

      const ids = members.map((m) => m.id);
      setSelectedIds(ids);
      setReorderItems(members);
      setThemeImagesCount(ids.length);
    } else {
      // brand-new theme: nothing selected yet
      setSelectedIds([]);
      setReorderItems([]);
      setThemeImagesCount(0);
    }
  }

  /* ========= Step 2: metadata handlers ========= */

  function handleMetadataNext() {
    // Auto-generate slug if none
    const slug = themeSlug || slugifyName(themeName);
    setThemeSlug(slug);

    // Require dataset selection before moving on
    if (!themeDatasetPath) {
      alert("Please choose a dataset/gallery for this theme.");
      return;
    }

    // Check for duplicate slug (only for NEW themes, not editing existing)
    if (!selectedThemeSlug) {
      const existingTheme = themes.find((t) => t.slug === slug);
      if (existingTheme) {
        const overwrite = window.confirm(
          `A theme with slug "${slug}" already exists:\n\n` +
          `• Name: ${existingTheme.name}\n` +
          `• Dataset: ${existingTheme.dataset}\n` +
          `• Images: ${existingTheme.imageCount ?? 0}\n\n` +
          `Do you want to EDIT that existing theme instead?\n\n` +
          `Click OK to edit the existing theme.\n` +
          `Click Cancel to go back and choose a different name.`
        );
        if (overwrite) {
          // Switch to editing the existing theme
          handleSelectExistingTheme(slug);
          return;
        } else {
          // Let user change the name
          return;
        }
      }
    }

    // Load gallery + membership (if editing existing theme)
    loadGalleryDatasetForTheme(themeDatasetPath, selectedThemeSlug || slug);
    setStep("selectImages");
  }

  /* ========= Step 3: image selection ========= */

  const filteredGalleryItems = useMemo(() => {
    let base = galleryItems;
    if (showSelectedOnly) {
      const setIds = new Set(selectedIds);
      base = galleryItems.filter((img) => setIds.has(img.id));
    }

    const q = filterText.trim().toLowerCase();
    if (!q) return base;

    return base.filter((d) =>
      [d.id, d.title, d.alt, d.description, d.story]
        .filter(Boolean)
        .some((v) => String(v).toLowerCase().includes(q))
    );
  }, [galleryItems, showSelectedOnly, selectedIds, filterText]);

  function toggleSelect(id) {
    setSelectedIds((prev) => {
      if (prev.includes(id)) {
        const next = prev.filter((x) => x !== id);
        setThemeImagesCount(next.length);
        return next;
      } else {
        const next = [...prev, id];
        setThemeImagesCount(next.length);
        return next;
      }
    });
  }

  function goToReorderStep() {
    if (!selectedIds.length) {
      if (!window.confirm("No images selected yet. Continue anyway?")) {
        return;
      }
    }

    // Build reorder array from selectedIds in current order:
    const mapById = new Map();
    galleryItems.forEach((it) => mapById.set(it.id, it));
    const ordered = selectedIds
      .map((id) => mapById.get(id))
      .filter(Boolean);

    setReorderItems(ordered);
    setStep("reorder");
  }

  /* ========= Step 4: reorder ========= */

  function moveReorder(fromIdx, toIdx) {
    setReorderItems((arr) => arrayMove(arr, fromIdx, toIdx));
  }

  /* ========= Backup handling ========= */

  function ensureBackup() {
    // Backup both: gallery dataset + themes.mjs (only .mjs files)
    const ts = new Date().toISOString().replace(/[:.]/g, "-");

    // 1) Gallery backup (if loaded)
    if (galleryFullData && galleryFullData.length) {
      const galleryName = themeDatasetPath
        ? prettyLabelFromPath(themeDatasetPath).replace(
            /[^a-zA-Z0-9-_]/g,
            "-"
          )
        : "unknown-gallery";
      downloadText(
        buildMjsJsonFromGallery(galleryFullData, "galleryData"),
        `THEME-BACKUP-${galleryName}-${ts}.mjs`
      );
    }

    // 2) Themes backup
    downloadText(
      buildThemesMjsJson(themes, "themes"),
      `THEME-BACKUP-themes-${ts}.mjs`
    );

    setBackupMade(true);
    note("Backup created, theme editing unlocked");
  }

  /* ========= Delete Theme ========= */

  async function handleDeleteTheme() {
    if (!selectedThemeSlug) {
      alert("No theme selected to delete.");
      return;
    }

    const themeToDelete = themes.find((t) => t.slug === selectedThemeSlug);
    if (!themeToDelete) {
      alert("Theme not found.");
      return;
    }

    const confirmMsg = `Are you sure you want to DELETE the theme "${themeToDelete.name}"?\n\nThis will:\n1. Remove the theme from themes.mjs\n2. Clean up theme references from images in the gallery file\n\nThis cannot be undone!`;
    
    if (!window.confirm(confirmMsg)) {
      return;
    }

    // Ensure backup before destructive operation
    if (!backupMade) {
      ensureBackup();
    }

    try {
      // 1) Remove theme from themes array
      const newThemes = themes.filter((t) => t.slug !== selectedThemeSlug);

      // 2) Clean theme references from gallery images
      const fullClone = JSON.parse(JSON.stringify(galleryFullData || []));
      const updatedGalleryArray = fullClone.map((item) => {
        if (!item || isGhost(item)) return item;
        
        if (item.themes && typeof item.themes === "object" && item.themes[selectedThemeSlug] != null) {
          const newThemes = { ...item.themes };
          delete newThemes[selectedThemeSlug];
          
          // Clean up themes object if empty
          const hasThemes = Object.keys(newThemes).length > 0;
          return {
            ...item,
            themes: hasThemes ? newThemes : undefined,
          };
        }
        return item;
      });

      // 3) Save updated themes.mjs
      const resThemes = await fetch("/.netlify/functions/updateThemes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          themeFilePath: THEME_FILE_PATH.replace(/^\//, ""),
          themesArray: newThemes,
        }),
      });
      if (!resThemes.ok) {
        throw new Error(await resThemes.text());
      }

      // 4) Save cleaned gallery data (if gallery was loaded)
      if (themeDatasetPath && galleryFullData.length) {
        const normalizedPath = themeDatasetPath.replace(/^\//, "");
        const finalGalleryPath = normalizedPath.startsWith("src/")
          ? normalizedPath
          : `src/${normalizedPath}`;

        const resGallery = await fetch("/.netlify/functions/updateGalleryOrder", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            datasetPath: finalGalleryPath,
            fullArray: updatedGalleryArray,
          }),
        });

        if (!resGallery.ok) {
          throw new Error(await resGallery.text());
        }
      }

      // 5) Update local state and reset
      setThemes(newThemes);
      note(`Theme "${themeToDelete.name}" deleted successfully`);
      
      // Reset to theme selection step
      setSelectedThemeSlug("");
      setThemeName("");
      setThemeSlug("");
      setThemeDescription("");
      setThemeVisible(true);
      setThemeDatasetPath("");
      setGalleryFullData([]);
      setGalleryItems([]);
      setSelectedIds([]);
      setReorderItems([]);
      setThemeImagesCount(0);
      setStep("selectTheme");

    } catch (err) {
      alert("Failed to delete theme: " + err.message);
      console.error("Delete theme error:", err);
    }
  }

  /* ========= Save Theme ========= */

  async function handleSaveTheme() {
    if (!backupMade && !skipBackupPrompt) {
      const ok = window.confirm(
        "You have not made a backup yet. Create backups now? (Cancel = I'll handle backups myself and continue.)"
      );
      if (ok) {
        ensureBackup();
      } else {
        setBackupMade(true);
      }
    }

    const slug = themeSlug || slugifyName(themeName);
    if (!themeName.trim()) {
      alert("Theme name is required.");
      return;
    }
    if (!slug) {
      alert("Theme slug could not be derived.");
      return;
    }
    if (!themeDatasetPath) {
      alert("Dataset is required.");
      return;
    }

    // 1) Build updated themes array with full theme data
    const existingIdx = themes.findIndex((t) => t.slug === slug);
    const existingTheme = existingIdx >= 0 ? themes[existingIdx] : null;
    const now = new Date().toISOString();

    // Theme object for themes.mjs (registry only - no images array)
    // Image membership is stored in gallery .mjs files via themes property
    const themeObj = {
      name: themeName,
      slug,
      dataset: themeDatasetPath.replace(/^\//, ""), // store without leading slash
      description: themeDescription,
      visible: themeVisible,
      imageCount: reorderItems.length, // track count for dropdown display
      firstImage: reorderItems[0]?.id || null, // first image ID for direct linking
      createdAt: existingTheme?.createdAt || now,
      updatedAt: now,
    };

    let newThemes;
    if (existingIdx >= 0) {
      newThemes = themes.slice();
      newThemes[existingIdx] = themeObj;
    } else {
      newThemes = [...themes, themeObj];
    }

    // 2) Build updated gallery dataset with themes[slug] indices
    // Copy full array deeply enough not to mutate original
    const fullClone = JSON.parse(JSON.stringify(galleryFullData || []));
    const selectedSet = new Set(selectedIds);

    // Build map id -> index from reorderItems
    const idxById = new Map();
    reorderItems.forEach((img, i) => {
      idxById.set(img.id, i);
    });

    const updatedGalleryArray = fullClone.map((item) => {
      if (!item || isGhost(item)) return item; // keep ghost as-is

      const isMember = selectedSet.has(item.id);
      const themeIndices = item.themes && typeof item.themes === "object"
        ? { ...item.themes }
        : {};

      if (isMember) {
        const idx = idxById.get(item.id) ?? 0;
        themeIndices[slug] = idx;
      } else {
        if (themeIndices[slug] != null) {
          delete themeIndices[slug];
        }
      }

      // Clean up themes object if empty
      const hasThemes = Object.keys(themeIndices).length > 0;

      return {
        ...item,
        themes: hasThemes ? themeIndices : undefined,
      };
    });

    // 3) Try saving themes + gallery via Netlify functions, fallback to download
    try {
      // Save themes.mjs (you'll implement this Netlify function)
      const resThemes = await fetch("/.netlify/functions/updateThemes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          themeFilePath: THEME_FILE_PATH.replace(/^\//, ""),
          themesArray: newThemes,
        }),
      });
      if (!resThemes.ok) {
        throw new Error(await resThemes.text());
      }

      // Save gallery dataset (reuse your existing function)
      const normalizedPath = themeDatasetPath.replace(/^\//, ""); // remove leading slash
      const finalGalleryPath = normalizedPath.startsWith("src/")
        ? normalizedPath
        : `src/${normalizedPath}`;

      const resGallery = await fetch(
        "/.netlify/functions/updateGalleryOrder",
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            datasetPath: finalGalleryPath,
            fullArray: updatedGalleryArray,
          }),
        }
      );

      if (!resGallery.ok) {
        throw new Error(await resGallery.text());
      }

      note("Theme + gallery updated on server");
      setThemes(newThemes);
      setGalleryFullData(updatedGalleryArray);
      setStep("done");
    } catch (err) {

      alert(
        "Server save failed. Falling back to download.\n\n" + err.message
      );

      // Fallback: download updated themes.mjs + gallery .mjs
      const ts = new Date().toISOString().replace(/[:.]/g, "-");

      // themes
      downloadText(
        buildThemesMjsJson(newThemes, "themes"),
        `themes-UPDATED-${ts}.mjs`
      );

      // gallery
      const galleryFilename =
        themeDatasetPath.split("/").pop() || "gallery.mjs";
      downloadText(
        buildMjsJsonFromGallery(updatedGalleryArray, "galleryData"),
        `UPDATED-${galleryFilename}`
      );

      setThemes(newThemes);
      setGalleryFullData(updatedGalleryArray);
      setStep("done");
    }
  }

  async function handleCommitRename() {
    if (!originalSlug) return;
    if (!themeSlug) return;

    const confirmMsg = `Rename theme:\n${originalSlug} → ${themeSlug}\n\n` +
      `This will:\n• Update slug in themes.mjs\n• Update all image theme references in the gallery.\n\nContinue?`;

    if (!window.confirm(confirmMsg)) return;

    const now = new Date().toISOString();

    // 1) Update the theme entry
    const newThemes = themes.map(t =>
      t.slug === originalSlug
        ? { ...t, slug: themeSlug, updatedAt: now }
        : t
    );

    // 2) Update gallery image memberships
    const updatedGallery = (galleryFullData || []).map(img => {
      if (!img || !img.themes) return img;

      if (img.themes[originalSlug] != null) {
        const newThemeObj = { ...img.themes };
        newThemeObj[themeSlug] = newThemeObj[originalSlug];
        delete newThemeObj[originalSlug];

        return {
          ...img,
          themes: newThemeObj
        };
      }
      return img;
    });

    // 3) SAVE the theme registry
    await fetch("/.netlify/functions/updateThemes", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        themeFilePath: THEME_FILE_PATH.replace(/^\//, ""),
        themesArray: newThemes
      })
    });

    // 4) SAVE the updated gallery
    const normalizedPath = themeDatasetPath.replace(/^\//, "");
    const finalGalleryPath = normalizedPath.startsWith("src/")
      ? normalizedPath : `src/${normalizedPath}`;

    await fetch("/.netlify/functions/updateGalleryOrder", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        datasetPath: finalGalleryPath,
        fullArray: updatedGallery
      })
    });

    // 5) Update UI state
    setThemes(newThemes);
    setGalleryFullData(updatedGallery);
    setOriginalSlug(themeSlug);
    setPendingRename(false);

    note(`Theme renamed to ${themeSlug}`);
  }

  /* ========= RENDER ========= */

  const themeLabel =
    themeName || selectedThemeSlug || "(Unnamed Theme)";
  const themeCount = themeImagesCount;

  // Controls are locked until user makes backup or skips - only on image selection step and beyond
  const controlsLocked = (step === "selectImages" || step === "reorder") && !backupMade && !skipBackupPrompt;

  return (
    <div
      className="p-6 max-w-7xl mx-auto text-sm"
      style={{
        fontFamily: "'Glegoo', serif",
        background: "#f5f3ef",
        minHeight: "100vh",
        color: "#2a1f17",
      }}
    >
      {/* Header */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          background: "#e4dae9",
          padding: "10px 20px",
          borderRadius: 8,
          marginBottom: 18,
          boxShadow: "0 2px 6px rgba(0,0,0,0.1)",
        }}
      >
        <div>
          <h1 style={{ fontSize: "1.6em", fontWeight: 700, margin: 0 }}>
            Theme Builder
          </h1>
          <div
            style={{
              fontSize: "0.9em",
              color: "#5a4a3a",
              marginTop: 4,
              fontWeight: 500,
              opacity: 0.8,
            }}
          >
            {step === "selectTheme"
              ? "Select or create a theme"
              : `Editing theme: ${themeLabel}`}
          </div>
        </div>

        {/* Backup gate + status indicator - only show on image selection step and beyond */}
        <div style={{ textAlign: "right" }}>
          {(step === "selectImages" || step === "reorder") && (
            <>
              <div className="flex items-center gap-3">
                {controlsLocked ? (
                  <span className="text-yellow-700 font-medium">🔒 Editing locked</span>
                ) : (
                  <span className="text-green-700 font-medium">✅ Editing unlocked</span>
                )}
              </div>
              <div className="mt-2 flex gap-2">
                {!backupMade && !skipBackupPrompt && (
                  <>
                    <button
                      onClick={ensureBackup}
                      className="px-3 py-1 rounded-md border bg-white hover:bg-gray-50"
                    >
                      1) Make Backups
                    </button>
                    <button
                      onClick={() => setSkipBackupPrompt(true)}
                      className="px-3 py-1 rounded-md border border-red-300 text-red-700 bg-white hover:bg-red-50"
                    >
                      Skip For Now
                    </button>
                  </>
                )}
              </div>
            </>
          )}
        </div>
      </div>

      {/* Status / last action */}
      {lastAction && (
        <div className="mb-3 text-xs bg-green-50 border border-green-200 text-green-800 px-2 py-1 rounded-md">
          {lastAction}
        </div>
      )}

      {/* Main content wrapper - grayed out when controls locked */}
      <div
        className={controlsLocked ? "pointer-events-none select-none opacity-40" : ""}
        aria-disabled={controlsLocked ? "true" : undefined}
      >

      {/* STEP 1: Theme selection */}
      {step === "selectTheme" && (
        <div className="space-y-4">
          <div>
            <label className="block mb-1 font-semibold">
              Existing Themes
            </label>
            <select
              className="border rounded-md px-2 py-1 min-w-[24rem]"
              disabled={!themesLoaded}
              onChange={(e) => {
                const v = e.target.value;
                if (!v) return;
                if (v === "__new__") {
                  handleCreateNewTheme();
                } else {
                  handleSelectExistingTheme(v);
                }
              }}
              defaultValue=""
            >
              <option value="">Select a theme…</option>
              <option value="__new__">➕ Create New Theme…</option>
              {themeOptions.map((t) => (
                <option key={t.slug} value={t.slug}>
                  {t.visible === false ? "🔒 " : ""}{t.name} ({t.imageCount ?? 0} images)
                </option>
              ))}
            </select>
          </div>

          <div className="text-xs opacity-70">
            Choose an existing theme to edit, or create a new one. You
            can reuse any gallery dataset and rebuild membership at any
            time.
          </div>
        </div>
      )}

      {/* STEP 2: Metadata */}
      {step === "metadata" && (
        <div className="space-y-4">
          <div className="flex gap-4">
            <div className="flex-1">
              <label className="block mb-1 font-semibold">
                Theme Name
              </label>
              <input
                type="text"
                className="w-full border rounded-md px-2 py-1"
                value={themeName}
                onChange={(e) => {
                  const newName = e.target.value;
                  setThemeName(newName);

                  // auto-slugify
                  const newSlug = slugifyName(newName);
                  setThemeSlug(newSlug);

                  // SHOW rename banner only if slug changed vs original
                  if (originalSlug && newSlug !== originalSlug) {
                    setPendingRename(true);
                  } else {
                    setPendingRename(false);
                  }
                }}
                placeholder="e.g., Black Hats"
              />
            </div>
            <div className="w-64">
              <label className="block mb-1 font-semibold">
                Slug
              </label>
              <input
                type="text"
                className="w-full border rounded-md px-2 py-1 text-xs"
                value={themeSlug}
                onChange={(e) => setThemeSlug(e.target.value)}
                placeholder="auto-generated-from-name"
              />
            </div>
          </div>

          {pendingRename && originalSlug && (
            <div style={{
              background: "#fff5d1",
              border: "1px solid #e6c76c",
              padding: "10px 14px",
              borderRadius: "6px",
              marginTop: "10px",
              fontSize: "0.9em"
            }}>
              <div><strong>Theme rename detected</strong></div>
              <div style={{ margin: "4px 0 8px" }}>
                {originalSlug} → <strong>{themeSlug}</strong>
              </div>

              <button
                onClick={handleCommitRename}
                style={{
                  padding: "4px 10px",
                  marginRight: "10px",
                  borderRadius: "4px",
                  border: "1px solid #c89a2c",
                  background: "#ffe8a3",
                  cursor: "pointer"
                }}
              >
                Rename Now
              </button>

              <button
                onClick={() => {
                  // cancel rename
                  const t = themes.find(t => t.slug === originalSlug);
                  if (t) {
                    setThemeName(t.name);
                    setThemeSlug(t.slug);
                  }
                  setPendingRename(false);
                }}
                style={{
                  padding: "4px 10px",
                  borderRadius: "4px",
                  border: "1px solid #aaa",
                  background: "#eee",
                  cursor: "pointer"
                }}
              >
                Cancel
              </button>
            </div>
          )}

          <div>
            <label className="block mb-1 font-semibold">
              SEO Description
            </label>
            <textarea
              className="w-full border rounded-md px-2 py-1 min-h-[100px]"
              value={themeDescription}
              onChange={(e) => setThemeDescription(e.target.value)}
              placeholder="Rich, story-driven description used for theme hover and DOM content…"
            />
          </div>

          <div className="flex gap-4 items-center">
            <div className="flex-1">
              <label className="block mb-1 font-semibold">
                Dataset / Gallery
              </label>
              <select
                className="w-full border rounded-md px-2 py-1"
                value={themeDatasetPath}
                onChange={(e) =>
                  setThemeDatasetPath(normalizePath(e.target.value))
                }
              >
                <option value="">Select a gallery dataset…</option>
                {datasetOptions.map((opt) => (
                  <option key={opt.path} value={opt.path}>
                    {opt.label}
                  </option>
                ))}
              </select>
            </div>
            <div className="w-48 text-sm">
              <div className="font-semibold mb-1">
                Images in this Theme
              </div>
              <div className="text-2xl">{themeCount}</div>
            </div>
          </div>

          {/* Visibility Toggle & Delete */}
          <div className="flex gap-4 items-center mt-4 p-3 bg-gray-50 rounded-md border">
            <div className="flex items-center gap-2 flex-1">
              <label className="font-semibold">Visibility:</label>
              <button
                onClick={() => setThemeVisible(!themeVisible)}
                className={`px-3 py-1 rounded-md border text-sm font-medium transition-colors ${
                  themeVisible 
                    ? "bg-green-100 border-green-300 text-green-800" 
                    : "bg-gray-200 border-gray-300 text-gray-600"
                }`}
              >
                {themeVisible ? "✓ Visible" : "○ Hidden"}
              </button>
              <span className="text-xs text-gray-500 ml-2">
                {themeVisible 
                  ? "Theme will appear in dropdowns/buttons" 
                  : "Theme is hidden from public display"}
              </span>
            </div>
            
            {/* Delete button - only show for existing themes */}
            {selectedThemeSlug && (
              <button
                onClick={handleDeleteTheme}
                className="px-3 py-1 rounded-md border border-red-300 bg-red-50 text-red-700 hover:bg-red-100 text-sm font-medium"
              >
                🗑️ Delete Theme
              </button>
            )}
          </div>

          <div className="flex justify-between mt-4">
            <button
              onClick={() => setStep("selectTheme")}
              className="px-3 py-1 rounded-md border"
            >
              ← Back
            </button>
            <button
              onClick={handleMetadataNext}
              className="px-3 py-1 rounded-md border bg-blue-50 hover:bg-blue-100"
            >
              Select Images →
            </button>
          </div>
        </div>
      )}

      {/* STEP 3: Select Images */}
      {step === "selectImages" && (
        <div className="space-y-4">
          <div className="flex items-center justify-between mb-2">
            <div>
              <div className="font-semibold">
                Select Images for Theme: {themeLabel}
              </div>
              <div className="text-xs opacity-70">
                Selected: {selectedIds.length} images
              </div>
              <div className="text-xs opacity-70">
                Dataset:{" "}
                {themeDatasetPath ? prettyLabelFromPath(themeDatasetPath) : "—"}
              </div>
            </div>

            <div className="flex items-center gap-2">
              <button
                className={`px-2 py-1 border rounded-md text-xs ${
                  !showSelectedOnly ? "bg-gray-200" : "bg-white"
                }`}
                onClick={() => setShowSelectedOnly(false)}
              >
                Show All
              </button>
              <button
                className={`px-2 py-1 border rounded-md text-xs ${
                  showSelectedOnly ? "bg-gray-200" : "bg-white"
                }`}
                onClick={() => setShowSelectedOnly(true)}
              >
                Show Selected
              </button>
              <input
                value={filterText}
                onChange={(e) => setFilterText(e.target.value)}
                placeholder="Search id/title/text…"
                className="w-72 border rounded-md px-2 py-1 text-xs"
              />
              <div className="flex items-center gap-2 border rounded-md px-2 py-1">
                <span className="opacity-70 text-xs">Thumb</span>
                <input
                  type="range"
                  min={90}
                  max={320}
                  value={thumb}
                  onChange={(e) => setThumb(Number(e.target.value))}
                />
              </div>
            </div>
          </div>

          <div
            style={{
              display: "grid",
              gap: "0.75rem",
              gridTemplateColumns: `repeat(auto-fill, minmax(${thumb}px, 1fr))`,
            }}
          >
            {filteredGalleryItems.map((it) => {
              const img = pickImage(it);
              const selected = selectedIds.includes(it.id);
              const hasSelections = selectedIds.length > 0;
              // Fade unselected images only when there ARE selections
              const isFaded = hasSelections && !selected;
              return (
                <div
                  key={it.id}
                  className={`relative border rounded-md bg-white overflow-hidden shadow-sm cursor-pointer transition-opacity duration-150 ${
                    selected ? "ring-2 ring-green-500 ring-offset-1" : ""
                  }`}
                  style={{
                    opacity: isFaded ? 0.6 : 1,
                  }}
                  onClick={() => toggleSelect(it.id)}
                  title={it.id}
                >
                  {img ? (
                    <img
                      src={img}
                      alt=""
                      className="block w-full"
                      style={{ height: thumb, objectFit: "cover" }}
                    />
                  ) : (
                    <div
                      className="w-full grid place-items-center text-xs"
                      style={{ height: thumb }}
                    >
                      No image
                    </div>
                  )}
                  {/* Selection indicator badge */}
                  {selected && (
                    <div className="absolute top-2 right-2 w-6 h-6 rounded-full bg-green-500 text-white flex items-center justify-center text-sm font-bold shadow-md">
                      ✓
                    </div>
                  )}
                  <div className="absolute bottom-0 left-0 right-0 text-[10px] px-1 py-0.5 bg-black/50 text-white flex justify-between">
                    <span className="truncate">{it.id}</span>
                    {selected && <span>Selected</span>}
                  </div>
                </div>
              );
            })}
          </div>

          <div className="flex justify-between mt-4">
            <button
              onClick={() => setStep("metadata")}
              className="px-3 py-1 rounded-md border"
            >
              ← Back
            </button>
            <button
              onClick={goToReorderStep}
              className="px-3 py-1 rounded-md border bg-blue-50 hover:bg-blue-100"
            >
              Reorder Images →
            </button>
          </div>
        </div>
      )}

      {/* STEP 4: Reorder */}
      {step === "reorder" && (
        <div className="space-y-4">
          <div className="flex items-center justify-between mb-2">
            <div>
              <div className="font-semibold">
                Reorder Images in Theme: {themeLabel}
              </div>
              <div className="text-xs opacity-70">
                Total: {reorderItems.length} images
              </div>
            </div>
          </div>

          <div
            style={{
              display: "grid",
              gap: "0.75rem",
              gridTemplateColumns: `repeat(auto-fill, minmax(${thumb}px, 1fr))`,
            }}
          >
            {reorderItems.map((it, idx) => {
              const img = pickImage(it);
              return (
                <div
                  key={it.id}
                  draggable
                  onDragStart={(e) => {
                    e.dataTransfer.effectAllowed = "move";
                    e.dataTransfer.setData("text/plain", String(idx));
                  }}
                  onDragOver={(e) => e.preventDefault()}
                  onDrop={(e) => {
                    e.preventDefault();
                    const from = Number(
                      e.dataTransfer.getData("text/plain")
                    );
                    const to = idx;
                    if (!Number.isNaN(from)) {
                      moveReorder(from, to);
                    }
                  }}
                  className="relative border rounded-md bg-white overflow-hidden shadow-sm cursor-move"
                  title={`#${idx + 1} – ${it.id}`}
                >
                  {img ? (
                    <img
                      src={img}
                      alt=""
                      className="block w-full"
                      style={{ height: thumb, objectFit: "cover" }}
                    />
                  ) : (
                    <div
                      className="w-full grid place-items-center text-xs"
                      style={{ height: thumb }}
                    >
                      No image
                    </div>
                  )}
                  <div className="absolute top-1 left-1 text-[11px] px-1.5 py-[1px] rounded bg-black/60 text-white">
                    #{idx + 1}
                  </div>
                  <div className="absolute bottom-0 left-0 right-0 text-[10px] px-1 py-0.5 bg-black/50 text-white truncate">
                    {it.id}
                  </div>
                </div>
              );
            })}
          </div>

          <div className="flex justify-between mt-4">
            <button
              onClick={() => setStep("selectImages")}
              className="px-3 py-1 rounded-md border"
            >
              ← Back
            </button>
            <button
              onClick={handleSaveTheme}
              className="px-3 py-1 rounded-md border bg-green-50 hover:bg-green-100"
            >
              💾 Save Theme
            </button>
          </div>
        </div>
      )}

      {/* STEP 5: Done */}
      {step === "done" && (
        <div className="space-y-4">
          <div className="text-lg font-semibold text-green-700">
            Theme saved successfully.
          </div>
          <div className="text-sm">
            <div>
              <strong>Theme:</strong> {themeLabel}
            </div>
            <div>
              <strong>Images:</strong> {themeCount}
            </div>
            <div>
              <strong>Dataset:</strong>{" "}
              {themeDatasetPath
                ? prettyLabelFromPath(themeDatasetPath)
                : "—"}
            </div>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => setStep("selectTheme")}
              className="px-3 py-1 rounded-md border"
            >
              Back to Theme List
            </button>
            <button
              onClick={() => setStep("metadata")}
              className="px-3 py-1 rounded-md border bg-blue-50 hover:bg-blue-100"
            >
              Edit Again
            </button>
          </div>
        </div>
      )}

      </div>
      {/* End of controlsLocked wrapper */}

      <div className="mt-6 text-xs opacity-70">
        ThemeBuilder writes theme membership into each image&apos;s{" "}
        <code>themes</code> object and stores theme metadata in{" "}
        <code>themes.mjs</code>. Use your existing Netlify functions for
        server writes, with downloaded <code>.mjs</code> backups as a
        fallback.
      </div>
    </div>
  );
}
