// src/components/VideoBakerEditor.jsx
import { useEffect, useMemo, useRef, useState } from "react";
import PanZoomStageEditor from "./PanZoomStageEditor.jsx";
import IntroOutroEditor from "./IntroOutroEditor.jsx";
import StageReviewer from "./StageReviewer.jsx";
// import StoryShowBaker from "./Gallery-Slideshow-StoryBaker.jsx";

/* ----------------------------- Helpers ------------------------------ */
function downloadText(text, filename) {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function serializeJS(value) {
  return JSON.stringify(value, null, 2);
}

function buildMjs({ storyMeta, storyData }) {
  const metaJS = serializeJS(storyMeta);
  const dataJS = serializeJS(storyData);
  return `// Auto-generated by VideoBaker – review & commit
export const storyMeta = ${metaJS};
export const storyData = ${dataJS};
`;
}

function arrayMove(arr, from, to) {
  if (from === to) return arr;
  const copy = arr.slice();
  const item = copy.splice(from, 1)[0];
  copy.splice(to, 0, item);
  return copy;
}

const MIN_STAGE_DURATION = 0.5;
const DEFAULT_STAGE_DURATION = 2;
const DEFAULT_BURN_RATE = 20;
const DEFAULT_PAUSE_DURATION = 2;
const MIN_TOTAL_DURATION = MIN_STAGE_DURATION * 3;

const formatSeconds = (value) => {
  const num = Number(value);
  if (!Number.isFinite(num)) return "";
  return Number(num.toFixed(2)).toString();
};

const normalizeDuration = (value, fallback = DEFAULT_STAGE_DURATION) => {
  const fallbackNum = Number.isFinite(Number(fallback)) ? Number(fallback) : DEFAULT_STAGE_DURATION;
  const safeFallback = Math.max(MIN_STAGE_DURATION, fallbackNum);
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return safeFallback;
  return Math.max(MIN_STAGE_DURATION, parsed);
};

const normalizePause = (value, fallback = DEFAULT_PAUSE_DURATION) => {
  const parsed = Number(value);
  const fallbackNum = Number.isFinite(Number(fallback)) ? Number(fallback) : DEFAULT_PAUSE_DURATION;
  if (!Number.isFinite(parsed)) return Math.max(0, fallbackNum);
  return Math.max(0, parsed);
};

function applyBurnRateToPanZoom(panZoom, totalSeconds, pauseSeconds) {
  if (!panZoom || !totalSeconds) return panZoom;
  const clampedTotal = Math.max(MIN_TOTAL_DURATION, Number(totalSeconds) || DEFAULT_BURN_RATE);
  const safePause = normalizePause(pauseSeconds, DEFAULT_PAUSE_DURATION);

  const startDuration = normalizeDuration(panZoom.start?.duration, DEFAULT_STAGE_DURATION);
  const midDuration = normalizeDuration(panZoom.mid?.duration, DEFAULT_STAGE_DURATION);
  const endDuration = normalizeDuration(panZoom.end?.duration, DEFAULT_STAGE_DURATION);

  const baseDurations = [startDuration, midDuration, endDuration];
  const baseSum = baseDurations.reduce((acc, val) => acc + val, 0) || DEFAULT_STAGE_DURATION * 3;
  const ratios = baseDurations.map((duration) => (baseSum > 0 ? duration / baseSum : 1 / baseDurations.length));

  const adjustedDurations = ratios.map((ratio) => Math.max(MIN_STAGE_DURATION, clampedTotal * ratio));
  let diff = clampedTotal - adjustedDurations.reduce((acc, val) => acc + val, 0);

  for (let i = adjustedDurations.length - 1; i >= 0 && Math.abs(diff) > 1e-6; i -= 1) {
    if (diff > 0) {
      adjustedDurations[i] += diff;
      diff = 0;
    } else {
      const available = adjustedDurations[i] - MIN_STAGE_DURATION;
      if (available <= 0) continue;
      const reduction = Math.min(available, -diff);
      adjustedDurations[i] -= reduction;
      diff += reduction;
    }
  }

  return {
    ...panZoom,
    pauseDuration: safePause,
    start: panZoom.start
      ? { ...panZoom.start, duration: adjustedDurations[0] }
      : { duration: adjustedDurations[0] },
    mid: panZoom.mid
      ? { ...panZoom.mid, duration: adjustedDurations[1] }
      : { duration: adjustedDurations[1] },
    end: panZoom.end
      ? { ...panZoom.end, duration: adjustedDurations[2] }
      : { duration: adjustedDurations[2] },
  };
}

const INTRO_SLIDE_IDS = new Set(["i-k4video-intro"]);
const OUTRO_SLIDE_IDS = new Set(["i-k4video-outro"]);

function isVideoIntroSlide(slide) {
  return !!slide && (INTRO_SLIDE_IDS.has(slide.id) || slide._isIntro === true);
}

function isVideoOutroSlide(slide) {
  return !!slide && (OUTRO_SLIDE_IDS.has(slide.id) || slide._isOutro === true);
}

function isVideoPaddingSlide(slide) {
  return isVideoIntroSlide(slide) || isVideoOutroSlide(slide);
}

/* ----------------------------- Aspect presets ------------------------------ */
const ASPECT_PRESETS = [
  { id: "16:9", label: "16:9 — YouTube / Facebook", ratio: 16 / 9, width: 1920, height: 1080 },
  { id: "9:16", label: "9:16 — Reels / TikTok / Shorts", ratio: 9 / 16, width: 1080, height: 1920 },
  { id: "4:5", label: "4:5 — Instagram Portrait", ratio: 4 / 5, width: 1080, height: 1350 },
  { id: "1:1", label: "1:1 — Square Post", ratio: 1, width: 1080, height: 1080 },
];

/* ----------------------------- Main Component ------------------------------ */
export default function VideoBakerEditor() {
  const modules = useMemo(
    () => import.meta.glob("/src/data/Other/Stories/*.mjs", { eager: false }),
    []
  );

  const options = useMemo(() => {
    return Object.keys(modules)
      .sort((a, b) => a.localeCompare(b))
      .map((path) => {
        const name = path.split("/").pop().replace(".mjs", "");
        const label = name.replace(/[-_]/g, " ").replace(/\b\w/g, (m) => m.toUpperCase());
        return { key: path, label };
      });
  }, [modules]);

  const [selectedPath, setSelectedPath] = useState("");
  const [storyMeta, setStoryMeta] = useState(null);
  const [slides, setSlides] = useState([]);
  const [rawSlides, setRawSlides] = useState([]);
  const [dirty, setDirty] = useState(false);
  const [status, setStatus] = useState("");
  const [editingSlide, setEditingSlide] = useState(null);
  const [showIntro, setShowIntro] = useState(false);
  const [showOutro, setShowOutro] = useState(false);
  const [introPanZoom, setIntroPanZoom] = useState(null);
  const [outroPanZoom, setOutroPanZoom] = useState(null);
  const [panZoomCache, setPanZoomCache] = useState({});
  const [introSlideData, setIntroSlideData] = useState(null);
  const [outroSlideData, setOutroSlideData] = useState(null);
  const [burnRateSeconds, setBurnRateSeconds] = useState(DEFAULT_BURN_RATE);
  const [burnPauseSeconds, setBurnPauseSeconds] = useState(DEFAULT_PAUSE_DURATION);
  const [burnRateInput, setBurnRateInput] = useState(formatSeconds(DEFAULT_BURN_RATE));
  const [burnPauseInput, setBurnPauseInput] = useState(formatSeconds(DEFAULT_PAUSE_DURATION));
  const [showPreview, setShowPreview] = useState(false);
  const previewAudioRef = useRef(null);
  const previewAmbientAudioRef = useRef(null);
  const [previewMuted, setPreviewMuted] = useState(false);
  const [previewVolume, setPreviewVolume] = useState(0.7);
  const [previewSpeaking, setPreviewSpeaking] = useState(false);
  const loaded = !!storyMeta;

  // DnD
  const dragFromIndex = useRef(null);

  // Aspect selection
  const [aspectChoice, setAspectChoice] = useState(null);
  const [showAspectPicker, setShowAspectPicker] = useState(false);

  // Restore last chosen aspect
  useEffect(() => {
    const saved = localStorage.getItem("vb_aspectChoice");
    if (saved) {
      try {
        setAspectChoice(JSON.parse(saved));
      } catch {}
    }
  }, []);

  useEffect(() => {
    if (aspectChoice) {
      localStorage.setItem("vb_aspectChoice", JSON.stringify(aspectChoice));
    }
  }, [aspectChoice]);

  useEffect(() => {
    if (showPreview) return;
    if (previewAudioRef.current) {
      try {
        previewAudioRef.current.pause();
        previewAudioRef.current.currentTime = 0;
      } catch {}
    }
    if (previewAmbientAudioRef.current) {
      try {
        previewAmbientAudioRef.current.pause();
        previewAmbientAudioRef.current.currentTime = 0;
      } catch {}
    }
    setPreviewSpeaking(false);
  }, [showPreview]);

  const currentAspect = aspectChoice || ASPECT_PRESETS[0]; // default 16:9 if none

  const previewSlides = useMemo(() => {
    if (!loaded) return [];

    const applyForPreview = (id, panZoom) => {
      if (!panZoom) return panZoom;
      if (isVideoPaddingSlide({ id })) return panZoom;
      return applyBurnRateToPanZoom(panZoom, burnRateSeconds, burnPauseSeconds);
    };

    const introMeta = storyMeta?.introMeta || {};
    const introFallback = {
      id: "i-k4video-intro",
      title: "Intro Slide",
      story:
        introMeta.introText ||
        "K4 Studios presents the Fine Art Photography of Wayne Heim.",
      description: "Intro placeholder for video sequencing",
      srcXL: "/images/K4-Stories-logo1b.webp",
      gallery: "Other/Stories",
      rating: 0,
      _isIntro: true,
      opening:
        introMeta.introText ||
        "K4 Studios presents the Fine Art Photography of Wayne Heim.",
      tagline: introMeta.tagline || "Embrace the Past... Live the Story.",
      showTitle: introMeta.showTitle || storyMeta?.showTitle || "K4 Studios Picture Show",
    };
    const introPanZoomSource =
      introPanZoom ||
      panZoomCache["i-k4video-intro"] ||
      introSlideData?.panZoom ||
      storyMeta?.introPanZoom ||
      null;
    const introOpening =
      introMeta.introText ||
      introSlideData?.opening ||
      introSlideData?.story ||
      introFallback.story;
    const introTitleValue =
      introMeta.showTitle ||
      introSlideData?.showTitle ||
      introSlideData?.title ||
      storyMeta?.showTitle ||
      introFallback.title;
    const introTaglineValue =
      introMeta.tagline || introSlideData?.tagline || "Embrace the Past... Live the Story.";

    const introSlide = {
      ...(introSlideData ? { ...introSlideData } : introFallback),
      id: "i-k4video-intro",
      _isIntro: true,
      opening: introOpening,
      showTitle: introTitleValue,
      title: introTitleValue,
      tagline: introTaglineValue,
      story: introOpening,
      panZoom: introPanZoomSource ? { ...introPanZoomSource } : null,
      introMeta: introMeta,
    };

    const outroMeta = storyMeta?.outroMeta || {};
    const outroFallback = {
      id: "i-k4video-outro",
      title: "Outro Slide",
      story:
        outroMeta.closingText ||
        "Every image is another notch in the belt, keeping history alive.",
      description: "Outro placeholder for video sequencing",
      srcXL: "/images/K4-Stories-logo1b.webp",
      gallery: "Other/Stories",
      rating: 0,
      _isOutro: true,
      closing:
        outroMeta.closingText ||
        "Every image is another notch in the belt, keeping history alive.",
      cta: outroMeta.cta || "Visit k4studios.com to explore more Picture Shows.",
      url:
        outroMeta.displayUrl ||
        `https://www.k4studios.com/pictureshow/${(storyMeta?.showTitle || "unknown")
          .toLowerCase()
          .replace(/\s+/g, "-")}`,
    };
    const outroPanZoomSource =
      outroPanZoom ||
      panZoomCache["i-k4video-outro"] ||
      outroSlideData?.panZoom ||
      storyMeta?.outroPanZoom ||
      null;
    const outroClosingValue =
      outroMeta.closingText ||
      outroSlideData?.closing ||
      outroSlideData?.story ||
      outroFallback.story;
    const outroCtaValue =
      outroMeta.cta || outroSlideData?.cta || "Visit k4studios.com to explore more Picture Shows.";
    const outroUrlValue =
      outroSlideData?.url ||
      outroMeta.displayUrl ||
      outroFallback.url ||
      `https://www.k4studios.com/pictureshow/${(storyMeta?.showTitle || "unknown")
        .toLowerCase()
        .replace(/\s+/g, "-")}`;

    const outroSlide = {
      ...(outroSlideData ? { ...outroSlideData } : outroFallback),
      id: "i-k4video-outro",
      _isOutro: true,
      closing: outroClosingValue,
      cta: outroCtaValue,
      url: outroUrlValue,
      story: outroClosingValue,
      panZoom: outroPanZoomSource ? { ...outroPanZoomSource } : null,
      outroMeta: outroMeta,
    };

    const bodySlides = slides.map((slide) => {
      if (!slide) return slide;
      const cachedPanZoom = panZoomCache[slide.id];
      const panZoom = cachedPanZoom || slide.panZoom;
      return panZoom
        ? { ...slide, panZoom: applyForPreview(slide.id, panZoom) }
        : { ...slide };
    });

    return [introSlide, ...bodySlides, outroSlide];
  }, [
    loaded,
    slides,
    panZoomCache,
    burnRateSeconds,
    burnPauseSeconds,
    introPanZoom,
    outroPanZoom,
    storyMeta,
  ]);

  const previewStartId = previewSlides.length > 0 ? previewSlides[0].id : null;

  const handleIntroPanZoom = () => {
    if (!storyMeta) return;
    const introMeta = storyMeta.introMeta || {};
    setEditingSlide({
      id: "__INTRO__",
      type: "intro",
      opening:
        introMeta.introText ||
        "K4 Studios presents the Fine Art Photography of Wayne Heim.",
      title:
        introMeta.showTitle || storyMeta.showTitle || "K4 Studios Picture Show",
      tagline: introMeta.tagline || "Embrace the Past. Live the Story.",
      panZoom:
        introPanZoom || panZoomCache["i-k4video-intro"] || storyMeta.introPanZoom,
      // Pass intro metadata so PanZoomStageEditor can gray out unused stages
      introMeta: introMeta,
    });
  };

  const handleOutroPanZoom = () => {
    if (!storyMeta) return;
    const outroMeta = storyMeta.outroMeta || {};
    const computedUrl =
      outroMeta.displayUrl ||
      `https://www.k4studios.com/pictureshow/${(storyMeta?.showTitle || "unknown")
        .toLowerCase()
        .replace(/\s+/g, "-")}`;
    setEditingSlide({
      id: "__OUTRO__",
      type: "outro",
      closing:
        outroMeta.closingText ||
        "Every image is another notch in the belt, keeping history alive.",
      cta: outroMeta.cta || "Visit k4studios.com to explore more Picture Shows.",
      url: computedUrl,
      panZoom:
        outroPanZoom || panZoomCache["i-k4video-outro"] || storyMeta.outroPanZoom,
      // Pass outro metadata so PanZoomStageEditor can gray out unused stages
      outroMeta: outroMeta,
    });
  };

  /* ----------------------------- Load selected show ------------------------------ */
  useEffect(() => {
    async function loadShow() {
      setStoryMeta(null);
      setSlides([]);
      setRawSlides([]);
      setPanZoomCache({});
      setIntroPanZoom(null);
      setOutroPanZoom(null);
  setIntroSlideData(null);
  setOutroSlideData(null);
      setDirty(false);
      if (!selectedPath) return;
      setStatus("Loading…");
      try {
        const mod = await modules[selectedPath]();
        let meta = mod?.storyMeta ?? null;
        let data = mod?.storyData ?? null;

        if (!meta) {
          const firstObj =
            (mod && typeof mod === "object" && Object.values(mod).find((v) => v?.showTitle)) || null;
          if (firstObj) meta = firstObj;
        }
        if (!data) {
          const firstArray =
            (mod && typeof mod === "object" && Object.values(mod).find((v) => Array.isArray(v))) ||
            null;
        if (Array.isArray(firstArray)) data = firstArray;
        }

        const dataArray = Array.isArray(data) ? data : [];
        const introFromData = dataArray.find(isVideoIntroSlide) || null;
        const outroFromData = dataArray.find(isVideoOutroSlide) || null;
        const baseSlides = dataArray.filter((s) => !isVideoPaddingSlide(s));

        const filtered = baseSlides.filter((s) => {
          if (!s) return false;
          if (s.id === "i-k4studios") return false;
          if (s.visibility === "ghost") return false;
          const t = (s.title || "").toLowerCase();
          if (t.startsWith("prologue")) return false;
          return true;
        });

        const metaBurnRate = Number(meta?.burnRateSeconds);
        const metaPause = Number(meta?.burnPauseSeconds);
        const resolvedBurnRate = Number.isFinite(metaBurnRate) ? metaBurnRate : DEFAULT_BURN_RATE;
        const resolvedPause = Number.isFinite(metaPause) ? metaPause : DEFAULT_PAUSE_DURATION;

        const ensurePanZoomDefaults = (panZoom) => {
          if (!panZoom) return panZoom;
          return applyBurnRateToPanZoom(panZoom, resolvedBurnRate, resolvedPause);
        };

        const cache = {};
        dataArray.forEach((s) => {
          if (s?.id && s.panZoom) {
            cache[s.id] = isVideoPaddingSlide(s)
              ? { ...s.panZoom }
              : ensurePanZoomDefaults(s.panZoom);
          }
        });

        setBurnRateSeconds(resolvedBurnRate);
        setBurnPauseSeconds(resolvedPause);
        setBurnRateInput(formatSeconds(resolvedBurnRate));
        setBurnPauseInput(formatSeconds(resolvedPause));

        const metaWithDefaults = {
          ...(meta || {}),
          burnRateSeconds: resolvedBurnRate,
          burnPauseSeconds: resolvedPause,
        };

        const shouldPreviewMute =
          typeof metaWithDefaults.globalAudioMode === "string" &&
          metaWithDefaults.globalAudioMode.toLowerCase() === "mute";

        setPreviewMuted(shouldPreviewMute);

        setStoryMeta(metaWithDefaults);
        setRawSlides(baseSlides.map((slide) =>
          slide?.panZoom && !isVideoPaddingSlide(slide)
            ? { ...slide, panZoom: ensurePanZoomDefaults(slide.panZoom) }
            : slide
        ));
        setSlides(filtered.map((slide) =>
          slide?.panZoom
            ? { ...slide, panZoom: ensurePanZoomDefaults(slide.panZoom) }
            : slide
        ));
        setPanZoomCache(cache);
        setIntroPanZoom(
          meta?.introPanZoom || introFromData?.panZoom || cache["i-k4video-intro"] || null
        );
        setOutroPanZoom(
          meta?.outroPanZoom || outroFromData?.panZoom || cache["i-k4video-outro"] || null
        );
        setIntroSlideData(introFromData ? { ...introFromData } : null);
        setOutroSlideData(outroFromData ? { ...outroFromData } : null);
        setDirty(false);
        setStatus(`Loaded ${filtered.length} slides`);

        // After a show is chosen, if no aspect set yet, prompt once.
        if (!aspectChoice) {
          setShowAspectPicker(true);
        }
      } catch (err) {
        console.error("❌ [VideoBaker] Load failed:", err);
        setStatus("Load failed");
      }
    }
    loadShow();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedPath, modules]);

  /* ----------------------------- Save .mjs ------------------------------ */
    async function saveAsMjs() {
      if (!storyMeta) return;

      const timestamp = new Date().toISOString();
      const metaForSave = {
        ...(storyMeta || {}),
        burnRateSeconds,
        burnPauseSeconds,
        savedAt: timestamp,
        introPanZoom: introPanZoom || storyMeta.introPanZoom || null,
        outroPanZoom: outroPanZoom || storyMeta.outroPanZoom || null,
      };

      const byId = new Map(slides.map((s) => [s.id, s]));
      const mergedData = rawSlides.map((s) => (byId.has(s.id) ? byId.get(s.id) : s));

      const introSlide = {
        id: "i-k4video-intro",
        title: "Intro Slide",
        story:
          metaForSave.introMeta?.introText ||
          "K4 Studios presents the Fine Art Photography of Wayne Heim.",
        description: "Intro placeholder for video sequencing",
        srcXL: "/images/K4-Stories-logo1b.webp",
        gallery: "Other/Stories",
        rating: 0,
        _isIntro: true,
        opening:
          metaForSave.introMeta?.introText ||
          "K4 Studios presents the Fine Art Photography of Wayne Heim.",
        showTitle: metaForSave.introMeta?.showTitle || metaForSave?.showTitle || "K4 Studios Picture Show",
        tagline: metaForSave.introMeta?.tagline || "Embrace the Past... Live the Story.",
        panZoom: metaForSave.introPanZoom,
      };

      const outroSlide = {
        id: "i-k4video-outro",
        title: "Outro Slide",
        story:
          metaForSave.outroMeta?.closingText ||
          "Every image is another notch in the belt, keeping history alive.",
        description: "Outro placeholder for video sequencing",
        srcXL: "/images/K4-Stories-logo1b.webp",
        gallery: "Other/Stories",
        rating: 0,
        _isOutro: true,
        closing:
          metaForSave.outroMeta?.closingText ||
          "Every image is another notch in the belt, keeping history alive.",
        cta: metaForSave.outroMeta?.cta || "Visit k4studios.com to explore more Picture Shows.",
        url:
          metaForSave.outroMeta?.displayUrl ||
          `https://www.k4studios.com/pictureshow/${(metaForSave?.showTitle || "unknown")
            .toLowerCase()
            .replace(/\s+/g, "-")}`,
        panZoom: metaForSave.outroPanZoom,
      };

      const mergedWithoutPadding = mergedData.filter((s) => !isVideoPaddingSlide(s));
      const finalData = [...mergedWithoutPadding, introSlide, outroSlide];
      const mjs = buildMjs({ storyMeta: metaForSave, storyData: finalData });

      const selectedFilename = selectedPath.split("/").pop() || "ShowData.mjs";
      const fallbackFilename = selectedFilename.replace(/\.mjs$/i, "-baked.mjs");

      let saved = false;

      if (selectedPath) {
        try {
          setStatus("Saving…");
          const res = await fetch("/.netlify/functions/saveShowData", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ filename: selectedFilename, content: mjs }),
          });
          if (!res.ok) throw new Error(await res.text());
          setStatus(`Saved → ${selectedFilename}`);
          setStoryMeta(metaForSave);
          saved = true;
        } catch (err) {
          console.error("⚠️ VideoBaker save failed, falling back to download", err);
        }
      }

      if (!saved) {
        downloadText(mjs, fallbackFilename);
        setStatus(`Downloaded ${fallbackFilename} (save unavailable)`);
      }

      setDirty(!saved);
    }

  /* ----------------------------- Update slide pan/zoom ------------------------------ */
  function updatePanZoom(id, newPanZoom) {
    if (id === "__INTRO__") {
      setIntroPanZoom(newPanZoom);
      setStoryMeta((prev) => ({ ...(prev || {}), introPanZoom: newPanZoom }));
      setPanZoomCache((prev) => ({ ...prev, "i-k4video-intro": newPanZoom }));
      setIntroSlideData((prev) => (prev ? { ...prev, panZoom: newPanZoom } : prev));
      setRawSlides((prev) =>
        prev.map((s) =>
          s.id === "i-k4video-intro" ? { ...s, panZoom: { ...s.panZoom, ...newPanZoom } } : s
        )
      );
      setDirty(true);
      setStatus("Intro positions updated");
      return;
    }
    if (id === "__OUTRO__") {
      setOutroPanZoom(newPanZoom);
      setStoryMeta((prev) => ({ ...(prev || {}), outroPanZoom: newPanZoom }));
      setPanZoomCache((prev) => ({ ...prev, "i-k4video-outro": newPanZoom }));
      setOutroSlideData((prev) => (prev ? { ...prev, panZoom: newPanZoom } : prev));
      setRawSlides((prev) =>
        prev.map((s) =>
          s.id === "i-k4video-outro" ? { ...s, panZoom: { ...s.panZoom, ...newPanZoom } } : s
        )
      );
      setDirty(true);
      setStatus("Outro positions updated");
      return;
    }
    setSlides((prev) =>
      prev.map((s) => (s.id === id ? { ...s, panZoom: { ...s.panZoom, ...newPanZoom } } : s))
    );
    setRawSlides((prev) =>
      prev.map((s) => (s.id === id ? { ...s, panZoom: { ...s.panZoom, ...newPanZoom } } : s))
    );
    setPanZoomCache((prev) => ({ ...prev, [id]: newPanZoom }));
    setDirty(true);
  }

  /* ----------------------------- Drag logic ------------------------------ */
  function onDragStart(e, index) {
    dragFromIndex.current = index;
    e.dataTransfer.effectAllowed = "move";
  }

  function onDragOver(e) {
    e.preventDefault();
  }

  function onDrop(e, index) {
    e.preventDefault();
    const from = dragFromIndex.current;
    const to = index;
    dragFromIndex.current = null;
    if (from == null || to == null || from === to) return;
    setSlides((arr) => arrayMove(arr, from, to));
    setDirty(true);
    setStatus(`Reordered slide #${from + 1} → #${to + 1}`);
  }

  function applyBurnRateGlobally(totalCandidate, pauseCandidate) {
    const existingTotal = Number.isFinite(burnRateSeconds) ? burnRateSeconds : DEFAULT_BURN_RATE;
    const existingPause = Number.isFinite(burnPauseSeconds) ? burnPauseSeconds : DEFAULT_PAUSE_DURATION;

    const parseCandidate = (candidate) => {
      if (candidate == null) return Number.NaN;
      if (typeof candidate === "string") {
        const trimmed = candidate.trim();
        if (!trimmed) return Number.NaN;
        return Number(trimmed);
      }
      return Number(candidate);
    };

    const parsedTotal = parseCandidate(totalCandidate);
    const parsedPause = parseCandidate(pauseCandidate);

    const safeTotalCandidate = Number.isFinite(parsedTotal) ? parsedTotal : existingTotal;
    const safePauseCandidate = Number.isFinite(parsedPause) ? parsedPause : existingPause;

    const safeTotal = Math.max(MIN_TOTAL_DURATION, safeTotalCandidate);
    const safePause = normalizePause(safePauseCandidate, existingPause);

    const updateWithBurn = (panZoom) => applyBurnRateToPanZoom(panZoom, safeTotal, safePause);

    setBurnRateSeconds(safeTotal);
    setBurnPauseSeconds(safePause);
    setBurnRateInput(formatSeconds(safeTotal));
    setBurnPauseInput(formatSeconds(safePause));

    setSlides((prev) =>
      prev.map((slide) => {
        if (!slide?.panZoom) return slide;
        return { ...slide, panZoom: updateWithBurn(slide.panZoom) };
      })
    );

    setRawSlides((prev) =>
      prev.map((slide) => {
        if (!slide?.panZoom) return slide;
        return { ...slide, panZoom: updateWithBurn(slide.panZoom) };
      })
    );

    setPanZoomCache((prev) => {
      const source = prev || {};
      const next = { ...source };
      Object.entries(next).forEach(([id, panZoom]) => {
        if (!panZoom) return;
        if (INTRO_SLIDE_IDS.has(id) || OUTRO_SLIDE_IDS.has(id)) return;
        next[id] = updateWithBurn(panZoom);
      });
      return next;
    });

    setStoryMeta((prev) => ({
      ...(prev || {}),
      burnRateSeconds: safeTotal,
      burnPauseSeconds: safePause,
    }));

    setDirty(true);
    setStatus(`Burn rate ${formatSeconds(safeTotal)}s · pause ${formatSeconds(safePause)}s applied`);
  }

  const handleBurnRateApply = () => {
    applyBurnRateGlobally(burnRateInput, burnPauseInput);
  };

  const handleBurnRateKeyDown = (event) => {
    if (event.key === "Enter") {
      event.preventDefault();
      handleBurnRateApply();
    }
  };

  function handlePreviewExit() {
    if (previewAmbientAudioRef.current) {
      try {
        previewAmbientAudioRef.current.pause();
        previewAmbientAudioRef.current.currentTime = 0;
      } catch {}
    }
    if (previewAudioRef.current) {
      try {
        previewAudioRef.current.pause();
        previewAudioRef.current.currentTime = 0;
      } catch {}
    }
    setPreviewSpeaking(false);
    setShowPreview(false);
  }

  /* ----------------------------- Render ------------------------------ */
  return (
    <div className="p-6 max-w-[1200px] mx-auto text-sm" style={{ fontFamily: "'Glegoo', serif" }}>
      <h1 className="text-3xl font-semibold mb-2">K4 Pictureshow Video Baker</h1>
      <p className="opacity-70 mb-6">
        Load an existing show, reorder slides, choose an output format, and edit pan/zoom/rotation.
      </p>

      {/* Top controls */}
      <div className="flex flex-wrap items-center gap-3 mb-5">
        <select
          className="border rounded-md px-2 py-1 min-w-[22rem]"
          value={selectedPath}
          onChange={(e) => setSelectedPath(e.target.value)}
        >
          <option value="">Select a show file…</option>
          {options.map((o) => (
            <option key={o.key} value={o.key}>
              {o.label}
            </option>
          ))}
        </select>

        {loaded && (
          <>
            <button
              onClick={() => setShowAspectPicker(true)}
              className="px-3 py-1 rounded-md border bg-white hover:bg-gray-50"
            >
              Change Format
            </button>
            <span className="text-xs opacity-80">
              <strong>Format:</strong> {currentAspect.label}{" "}
              <span className="opacity-60">
                ({currentAspect.width}×{currentAspect.height})
              </span>
            </span>
            <div className="flex items-center gap-2 border rounded-md px-2 py-1 bg-white shadow-sm">
              <span className="text-xs font-semibold uppercase tracking-wide text-gray-500">
                Burn Rate
              </span>
              <label className="flex items-center gap-1 text-xs text-gray-700">
                <input
                  type="number"
                  min={MIN_TOTAL_DURATION}
                  step="0.5"
                  value={burnRateInput}
                  onChange={(e) => setBurnRateInput(e.target.value)}
                  onKeyDown={handleBurnRateKeyDown}
                  className="w-16 border rounded px-1 py-0.5 text-right text-sm"
                />
                <span className="opacity-60">sec</span>
              </label>
              <label className="flex items-center gap-1 text-xs text-gray-700">
                <input
                  type="number"
                  min={0}
                  step="0.5"
                  value={burnPauseInput}
                  onChange={(e) => setBurnPauseInput(e.target.value)}
                  onKeyDown={handleBurnRateKeyDown}
                  className="w-16 border rounded px-1 py-0.5 text-right text-sm"
                />
                <span className="opacity-60">pause</span>
              </label>
              <button
                type="button"
                onClick={handleBurnRateApply}
                className="text-xs px-2 py-1 border rounded-md bg-blue-50 hover:bg-blue-100"
              >
                Apply
              </button>
            </div>
          </>
        )}

        {dirty && <span className="text-red-700">Unsaved changes</span>}

        <button
          onClick={saveAsMjs}
          className="px-3 py-1 rounded-md border bg-white hover:bg-gray-50"
          disabled={!loaded}
        >
          Save .mjs
        </button>

        {status && <span className="ml-auto text-xs opacity-70">{status}</span>}
      </div>

      {/* Aspect picker appears AFTER a show is selected */}
      {loaded && showAspectPicker && (
        <div className="mb-5 p-4 border rounded-lg bg-white shadow-sm">
          <div className="flex items-center justify-between mb-3">
            <h3 className="text-lg font-semibold">Select Output Format</h3>
            <button
              className="px-2 py-1 text-xs border rounded-md bg-gray-50 hover:bg-gray-100"
              onClick={() => setShowAspectPicker(false)}
            >
              Close
            </button>
          </div>
          <div className="grid sm:grid-cols-2 gap-2">
            {ASPECT_PRESETS.map((opt) => (
              <button
                key={opt.id}
                onClick={() => {
                  setAspectChoice(opt);
                  setShowAspectPicker(false);
                }}
                className={`text-left border rounded-md px-3 py-2 hover:bg-gray-50 ${
                  aspectChoice?.id === opt.id ? "bg-green-50 border-green-400" : ""
                }`}
              >
                <div className="font-medium">{opt.label}</div>
                <div className="text-xs opacity-70">
                  {opt.width} × {opt.height}
                </div>
              </button>
            ))}
          </div>
        </div>
      )}

      {!selectedPath && <p className="opacity-70">Select a show file to begin editing.</p>}

      {/* Grid */}
      {loaded && (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
            gap: "1rem",
          }}
        >
          {/* Intro card */}
          <div className="border rounded-lg overflow-hidden bg-white shadow-sm">
            <div
              className="relative bg-gray-50"
              style={{
                width: "100%",
                aspectRatio: String(currentAspect.ratio),
              }}
            >
              <div className="absolute inset-0 grid place-items-center text-xs text-gray-500">
                Intro Placeholder
              </div>
            </div>
            <div className="p-2">
              <div className="font-medium text-sm">Intro Slide 🎬</div>
              <div className="text-xs opacity-70 mb-2">Intro Meta ✨</div>
              <div className="flex flex-wrap gap-2">
                <button
                  onClick={handleIntroPanZoom}
                  className="px-3 py-1 text-xs border rounded-md bg-blue-50 hover:bg-blue-100"
                >
                  Edit Intro
                </button>
                <button
                  onClick={() => setShowIntro(true)}
                  className="px-3 py-1 text-xs border rounded-md bg-amber-50 hover:bg-amber-100"
                >
                  Edit Intro Text
                </button>
              </div>
            </div>
          </div>

          {/* Draggable slides */}
          {slides.map((s, index) => {
            const src = s.srcXL || s.srcL || s.srcM || s.src || "";
            const cachedPanZoom = panZoomCache[s.id] || s.panZoom;
            return (
              <div
                key={s.id}
                draggable
                onDragStart={(e) => onDragStart(e, index)}
                onDragOver={onDragOver}
                onDrop={(e) => onDrop(e, index)}
                className="relative border rounded-lg overflow-hidden bg-white shadow-sm cursor-move"
                title={`Drag to reorder`}
              >
                {/* Edited checkmark */}
                {cachedPanZoom && (
                  <div className="absolute top-1 right-1 bg-green-600 text-white text-[10px] font-bold px-1.5 py-0.5 rounded-full shadow-md z-10">
                    ✓
                  </div>
                )}

                {/* Aspect-correct preview window */}
                <div
                  className="relative bg-black"
                  style={{
                    width: "100%",
                    aspectRatio: String(currentAspect.ratio),
                    overflow: "hidden",
                  }}
                >
                  {src ? (
                    <img
                      src={src}
                      alt=""
                      className="absolute inset-0 w-full h-full object-cover select-none"
                      draggable={false}
                    />
                  ) : (
                    <div className="absolute inset-0 grid place-items-center text-xs text-gray-400">
                      No image
                    </div>
                  )}
                </div>

                <div className="p-2">
                  <div className="font-medium text-sm truncate">{s.title || s.id || "Untitled"}</div>
                  <div className="text-xs opacity-70 mb-2">
                    {s.panZoom ? "panZoom ✅" : "no panZoom ⚠️"}
                  </div>
                  <button
                    onClick={() =>
                      setEditingSlide({
                        ...s,
                        panZoom: cachedPanZoom,
                      })
                    }
                    className="px-3 py-1 text-xs border rounded-md bg-blue-50 hover:bg-blue-100"
                  >
                    Edit Pan/Zoom
                  </button>
                </div>
              </div>
            );
          })}

          {/* Outro card */}
          <div className="border rounded-lg overflow-hidden bg-white shadow-sm">
            <div
              className="relative bg-gray-50"
              style={{
                width: "100%",
                aspectRatio: String(currentAspect.ratio),
              }}
            >
              <div className="absolute inset-0 grid place-items-center text-xs text-gray-500">
                Outro Placeholder
              </div>
            </div>
            <div className="p-2">
              <div className="font-medium text-sm">Outro Slide 🏁</div>
              <div className="text-xs opacity-70 mb-2">Outro Meta ✨</div>
              <div className="flex flex-wrap gap-2">
                <button
                  onClick={handleOutroPanZoom}
                  className="px-3 py-1 text-xs border rounded-md bg-blue-50 hover:bg-blue-100"
                >
                  Edit Outro
                </button>
                <button
                  onClick={() => setShowOutro(true)}
                  className="px-3 py-1 text-xs border rounded-md bg-amber-50 hover:bg-amber-100"
                >
                  Edit Outro Text
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {loaded && (
        <div className="mt-6 flex justify-center">
          <button
            type="button"
            onClick={() => {
              if (!previewSlides.length) return;
              setShowPreview(true);
            }}
            className="px-4 py-2 text-sm font-medium rounded-md border bg-emerald-50 hover:bg-emerald-100 transition"
            disabled={!previewSlides.length}
          >
            Preview Show
          </button>
        </div>
      )}

      {/* Editors */}
      {editingSlide && (
        <PanZoomStageEditor
          slide={editingSlide}
          onSave={(data) => {
            updatePanZoom(editingSlide.id, data);
            setEditingSlide(null);
          }}
          onCancel={() => setEditingSlide(null)}
          // 👇 Pass aspect + resolution so the popup frames exactly right
          aspectRatio={currentAspect.ratio}
          resolution={{ width: currentAspect.width, height: currentAspect.height }}
        />
      )}

      {showIntro && (
        <IntroOutroEditor
          mode="intro"
          showMeta={storyMeta || {}}
          onSave={({ data }) => {
            setStoryMeta((prev) => ({
              ...(prev || {}),
              introMeta: {
                introText: data.introText || "K4 Studios presents the Fine Art Photography of Wayne Heim.",
                showTitle: data.showTitle || prev?.showTitle || "",
                tagline: data.tagline || "Embrace the Past... Live the Story.",
                // Stage assignments (1-3)
                introTextStage: data.introTextStage ?? 1,
                showTitleStage: data.showTitleStage ?? 2,
                taglineStage: data.taglineStage ?? 3,
                // Show/hide toggles
                showIntroText: data.showIntroText ?? true,
                showShowTitle: data.showShowTitle ?? true,
                showTagline: data.showTagline ?? true,
                // Piece ordering
                introPieceOrder: data.introPieceOrder || ["introText", "showTitle", "tagline"],
              },
            }));
            setDirty(true);
            setShowIntro(false);
          }}
          onCancel={() => setShowIntro(false)}
        />
      )}

      {showOutro && (
        <IntroOutroEditor
          mode="outro"
          showMeta={storyMeta || {}}
          onSave={({ data }) => {
            setStoryMeta((prev) => ({
              ...(prev || {}),
              outroMeta: {
                closingText:
                  data.closingText ||
                  "Every image is another notch in the belt, keeping history alive.",
                cta: data.cta || "Visit k4studios.com to explore more Picture Shows.",
                displayUrl:
                  data.displayUrl ||
                  `https://www.k4studios.com/pictureshow/${(prev?.showTitle || "unknown")
                    .toLowerCase()
                    .replace(/\s+/g, "-")}`,
              },
            }));
            setDirty(true);
            setShowOutro(false);
          }}
          onCancel={() => setShowOutro(false)}
        />
      )}

      {showPreview && previewSlides.length > 0 && (
        <StageReviewer
          mode="preview"
          images={previewSlides}
          outputResolution={{
            width: currentAspect?.width || ASPECT_PRESETS[0].width,
            height: currentAspect?.height || ASPECT_PRESETS[0].height,
          }}
          onExit={handlePreviewExit}
          audioRef={previewAudioRef}
        />
      )}

      <audio
        ref={previewAudioRef}
        onEnded={() => setPreviewSpeaking(false)}
        onPause={() => setPreviewSpeaking(false)}
        onPlay={() => setPreviewSpeaking(true)}
        style={{ display: "none" }}
      />

      <audio ref={previewAmbientAudioRef} loop style={{ display: "none" }} />
    </div>
  );
}
