// Canonical gallery landing pages.
// This list is used for dashboard classification and metrics bucketing.
// Keep in sync with the site nav / galleryPrefetchMap source of truth.

export const GALLERY_LANDING_PATHS = [
  '/Galleries/Painterly-Fine-Art-Photography/Facing-History/Civil-War-Portraits/Color',
  '/Galleries/Painterly-Fine-Art-Photography/Facing-History/Civil-War-Portraits/Black-White',
  '/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Color',
  '/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/Black-White',
  '/Galleries/Painterly-Fine-Art-Photography/Facing-History/Western-Cowboy-Portraits/NA-Color',
  '/Galleries/Painterly-Fine-Art-Photography/Facing-History/Roaring-20s-Portraits/Color',
  '/Galleries/Painterly-Fine-Art-Photography/Facing-History/Roaring-20s-Portraits/Black-White',
  '/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/War/Color',
  '/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/War/Black-White',
  '/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/Machines/Color',
  '/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/Machines/Black-White',
  '/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/Portraits/Color',
  '/Galleries/Painterly-Fine-Art-Photography/Facing-History/WWII/Portraits/Black-White',
  '/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Location/International/Gallery',
  '/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Location/Midwest/Gallery',
  '/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Location/Northeast/Gallery',
  '/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Location/South/Gallery',
  '/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Location/West/Gallery',
  '/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Theme/Mountains',
  '/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Theme/Water',
  '/Galleries/Painterly-Fine-Art-Photography/Landscapes/By-Theme/Sunsets',
  '/Galleries/Painterly-Fine-Art-Photography/Transportation/Trains-Color',
  '/Galleries/Painterly-Fine-Art-Photography/Transportation/Trains-Black-White',
  '/Galleries/Painterly-Fine-Art-Photography/Transportation/Cars',
  '/Galleries/Painterly-Fine-Art-Photography/Miscellaneous/Portraits',
  '/Galleries/Fine-Art-Photography/Landscapes/By-Location/International/Canada-Western',
  '/Galleries/Fine-Art-Photography/Landscapes/By-Location/International/The-Faroe-Islands',
  '/Galleries/Fine-Art-Photography/Landscapes/By-Location/International/Iceland',
  '/Galleries/Fine-Art-Photography/Landscapes/By-Location/International/Newfoundland',
  '/Galleries/Fine-Art-Photography/Landscapes/By-Location/Midwest/Gallery',
  '/Galleries/Fine-Art-Photography/Landscapes/By-Location/Northeast/Gallery',
  '/Galleries/Fine-Art-Photography/Landscapes/By-Location/South/Gallery',
  '/Galleries/Fine-Art-Photography/Landscapes/By-Location/West/Gallery',
  '/Galleries/Fine-Art-Photography/Landscapes/By-Theme/Mountains',
  '/Galleries/Fine-Art-Photography/Landscapes/By-Theme/Water',
  '/Galleries/Fine-Art-Photography/Landscapes/By-Theme/Sunsets',
  '/Galleries/Fine-Art-Photography/Landscapes/By-Theme/Color',
  '/Galleries/Fine-Art-Photography/Landscapes/By-Theme/Black-White',
  '/Galleries/Fine-Art-Photography/Portraits/Color',
  '/Galleries/Fine-Art-Photography/Portraits/Black-White',
  '/Galleries/Fine-Art-Photography/Portraits/Reenactors',
  '/Galleries/Fine-Art-Photography/Transportation/Boats',
  '/Galleries/Fine-Art-Photography/Transportation/Cars',
  '/Galleries/Fine-Art-Photography/Transportation/Military',
  '/Galleries/Fine-Art-Photography/Transportation/Planes',
  '/Galleries/Fine-Art-Photography/Transportation/Trains',
  '/Galleries/Fine-Art-Photography/Architecture/Gallery',
  '/Galleries/Fine-Art-Photography/Miscellaneous/Reenactments',
  '/Galleries/Fine-Art-Photography/Miscellaneous/Pets',
  '/Galleries/Fine-Art-Photography/Miscellaneous/Wildlife',
  '/Other/K4-Select-Series/Engrained/Engrained-Series',
];
