/** @type {import('tailwindcss').Config} */
module.exports = {
  corePlugins: {
    accentColor: false,
    appearance: false,
    caretColor: false,
    userSelect: false,
  float: false,
  aspectRatio: false,
  container: false,
  pointerEvents: false,
  ringColor: false,
  ringOffsetColor: false,
  ringOffsetWidth: false,
  ringOpacity: false,
  ringWidth: false,
  stroke: false,
  strokeWidth: false,
  textDecoration: false,
  textDecorationColor: false,
  textDecorationStyle: false,
  textDecorationThickness: false,
  textUnderlineOffset: false,
  touchAction: false,
  willChange: false,
  clear: false,
  isolation: false,
  objectFit: false,
  objectPosition: false,
  overscrollBehavior: false,
  placeItems: false,
  placeSelf: false,
  resize: false,
  scrollSnapAlign: false,
  scrollSnapType: false,
  verticalAlign: false,
  visibility: false,
  whitespace: false,
  wordBreak: false,
  animation: false,
  backdropBlur: false,
  backdropBrightness: false,
  backdropContrast: false,
  backdropGrayscale: false,
  backdropHueRotate: false,
  backdropInvert: false,
  backdropOpacity: false,
  backdropSaturate: false,
  backdropSepia: false,
  backgroundBlendMode: false,
  blur: false,
  brightness: false,
  contrast: false,
  dropShadow: false,
  filter: false,
  grayscale: false,
  hueRotate: false,
  invert: false,
  mixBlendMode: false,
  opacity: false,
  saturate: false,
  sepia: false,
  transitionProperty: false,
  backgroundAttachment: false,
  backgroundClip: false,
  backgroundOrigin: false,
  backgroundPosition: false,
  backgroundRepeat: false,
  backgroundSize: false,
  borderCollapse: false,
  borderSpacing: false,
  boxDecorationBreak: false,
  boxSizing: false,
  columns: false,
  divideColor: false,
  divideOpacity: false,
  divideStyle: false,
  divideWidth: false,
  flexBasis: false,
  flexDirection: false,
  flexGrow: false,
  flexShrink: false,
  flexWrap: false,
  gridAutoColumns: false,
  gridAutoFlow: false,
  gridAutoRows: false,
  gridColumn: false,
  gridColumnEnd: false,
  gridColumnStart: false,
  gridRow: false,
  gridRowEnd: false,
  gridRowStart: false,
  gridTemplateColumns: false,
  gridTemplateRows: false,
  fontVariantNumeric: false,
  gridAutoColumns: false,
  gridAutoFlow: false,
  gridAutoRows: false,
  gridColumn: false,
  gridColumnEnd: false,
  gridColumnStart: false,
  gridRow: false,
  gridRowEnd: false,
  gridRowStart: false,
  gridTemplateColumns: false,
  gridTemplateRows: false,
  overscrollBehavior: false,
  tableLayout: false,
  zIndex: false,
  alignContent: false,
  alignSelf: false,
  justifyContent: false,
  justifyItems: false,
  justifySelf: false,
  order: false,
  space: false,
  flexBasis: false,
  flexDirection: false,
  flexGrow: false,
  flexShrink: false,
  flexWrap: false,
 // dont remove:  inset: false,
  },
  content: [
    './src/**/*.{astro,js,jsx,ts,tsx,mdx,html,vue,svelte}',
    './public/**/*.html',
  ],
  safelist: [
    'carousel',
    'carousel-track',
    'carousel-slide',
    'carousel-fade',
    'carousel-fadein',
    'carousel-fullsize',
    'k4-home-carousel-img',
    'k4-home-carousel-img--1',
    'k4-home-carousel-img--2',
    'k4-home-carousel-img--3',
    'k4-home-carousel-img--4',
    'k4-home-carousel-img--5',
    'k4-home-carousel-img--6',
    'k4-home-carousel-img--7',
    'k4-home-carousel-img--8',
    'fade-in',
    'loaded',
    'reveal-on-scroll',
    'slide-in-left',
    'tagline',
    'kw-link',
    // Basic utility classes that might be needed
    'flex',
    'block',
    'inline',
    'inline-block',
    'hidden',
    'relative',
    'absolute',
    'fixed',
    'static',
    'text-center',
    'text-left',
    'text-right',
    'mx-auto',
    'w-full',
    'h-full',
    'max-w-full',
    'overflow-hidden',
    'overflow-auto',
    'p-4',
    'm-4',
    'bg-white',
    'bg-black',
    'text-black',
    'text-white',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};